### ISSUE TITLE
Allow wildcards as path for resolversComposition 

### ISSUE THREAD

**Issue by gagoar** [Urigo/graphql-modules#1015]
Thanks for building this amazing system. it makes GraphQL easy to maintain and evolve over time. ❤️

### Context
`resolversComposition` as explained [here](https://github.com/Urigo/graphql-modules/blob/ac5cbdf0a27509e5d1b600029f47871794971f28/docs/introduction/resolvers-composition.md) can take a query path and append logic before the resolver is invoked on run time.

We have leveraged `resolversComposition` to provide authorization. This approach has proven to be helpful and at the same time, it produces too many functions per query paths In order to ensure we are catching every possible call that comes to the type/field. 

If we had the possibility to use wild cards to make sure we can catch any query path it will make this feature more resilient and lightweight.

### Benefits. 
 - _**Backward compatibility**_: the current behavior will not change. 
 - **_lightweight_**: Fewer functions need to be generated to catch every possible path. 
 - _**More composable**_: we can relay on tiering when adding functions to query paths.  

### Possible Use Case

Taking up the current example [here](https://github.com/Urigo/graphql-modules/blob/ac5cbdf0a27509e5d1b600029f47871794971f28/docs/introduction/resolvers-composition.md) and adding wildcards, we could have something like: 

```typescript
import { GraphQLModule } from '@graphql-modules/core';

const MyModule = new GraphQLModule({
  /*...*/
  resolversComposition: { 
   'Query.myQuery': [hasRole('EDITOR')], // => Query.myQuery will work as it used to. 
   'SuperSecured.*': [isAuthenticated()] // => Any query to a particular field of `SuperSecured` type will call `isAtuhenticated`. 
   'Mutation.*': [isAuthenticated()] // => All mutations will call `isAuthenticated`. 
  }
});
```
I can see how we could expand the wildcards to follow some standard such [glob wildcards](https://en.wikipedia.org/wiki/Glob_(programming)) given that [minimatch](https://www.npmjs.com/package/minimatch) already has glob patterns implemented.   

Thanks!

**Comment by ardatan** [comment]
Resolvers Composition has already support for `*` wildcards for fields as you said. Let us know if it doesn't work properly.

**Comment by gagoar** [comment]
@ardatan  I will check and make sure what I'm proposing is already there, and update the documentation accordingly

**Comment by gagoar** [comment]
closing this pr, in favor of https://github.com/Urigo/graphql-modules/pull/1027
