### ISSUE TITLE
Duplicate Instantiation of Providers leading to n+1 problem

### ISSUE THREAD

**Issue by piyugupt** [Urigo/graphql-modules#1025]
Using ProviderScope.Session , I still see duplicate instances of Provider being created within the same GQL Query Request, which is leading to the n+1 problem in our use case. Code snippets below.

```
@Injectable({
    scope: ProviderScope.Session
  })
export class MyProvider extends RESTDataSource {
      constructor() {
          super();
        }
    }
```

```
const myModule= new GraphQLModule({
    typeDefs,
    resolvers,
    providers: [MyProvider],
    imports: [commonModule]
  });
```

```
const resolvers: Resolvers = {
    Query: {
      myQuery: async (root, args, { injector }: ModuleContext) => injector.get(MyProvider).getSomeData()
    }
  };
```

RestDataSource uses an in-memory memoizedResults Map to avoid multiple outgoing requests to the same API within the same GQL Query request, but since we have multiple Provider instances being created for the same Provider within the same Query request, it leads to unnecessary duplicate API requests going out.
I am using the following versions:
```
"@graphql-modules/core": "^0.7.7",
"@graphql-modules/di": "^0.7.7",
"apollo-datasource-rest": "^0.5.0",
```

**Comment by kamilkisiela** [comment]
We released a new major version (v1.0) of GraphQL Modules. Here's the [migration guide](https://graphql-modules.com/docs/next/recipes/migration).

The new version solves the issue, so I'm closing the thread.

Please try to upgrade. If you can't and still want to use the legacy version, please open a new issue.
