### ISSUE TITLE
Context builders `session` parameter does not contain `req` and `res`

### ISSUE THREAD

**Issue by sassman** [Urigo/graphql-modules#1032]
given the installed versions of
```
    "apollo-server": "^2.11.0",
    "graphql": "^14.6.0",
```
and a plain vanilla `ApolloServer` usage without any express app or middleware the context builder first argument `session` does not contain `req` and `res` in a GQL Module.

let's pick that example from the [docs](https://graphql-modules.com/docs/introduction/context#context-builders) where the `AuthModule` should have access to the request object. 

```typescript
export const AuthModule = new GraphQLModule({
  typeDefs,
  resolvers,
  providers: [AuthenticationProvider],
  async context(session: any, currentContext, { injector }) {
    const req = session.req; // is undefined
  }
});
``` 

but when I put this context builder directly in the ApolloServer config like this then it works:
```typescript
const server = new ApolloServer({
  modules: [AppModule],
  context: ({ req, res }) => {
    console.log(req.headers['authorization']);  // here req is not undefined, all works as expected
  }
});
```

I very much doubt that this is the intended behaviour. But if so, then the docs are pretty much misleading.

**Comment by sassman** [comment]
My workaround is to return the authorization header from the ApolloServers context builder, so that I can access it in the AuthModule like below. But that is far from being ideal:

```typescript
const server = new ApolloServer({
  modules: [AppModule],
  context: ({req, res}) => ({
    authHeader: req.headers['authorization'],
  })
});
```

```typescript
export const AuthModule = new GraphQLModule({
  providers: [UserProvider],
  typeDefs,
  resolvers,
  context: ({ authHeader }, currentContext, { injector }) => {
    console.log(authHeader);
  }
});
```

**Comment by ardatan** [comment]
Could you try it like below?;
```ts
const { schema } = AppModule;
const server = new ApolloServer({
  schema,
  context: session => session,
});
```

**Comment by sassman** [comment]
@ardatan 

yes populating the whole session there like you suggested `context: session => session` works as expected.

I guess that important detail needs to go into the docs mentioned above. 

Thanks for the help

**Comment by sassman** [comment]
actually I think the way how the `AppModule` should be used by the AplloServer was not ideal. Seems that below works good: 

```typescript
const server = new ApolloServer({
  modules: [AppModule],
  context: AppModule.context
});
```

**Comment by ardatan** [comment]
GraphQL Modules internally calls context builder functions already if used. If you do `AppModule.context`, it would call all the context functions in every request even if they are not used. So `context: session => session` is correct usage.
