### ISSUE TITLE
Support async factories in providers

### ISSUE THREAD

**Issue by LucienLee** [Urigo/graphql-modules#1071]
As @ardatan you mentioned at #145
> In my opinion, we should support async factories in providers like useFactory: async() => { ... }

I totally agree with you about that. But In my test, it can not work. How do you think about supporting this feature?

Related issue: #525

**Comment by kamilkisiela** [comment]
We decided not to support async factories, yet. Keeping it sync works just fine and all the async logic can be done directly within DI.
