### ISSUE TITLE
Usage example for testing

### ISSUE THREAD

**Issue by dandv** [Urigo/graphql-modules#1078]
Not sure where to submit a PR for this, but wanted to share how I managed to fix this error:

> GraphQLError: Cannot read property 'session' of null

In was migrating from vanilla GraphQL. In a unit test, I was calling

    await graphql(schema, query, null, null, variables);

Converting to graphql-modules, that became

    await graphql(MyModule.schema, query, null, null, variables);

The problem was that the 4th parameter, contextValue, has to be an identity function:

```js
await graphql(MyModule.schema, query, null, session => session, variables);
```

/hattip: [this comment](https://github.com/Urigo/graphql-modules/issues/673#issuecomment-530652740)

**Comment by ardatan** [comment]
In GraphQL-js, `contextValue` is not the same thing with `context` factory function of Apollo Server. As you can see in our tests, you need to send an empty object like below;
```
await graphql(MyModule.schema, query, null, {}, variables);
```

**Comment by dandv** [comment]
How can I pass a value during tests (to mock an authenticated user, for example)? I tried putting it [inside the context object instead of `{}`](https://github.com/dandv/graphql-modules-context-test/blob/master/src/test.ts#L9), but it [doesn't appear to be passed to the resolver](https://github.com/dandv/graphql-modules-context-test/blob/master/src/app/user/user.module.ts#L21).

[Repro repo](https://github.com/dandv/graphql-modules-context-test) based on the `apollo-modules` sample.

**Comment by dandv** [comment]
For others landing here, I've [added](https://github.com/Urigo/graphql-modules/pull/1132/files) an example to the [test your module](https://graphql-modules.com/docs/introduction/test-your-module) page.
