### ISSUE TITLE
Add `visitSchemaDirectives` option

### ISSUE THREAD

**Issue by danielrearden** [Urigo/graphql-modules#1086]
In order to apply the schema directives added by each module, we have to manually call `SchemaDirectiveVisitor.visitSchemaDirectives` after getting the schema from the root module, as shown in #381 . 

I get that it's important to do it this way to avoid applying the same directive more than once. However, it would be nice DX to at least have a `visitSchemaDirectives` option that could be passed to the root module to automatically call `visitSchemaDirectives` for you.

At the very least, the existing workaround should probably be documented so that it's clear schema directives won't work without it.

**Comment by ardatan** [comment]
Available in 0.7.17!
