### ISSUE TITLE
@nexus/schema integration and Cannot return null for non-nullable field

### ISSUE THREAD

**Issue by lewebsimple** [Urigo/graphql-modules#1116]
I'm getting `Cannot return null for non-nullable field` when trying to use `@nexus/schema` inside a module with `extraSchemas`.

Reproduction repo here: https://github.com/lewebsimple/test-graphql-modules

**Comment by wuichen** [comment]
i can confirm seeing the same error while using @nexus/schema

**Comment by kamilkisiela** [comment]
Closing in favor of #1466
