### ISSUE TITLE
make resolverComposition act on implicit field resolvers

### ISSUE THREAD

**Issue by dandv** [Urigo/graphql-modules#1137]
Consider a `User` type where the `email` field comes straight from the User object. There's no need to define a trivial resolver for the `email` field.

Now consider that the email filed requires the request to have a certain role.

```ts
resolversComposition: {
  'User.email': [hasRole('admin')]
}
```

This won't enforce anything on the email field, unless I do write that trivial field resolver:

```ts
resolvers: {
  User: {
    email: u => u.email
  }
}
```

Semantically, the code above is clutter. Would it be possible for the resolver composition to act on these unspecified field resolvers too?

**Comment by kamilkisiela** [comment]
We released a new major version (v1.0) of GraphQL Modules. Here's the [migration guide](https://graphql-modules.com/docs/next/recipes/migration).

The new version solves the issue, so I'm closing the thread.

Please try to upgrade. If you can't and still want to use the legacy version, please open a new issue.
