### ISSUE TITLE
Troubleshooting section with circular dependency error

### ISSUE THREAD

**Issue by dandv** [Urigo/graphql-modules#1140]
I've run a few times into errors like, `TypeError: MyModule_1.myFunction is not a function`, when `myFunction` was clearly defined in the module. The cause was a circular dependency and the solution was to move the definition of myFunction into the same module as the one used in the function.

Since this is not an intuitive error, it should be mentioned in a Troubleshooting or FAQ section somewhere.

**Comment by kamilkisiela** [comment]
We released a new major version (v1.0) of GraphQL Modules. Here's the [migration guide](https://graphql-modules.com/docs/next/recipes/migration).

The new version solves the issue by implementing a much more DX friendly Dependency Injection mechanism, so I'm closing the thread.

Please try to upgrade. If you can't and still want to use the legacy version, please open a new issue.
