### ISSUE TITLE
Doesn't import interfaces from another module

### ISSUE THREAD

**Issue by 7HUND3RX** [Urigo/graphql-modules#1159]
Following is code example, I'm trying to implement:

Module A TypeDefs:
```
  interface Timestamped {
    createdAt: Date!
    lastModifiedAt: Date
  }

``` 

Module B TypeDefs:
```
  type Animal implements Timestamped {
    id: ID!
    name: String!

    createdAt: Date!
    lastModifiedAt: Date
  }
```

module-b/index.ts:
```
import ModuleA from '../module-a';

export default new GraphQLModule({
  name: 'Animal Module',
  typeDefs: [schema],
  resolvers: [{ Mutation, Query }],
  imports: [ModuleA],
});
```

Gives me following error:
```
SchemaNotValidError: 
      GraphQL-Modules Error: Schema is not valid!
      - #Module #Animal Module doesn't have a valid schema!
      -- Unknown type "Timestamped".

      Possible solutions:
      - Check syntax errors in typeDefs
      - Make sure you import correct dependencies
```

**Comment by zomble** [comment]
I am getting this issue. I'm not sure what has caused it.

This was functioning. ... Back tracking versions too:

`
    "@graphql-modules/core": "0.7.14",
    "graphql": "~14.6.0",
    "graphql-tools": "~4.0.7",
`

I can get this functioning again.

@7HUND3RX can you confirm?

@ardatan thoughts?

**Comment by 7HUND3RX** [comment]
@zomble I can confirm that it works with the versions you have mentioned but fails with this:

`"@graphql-modules/core": "0.7.17", "graphql": "~15.0.0",`

**Comment by TAnas0** [comment]
I can confirm the original issue, but I cannot make it work with previous versions either.
Here is a minimal example for reproduction purposes: https://github.com/TAnas0/graphql-modules-sample
Use `yarn && yarn start`

It is not working with the following versions (output of `yarn list @graphql-modules graphql`):
```
├─ @graphql-modules/core@0.7.17
└─ graphql@15.1.0
```

```
├─ @graphql-modules/core@0.7.13
└─ graphql@15.1.0
```

```
├─ @graphql-modules/core@0.7.13
└─ graphql@14.6.0
```

```
├─ @graphql-modules/core@0.7.14
└─ graphql@14.6.0
```

**Comment by jeromecovington** [comment]
I can also verify that pinning to the versions @zomble defined, gets me past the unknown types error.
