### ISSUE TITLE
Integration with Koa Middleware?

### ISSUE THREAD

**Issue by rahul22048** [Urigo/graphql-modules#1172]
Does graphql modules integrate with koa middleware as well? Because in none of the examples i saw koa being used as a middleware. Also we were trying to migrate from express to koa, but we are facing issues in it, especially around context object.

**Comment by ardatan** [comment]
If you have a reproduction for your issues with Koa and GraphQL Modules, we can help you better. I think it should work properly.

**Comment by rahul22048** [comment]
So, we have one module let's call it common module, which was included in every other module. The job of this module was to set credentials inside context object. It's initialisation went something like below:-
...
const commonModule = new GraphQLModule({
  typeDefs,
  resolvers,
  context: (session: { req?: Request }) => createContext(session.req)
});
...
Request is actually of type Express.Request. But while migration to koa i changed the type to koa.Request, after that it stopped working. Koa.Request turned out to be undefined.

Also i am using apollo-server-koa package , and applied koa as a  middleware. Endpoint other than  /graphql, seems to be working fine. Infact the modules which does not require any credentials to be set are also working fine, but the ones where credential needs to be set are not working fine.

**Comment by rahul22048** [comment]
So actually the request object inside session is not getting correctly set, it is undefined. Whereas in case of express, request object was properly set inside session object.

**Comment by ardatan** [comment]
How do you create `ApolloServer` instance? And if you share a minimal reproduction, that would be better..

**Comment by rahul22048** [comment]
const { schema, context } = appModules.forRoot({});
const server = new ApolloServer({
    schema,
    context,
    tracing: true,
    playground: config.enablePlayground
  });
  server.applyMiddleware({ app,path:'/graphql'});

**Comment by rahul22048** [comment]
appModules basically is collection of all the graphql modules

**Comment by rahul22048** [comment]
@ardatan :- Any finding on this issue?

**Comment by ardatan** [comment]
@rahul22048 Could you create a reproduction as a GitHub repo or CodeSandbox?

**Comment by rahul22048** [comment]
I can't do that with my live production code. To repro this , you just need to change dependency from apollo-server-express to apollo-server-koa, and see everything works fine. Bug could also be on apollo-server-koa package, where some pieces are missing.

**Comment by ardatan** [comment]
@rahul22048 I don't need your code. Could you do that on CodeSandbox or GitHub repo?

**Comment by zomble** [comment]
Koa context shows up in under session.ctx. @rahul22048 you might be looking for session.ctx.request.

`apollo-server-koa` is not a drop in replacement for `apollo-server-express`
