### ISSUE TITLE
enum values not resolved to internal values

### ISSUE THREAD

**Issue by dandv** [Urigo/graphql-modules#1176]
[This CSB](https://codesandbox.io/s/apollo-server-typescript-starter-xx5jk?file=/index.ts) is using graphql-tools directly to echo the value of an enum. It works as expected, returning the internal values for these queries:

```gql
{
  #expect "1"
  echo(status: PENDING)
  # expect "2"
  echoDefault: echo
}
```

[This GraphQL Modules CSB](https://codesandbox.io/s/graphql-modules-apollo-server-typescript-starter-mhd7m?file=/index.ts) uses exactly the same code, but the typeDefs and resolvers are passed to `new GraphQLModule(...)` instead of `makeExecutableSchema`.

When running the same queries as above, the results are strings:

```
{
  "data": {
    "echo": "PENDING",
    "echoDefault": "APPROVED"
  }
}
```

Note that this is different from [the older graphq-tools bug of not resolving default enum values](https://github.com/ardatan/graphql-tools/issues/715#issuecomment-638519739). Even the explicitly passed `PENDING` value is not resolved.

**Comment by ardatan** [comment]
Could you create a reproduction repo or CodeSandbox?

**Comment by dandv** [comment]
It's linked in my OP under "This GraphQL Modules CSB". Did you manage to reproduce?

**Comment by ardatan** [comment]
My bad :( I'm taking a look. Thanks!

**Comment by ardatan** [comment]
This is not a GraphQL Modules bug but Apollo Server's. There is a bug in Apollo Server so we don't recommend you to use `modules` property of Apollo Server. Please pass `UserModule.schema` to `schema` instead of `modules` and try again.

**Comment by dandv** [comment]
Thanks @ardatan, that worked.
