### ISSUE TITLE
Testing AppModule with different config options

### ISSUE THREAD

**Issue by darkbasic** [Urigo/graphql-modules#1179]
My main `AppModule` accepts a configuration object which sets several options into a `CommonModule`, which then gets used by the whole application.

For example the `AppModule` accepts a time `format`, which gets passed to the `CommonModule` which then uses that value to instantiate a provider used by the `TimeModule`: https://github.com/darkbasic/graphql-modules-multiple-configurations-test

Everything works, but I'm having some issues with the tests: in fact if I want to test it with both the `24h` and `am/pm` time formats it keeps using the old values when I instantiate the `AppModule` for the second time (https://github.com/darkbasic/graphql-modules-multiple-configurations-test/blob/master/src/index.ts).
I've found that importing the `TimeModule` with `.forRoot({})` (https://github.com/darkbasic/graphql-modules-multiple-configurations-test/blob/master/src/app.module.ts#L8) somehow fixes the issue, but it's a workaround.

What's the suggested way to test the `AppModule` with multiple different configs?

**Comment by ardatan** [comment]
@darkbasic You can try `forChild`.

**Comment by darkbasic** [comment]
Hi @ardatan , I've tried it but somehow doesn't work.

**Comment by kamilkisiela** [comment]
We released a new major version (v1.0) of GraphQL Modules. Here's the [migration guide](https://graphql-modules.com/docs/next/recipes/migration).

The new version solves the issue, so I'm closing the thread. Config is now something defined directly in Dependency Injection.

Please try to upgrade. If you can't and still want to use the legacy version, please open a new issue.
