### ISSUE TITLE
GraphQL Toolkit is deprecated and merged into GraphQL Tools

### ISSUE THREAD

**Issue by lewebsimple** [Urigo/graphql-modules#1183]
Are there any plans to upgrade GraphQL Modules to the new GraphQL Tools ?

**Comment by ardatan** [comment]
Hi @lewebsimple !
Yes, we will be using new GraphQL Tools in the next release of GraphQL Modules.
You can see the progress here;
https://github.com/Urigo/graphql-modules/pull/1177

**Comment by kamilkisiela** [comment]
We released a new major version (v1.0) of GraphQL Modules. Here's the [migration guide](https://graphql-modules.com/docs/next/recipes/migration).

The new version solves the issue, so I'm closing the thread.

Please try to upgrade. If you can't and still want to use the legacy version, please open a new issue.
