### ISSUE TITLE
graphql.js version 15 compatibility

### ISSUE THREAD

**Issue by artecoop** [Urigo/graphql-modules#1199]
Hello all!
I've happily integrated graphql-modules with the Fastify ecosystem and it's working very good.

But since they released fastify-gql 4.0.0 a couple of days ago, there is a problem with this integration: every query returns `Unknown operation named "".`

As you can see on this issue I opened on their repo
https://github.com/mcollina/fastify-gql/issues/183
the culprit **_seems_** not to be fastify-gql, but somewhat graphql.js version 15 and graphql-modules.

For your commodity, I link here the minimal repro I used to show the problem:
https://codesandbox.io/s/keen-sara-hs6f5

I can't find any package dependent to graphql.js in the graphql-modules tree. 
If someone can point me where this interaction could happen, I'll be glad to check and test if there is something I can do about.

**Comment by ardatan** [comment]
It looks like a problem with the server itself because that error looks an execution error from server. So when I give a name to the operation, it works as expected.

```gql
# Write your query or mutation here
query test {
  getAll{
    firstName
  }
}
```

**Comment by artecoop** [comment]
Well, this is working. A huge thank you!!!!

There is a change in grapqhl.js that require named queries? With 14.6.0 the operation name was not mandatory.

Thanks again!!!!!

**Comment by ardatan** [comment]
You're welcome :) I don't think it is graphql-js;
https://codesandbox.io/s/admiring-wescoff-ejkdp?file=/src/index.js
You can see vanilla graphql-js works as expected with unnamed operations.

**Comment by numToStr** [comment]
I guess this was the change which caused the issue https://github.com/graphql/graphql-js/pull/2149

**Comment by ardatan** [comment]
@numToStr Hmm I see so it is how you call it :) But it's fixed at least
