### ISSUE TITLE
Apollo Context with GraphQL Modules

### ISSUE THREAD

**Issue by piyugupt** [Urigo/graphql-modules#1205]
We are in the process of merging GraphQL Schema's across few different Teams into a Single GraphQL Service. Some of these Schema/Resolvers use GraphQL Modules, while others don't, but all of these use a common Wrapper over RestDataSource, which uses context data to make certain optimizations in upstream calls.
I notice that the Context I set in Apollo Server is not available for use in GraphQL Modules, and the corresponding RestDataSource implementation. Is there a way to achieve this sharing of context between Apollo & GraphQL Modules. Sample code below,

```
......
const myModule = new GraphQLModule({
  typeDefs,
  resolvers,
  providers: [MyModuleProvider]
});
MyModuleProvider extends CommonRestDataSource {
...
}

const server = new ApolloServer({
    modules,
    schema,
    context,
    datasources
  });
```

**Comment by ardatan** [comment]
You can access the global context with `session` parameter.

**Comment by piyugupt** [comment]
Added Sample code in github repo, https://github.com/piyugupt/test-gqlmodulecontext/blob/master/src/core/base-rest-data-source.ts#L9 
Can you help with an example on how to use the session parameter in this case to access the Apollo Context

**Comment by piyugupt** [comment]
Found a solution for this, sample code below.
`const myModule = new GraphQLModule({
  typeDefs,
  resolvers,
  providers: [MyProvider],
  context: session => session
});`
