### ISSUE TITLE
Performance issues with child modules

### ISSUE THREAD

**Issue by Myrannas** [Urigo/graphql-modules#1222]
Hi! 

While profiling our services we have noticed performance issues while resolving services from child modules - in particular a significant amount of time is spent in the `ServiceIdentifierNotFoundError` constructor.

<img width="817" alt="Screen Shot 2020-07-03 at 10 29 13 pm" src="https://user-images.githubusercontent.com/555736/86580760-7a9ea780-bfc2-11ea-8c40-fd6ceda5c66a.png">

I have made some tweaks that'd I'd be keen to contribute upstream if possible that reduce the impact of this, by only constructing the exception if we can't resolve the service (https://github.com/Myrannas/graphql-modules/commit/1087ef1569e0e8ad7d9915401b35e4ad184db655). Are you open to contributions?

<img width="817" alt="Screen Shot 2020-07-03 at 10 25 09 pm" src="https://user-images.githubusercontent.com/555736/86580817-90ac6800-bfc2-11ea-9ac5-c3005870d219.png">

**Comment by kamilkisiela** [comment]
We released a new major version (v1.0) of GraphQL Modules. Here's the [migration guide](https://graphql-modules.com/docs/next/recipes/migration).

The new version solves the issue, so I'm closing the thread.

Please try to upgrade. If you can't and still want to use the legacy version, please open a new issue.
