### ISSUE TITLE
Provider Initialization missing when injecting into context function

### ISSUE THREAD

**Issue by markw351** [Urigo/graphql-modules#1242]
Using

@graphql-modules/core": "^0.7.17"
@graphql-modules/di": "^0.7.17"

I notice an issue with a provider (Apollo RESTDatasource based class) that was complaining of an undefined context when calling the willSendRequest method, as this is where we set the Authorization header.

When calling the injected provider in a resolver this is all fine, eg

```
export const resolvers = {
  Query: {
    customer: async (root, args, { injector, user }) => {
      return await injector.get(UserDataSource).customer(user.id);
    },
  },
};
```

however when making the same call inside the context function of a module

```
context: async (session, { token, user }, { injector }) => {
    if (user && user.id) {
      const customer = await injector.get(UserDataSource).customer(user.id);
      return {
        user: {
          ...user,
          ...customer,
        },
      };
    }
    return;
  },
```
The initialize method on the datasource is never called, so context is undefined thus the error I'm seeing. This also means this Datasource would also be lacking the cache so not taking advantage of any previous calls this DS might have made for the same data. The [documention](https://graphql-modules.com/docs/introduction/context) on context builders citing auth as an example has an injected provider so it would appear that this would be a valid use case.

**Comment by ardatan** [comment]
Could you please create a reproduction?
