### ISSUE TITLE
Seeing undefined arg data when using `imports` making some resolvers useless

### ISSUE THREAD

**Issue by smolinari** [Urigo/graphql-modules#1243]
Hi,

As noted [in Discord](https://discord.com/channels/625400653321076807/631489837416841253/735107328587726860), I think I've possibly found a bug, or my usage of both TypeGraphQL and GraphQL-Modules isn't as it should be. Either way, I'd like someone with much more experience to have a look. 

Here is the reproduction: https://github.com/smolinari/gql-modules-test

Follow the readme.md of that repo to get the server running. 

Then run this query:

```
query{getOneRecipe(id: 1){
  id
  title
  description
}}
```
You can see the error: `Cannot return null for non-nullable field Query.getOneRecipe.` ( I realize this should be  nullable field, however, if I add the null check, then it will just return null, when it should return the recipe.) This error happens because the argument `id` is undefined getting to the resolver. You'll see, in `BaseResolver`, I'm console.logging out the `id` argument and it shows in the terminal as `undefined`. 

If you go to `index.ts` and comment out the `UserModule` within the `imports` property of the `GraphQLModule` config parameter, then the query will work, which I believe proves the collision happening with importing. 

Scott

**Comment by smolinari** [comment]
I've changed direction and also found it might be an issue with Apollo too. Closing.

Scott

**Comment by smolinari** [comment]
Actually, I'm reopening, as GraphQL-Modules seems to be broken with Type-GraphQL and I'd like to see the two working together. Thanks. 

Scott

**Comment by agustif** [comment]
> Actually, I'm reopening, as GraphQL-Modules seems to be broken with Type-GraphQL and I'd like to see the two working together. Thanks.
> 
> Scott

Hey @smolinari you have a working implementation by graphql-modules author.
I used it to see how to work out graphql+modules + typegraphql+typeorm, it works great as I have only a model file which both declare the db entity (typeorm) and graphql type https://github.com/ardatan/TypeGraphQLModules

**Comment by smolinari** [comment]
Yeah, that template used to work. It doesn't since TypeGraphQL went 1.0. See this issue too.

https://github.com/ardatan/TypeGraphQLModules/issues/31

And I see you commented in that issue too, so you are aware of the incompatibility.

Scott

**Comment by agustif** [comment]
> Yeah, that template used to work. It doesn't since TypeGraphQL went 1.0. See this issue too.
> 
> [ardatan/TypeGraphQLModules#31](https://github.com/ardatan/TypeGraphQLModules/issues/31)
> 
> And I see you commented in that issue too, so you are aware of the incompatibility.
> 
> Scott

Checkout the other one which is updated for type-graphql 1.0.0rc3 https://github.com/MichalLytek/type-graphql/tree/master/examples/graphql-modules

I can confirm I have typegraphql v1 and graphql-modules  "^0.7.18-alpha-6c93635.67", working together

**Comment by smolinari** [comment]
And I can confirm, that it doesn't work. My use case might be different than yours, so 🤷  

Scott

**Comment by agustif** [comment]
> And I can confirm that it doesn't work ( I upgraded to the same version you are using). My use case might be different than yours, so 🤷
> 
> Btw, are you using Apollo Server with Express? Or just graphql-express? That might be the key difference too.
> 
> Scott

Yes I'm using Apollo-Server-Express

Your resolvers and mine are very different though

**Comment by smolinari** [comment]
They are just using resolver inheritance also taken from the TypeGraphQL examples.

What do your resolvers look like? Can you show an example or link to your code?

Scott

**Comment by agustif** [comment]
```document.resolver.ts
import {
  Arg,
  Mutation,
  Query,
  Resolver,
} from 'type-graphql';

import { Injectable } from '@graphql-modules/di';

import { CreateDocumentInput } from '../inputs/create.document.input';
import { UpdateDocumentInput } from '../inputs/update.document.input';
import Document from '../models/document.model';
import DocumentProvider from '../providers/document.provider';

/**
 *
 *
 * @export
 * @class DocumentResolver
 */
@Injectable()
@Resolver((of) => Document)
export default class DocumentResolver {
  constructor(private readonly documentProvider: DocumentProvider) {}

  /**
   *
   *
   * @returns
   * @memberof DocumentResolver
   */
  @Query(() => [Document])
  documents() {
    return this.documentProvider.getAll();
  }

  /**
   *
   *
   * @param {string} id
   * @returns
   * @memberof DocumentResolver
   */
  @Query(() => Document)
  document(@Arg("id") id: string) {
    return this.documentProvider.findDocumentById(id);
  }

  /**
   *
   *
   * @param {CreateDocumentInput} data
   * @returns
   * @memberof DocumentResolver
   */
  @Mutation(() => Document)
  createDocument(@Arg("data") data: CreateDocumentInput) {
    return this.documentProvider.create(data);
  }

  /**
   *
   *
   * @param {string} id
   * @param {UpdateDocumentInput} data
   * @returns
   * @memberof DocumentResolver
   */
  @Mutation(() => Document)
  async updateDocument(
    @Arg("id") id: string,
    @Arg("data") data: UpdateDocumentInput
  ) {
    return this.documentProvider.update(data, id)
  }

  /**
   *
   *
   * @param {string} id
   * @returns
   * @memberof DocumentResolver
   */
  @Mutation(() => Boolean)
  async deleteDocument(@Arg("id") id: string) {
    return this.documentProvider.delete(id)
  }

}
```

**Comment by smolinari** [comment]
Closing once more. My new direction seems to be working now, so this isn't an issue for me anymore.

Scott
