### ISSUE TITLE
OnInit is fired only when a resolver of the declaring module is called for the first time

### ISSUE THREAD

**Issue by johannesfritsch** [Urigo/graphql-modules#1260]
## Bug Report
OnInit is fired only when a resolver of the declaring module is called for the first time. The documentation says it is executed when the application starts. We should either update the documentation or fix the behavior.

## Current behavior
I want to register handlers in a provider at application start. I thought OnInit would be a good idea from the documentation. But the code is ran in some circumstances.

## Input Code
```ts
@Injectable()
class SampleProvider implements OnInit {
  onInit() {
    console.log('yay!'); // <------ This is only called when I resolve me { friends { id } }, but not when I resolve { me { id }}
  }
}

export const SocialNetworkModule = new GraphQLModule({
  typeDefs: gql`
    type User {
      friends: [User]
    }
  `,
  resolvers: {
    User: {
      friends: (user, args) => {
        return user.friends;
      },
    },
  },
  imports: [
    UserModule,
  ],
  providers: [SampleProvider],
});
```

## Expected behavior
I would expect that OnInit is called on app start. Only then I can register handlers etc.

## Environment

<pre><code>
Version: Current npm version as of today.
</code></pre>

**Comment by kamilkisiela** [comment]
We released a new major version (v1.0) of GraphQL Modules. Here's the [migration guide](https://graphql-modules.com/docs/next/recipes/migration).

The new version solves the issue, so I'm closing the thread.

Please try to upgrade. If you can't and still want to use the legacy version, please open a new issue.
