### ISSUE TITLE
context on custom directive only has session

### ISSUE THREAD

**Issue by maapteh** [Urigo/graphql-modules#1269]
I want to know how to have custom directives really working. Because they seem to not have access to the context our modules create along the way (so we set memberId on the context for example).

So my question is how come i have only session (req, res) on the context in a custom directive? Is v1 (with easier context) solving this?

<img src="https://i.imgur.com/Ktd4Zl2.png" width="400px" />

**Comment by kamilkisiela** [comment]
In v1 the context is "generated" at resolver level so it should work just fine with schema directives.
