### ISSUE TITLE
Inherit resolvers from interfaces

### ISSUE THREAD

**Issue by smolinari** [Urigo/graphql-modules#1286]
Hi,

I think [this could be a logic error](https://github.com/Urigo/graphql-modules/blob/5fa95f4ff60b9f925c8500f6aa5c571c6138611d/packages/graphql-modules/src/module/resolvers.ts#L242). 

I'm currently getting this warning during compilation: 

`ResolverInvalidError: Invalid resolver of "nodeInterface" union or interface
Only __resolveType is allowed`

Such resolvers have the return type of the interface so they can be used for multiple objects, but naturally they have other fields too. 

This is the interface type config:

```javascript
export interface GraphQLInterfaceTypeConfig<TSource, TContext> {
  name: string;
  description?: Maybe<string>;
  interfaces?: Thunk<Maybe<Array<GraphQLInterfaceType>>>;
  fields: Thunk<GraphQLFieldConfigMap<TSource, TContext>>;
  /**
   * Optionally provide a custom type resolver function. If one is not provided,
   * the default implementation will call `isTypeOf` on each implementing
   * Object type.
   */
  resolveType?: Maybe<GraphQLTypeResolver<TSource, TContext>>;
  extensions?: Maybe<Readonly<GraphQLInterfaceTypeExtensions>>;
  astNode?: Maybe<InterfaceTypeDefinitionNode>;
  extensionASTNodes?: Maybe<ReadonlyArray<InterfaceTypeExtensionNode>>;
}

```

Where the option is clearly `fields` and not `field`. 

My code was working fine with GraphQL-Modules before 1.0 (but using extraSchema with TypeGraphQL).  I hope I've found something to help improve the library. 

Scott

**Comment by kamilkisiela** [comment]
I don't think `graphql` library supports it, it's `@graphql-tools/schema` and its `makeExecutableSchema` that enables that by copying it from the interface definition (`inheritResolversFromInterfaces` flag - disabled by default).

**Comment by markw351** [comment]
So why not enable inheritResolversFromInterfaces to be passed in the config in createApplication to the schema.makeExecutableSchema call?

We have a large production application I'm looking at migrating to 1.0 but I'm loathe to replicate the same resolver function from a single interface to over a dozen+ types.

**Comment by kamilkisiela** [comment]
In next minor version you'll be able to provide your own schema building logic. I know I could add a flag but be aware that at some point we may move away from `makeExecutableSchema` and then we would end up with a breaking change.

**Comment by kamilkisiela** [comment]
#1512 introduces `Application.schemaBuilder` options.

By default it's:

```javascript
{
  schemaBuilder: makeExecutableSchema
}
```

In case you need `inheritResolversFromInterfaces`:

```javascript
const app = createApplication({
  modules,
  schemaBuilder({typeDefs, resolvers}) {
    return makeExecutableSchema({
      typeDefs, 
      resolvers, 
      inheritResolversFromInterfaces: true
    });
  }
});
```

**Comment by kamilkisiela** [comment]
Available in v1.2.0

https://graphql-modules.com/docs/api#applicationconfig - note `schemaBuilder`

**Comment by markw351** [comment]
@kamilkisiela this is still occurring despite the change, and seems it is not related to the schema creation. The error is being thrown inside addInterfaceOrUnion

`function addInterfaceOrUnion({ typeName, fields, container, config, }) {
    if (container[typeName]) {
        throw new ResolverDuplicatedError(`Duplicated resolver of "${typeName}" union or interface`, useLocation({ dirname: config.dirname, id: config.id }));
    }
    if (Object.keys(fields).length > 1) {
        throw new ResolverInvalidError(`Invalid resolver of "${typeName}" union or interface`, `Only __resolveType is allowed`, useLocation({ dirname: config.dirname, id: config.id }));
    }
    writeResolverMetadata(fields.__resolveType, config);
    container[typeName] = {
        __resolveType: fields.__resolveType,
    };
}`

Which is graphql-module code, not graphql-tools.

**Comment by kamilkisiela** [comment]
#1517 this should do it, forgot that we have internal checks for those things

**Comment by kamilkisiela** [comment]
ok, 1.2.1 is out
