### ISSUE TITLE
v1.0 where is the context?

### ISSUE THREAD

**Issue by onhate** [Urigo/graphql-modules#1288]
I miss the context part in the module where I was able to inject in the context values for each module, was that moved to somewhere else?

**Comment by kamilkisiela** [comment]
Now there's no module-level context, context is global. If you need to store some module-only data you can use Dependency Injection.

**Comment by onhate** [comment]
Actually I'm looking for global context, what I could not find is how to put data into context now, before there was a context method in the module and now it's gone.

**Comment by kamilkisiela** [comment]
Because it's a global context you define it in your GraphQL server.

**Comment by onhate** [comment]
hmm, got it.
What do you suggest for scenario like an auth-module that previously was injecting in the context the jwt decoded? I have 2 implementations of auth and before I was just selecting one or another module and now I need to move that logic to server.

**Comment by kamilkisiela** [comment]
Since it's Auth I would do it on application level, not in auth module or something. It's accessed by the rest of modules anyway

**Comment by onhate** [comment]
thanks for the quick responses @kamilkisiela
