### ISSUE TITLE
v1.0 beta, schemaDirectives are gone?

### ISSUE THREAD

**Issue by maapteh** [Urigo/graphql-modules#1293]
Hi, in pre 1.0 versions we used apollo server with a commonModule and then in every other module we imported this module. The module was created with `schemaDirective` option to include our own directives. And then for server they where added with `SchemaDirectiveVisitor`.

Pre 1.0 beta our common module included:
```
    ...module,
    schemaDirectives: {
        isAuthenticated: IsAuthenticatedDirective,
        deprecated: isDeprecated,
    },
```
So using schemaDirectives is gone in v1 beta, the directive is now only in our playground schema because we added the .graphql schema. But when used its not being called at all.

Im now also looking at the schemaDirectives option we had during startup of our apollo server. 

old situation:
```
    const { schema, schemaDirectives } = application;
    SchemaDirectiveVisitor.visitSchemaDirectives(schema, schemaDirectives);
```

new:
```
    const schema = application.createSchemaForApollo();
```

But so far im not able to have custom directives really working...

`"_directives":["@cacheControl","@complexity","@isAuthenticated","@deprecated","@skip","@include","@specifiedBy"],`

__By the way nice work!__ It seems with middleware i have more fine grained options when to put something on the context, or not. Have to find out why for batched queries context is also generated twice but overal this is a major change for modules. Really cool!

**Comment by maapteh** [comment]
@kamilkisiela how do you use custom directives now in modules?

**Comment by kamilkisiela** [comment]
I guess we could add them but as something that wraps resolve functions, just to avoid the need for GraphQLSchema.

**Comment by fridaystreet** [comment]
definitely a +1 for keeping schema directives. before using directives it was very clunky with resolver composition, especially with a very modulised application. Schema directives are a very nice way of being able to express the intent in the schema so it is easy to see that additional checks and measures are being applied to specific parts of teh schema.

I like the fact the this livrary is evolving, but we have built a lot of code based on the legacy version, it would be nice to see that supported and maintained until core functionality like this is available in v1

**Comment by kamilkisiela** [comment]
#1441 I prepared an example of Schema Directives and new GraphQL modules, as two integration tests. It's possible to use Schema Directives (with the visitor pattern) and thanks to those tests, we won't break it in the future. I know it's not ideal but at least it works in new version. We can always figure out how to make Schema Directives much more developer friendly but not tightly integrated with GraphQL Modules API.

**Comment by kamilkisiela** [comment]
The issues is about "missing schema directives" so that's why I closed it but if you want to have Schema Directives implemented in a much better way than it is right now, please open a new issue with a proposal.
