### ISSUE TITLE
v0.7.17 error unit testing module that imports two mocked modules

### ISSUE THREAD

**Issue by shotor** [Urigo/graphql-modules#1296]
We have an issue where we want to unit test a GraphQL module using the `execute` function from the `graphql` package. We run a query against the schema that the GraphQL module exposes.

https://github.com/shotor/graphql-modules-jest/blob/master/src/mock-query.ts

To do this we import one of our GraphQL modules in our unit tests. These may depend on other GraphQL modules. These dependencies we mock using jest mocks. Then we execute the query.

https://github.com/shotor/graphql-modules-jest/blob/master/src/case-one-import/__mocks__/module-a.ts
https://github.com/shotor/graphql-modules-jest/blob/master/src/case-one-import/module-b.ts
https://github.com/shotor/graphql-modules-jest/blob/master/src/case-one-import/module-b.test.ts

This works fine in the case where we unit test a GraphQL module that depends on 1 other module. But when we try it on a module that depends on two, we get an error that our directives can't be found:

https://github.com/shotor/graphql-modules-jest/blob/master/src/case-two-imports/module-c.ts
https://github.com/shotor/graphql-modules-jest/blob/master/src/case-two-imports/module-c.test.ts

```sh
 FAIL  src/case-two-imports/module-c.test.ts
  ● module-c › cant load ModuleC


          GraphQL-Modules Error: Schema is not valid!
          - #Module #module-c.test.ts_3239397735238033 doesn't have a valid schema!
          -- Unknown directive "@cacheControl".

          Possible solutions:
          - Check syntax errors in typeDefs
          - Make sure you import correct dependencies

       9 |   variableValues,
      10 | }) => {
    > 11 |   const { schema, injector } = graphqlModule;
         |           ^
      12 |
      13 |   inject && inject(InjectFunction(ModuleSessionInfo), injector);
      14 |
```
The full reproduction is available: https://github.com/shotor/graphql-modules-jest

The first two cases pass, but the `case-two-imports` fails. 

Can you please advise how to unit test this use case?

**Comment by kamilkisiela** [comment]
We released a new major version (v1.0) of GraphQL Modules. Here's the [migration guide](https://graphql-modules.com/docs/next/recipes/migration).

The new version solves the issue of mocking other modules, so I'm closing the thread.

Please try to upgrade. If you can't and still want to use the legacy version, please open a new issue.
