### ISSUE TITLE
[v1.0 beta]: Error: There can be only one type named "Query".

### ISSUE THREAD

**Issue by maapteh** [Urigo/graphql-modules#1300]
I started with exporation to the new v1 version. I have two modules both with their own query. Now the createApplication method takes all my modules and creates an executable schema. But the resolvers are not flattened. So it will see Query and Mutation multiple times. While starting i get the error:

There can be only one type named "Query"

code of this library:
```
createApplication(config) {
    const providers = config.providers && typeof config.providers === 'function'
        ? config.providers()
        : config.providers;
    ...
    const schema = makeExecutableSchema({ typeDefs, resolvers });
```

Resolver i give is:
<img width="600" alt="Screenshot 2020-08-28 at 10 15 14" src="https://user-images.githubusercontent.com/25961356/91538374-0cb69280-e918-11ea-8489-12f570fb4093.png">

**Comment by maapteh** [comment]
mergeResolvers fixes it

**Comment by maapteh** [comment]
const resolvers = mergeResolvers(modules.map((mod) => mod.resolvers).filter(Boolean));

fixes it

**Comment by kamilkisiela** [comment]
I think it happens not because of resolvers but you probably have `type Query { }` defined twice instead of one of them being `extend Query { }`

**Comment by maapteh** [comment]
They are re-usable modules. If we all use extend there is not a query, right?

**Comment by kamilkisiela** [comment]
sure but it's not valid with GraphQL spec so if an IDE extension or some other tool wants to collect all definitions and build a schema they will get the same issue you're seeing, duplicated type definition.

**Comment by maapteh** [comment]
ok, will close my pr :)

**Comment by maapteh** [comment]
Maybe it helps others. In our modules pre v1 beta we had added typeDefs like so:

```
const resolversArray = loadFilesSync(`${__dirname}/resolvers`, { extensions: ['ts', 'js']});
const typeDefs = mergeTypeDefs(typeDefsArray);
```

But in the end it turned out, on module perspective we had to simply give mergeTypeDefs an option:

```
const resolversArray = loadFilesSync(`${__dirname}/resolvers`, { extensions: ['ts', 'js']});
const resolvers = mergeResolvers(resolversArray);
const typeDefsArray = loadFilesSync(`${__dirname}/schema/*.graphql`);
const typeDefs = mergeTypeDefs(typeDefsArray, { useSchemaDefinition: false });

export const ProductModule = createModule({
    id: 'product',
    providers: [
        ...
    ],
    resolvers: resolvers,
    typeDefs: typeDefs,
```
