### ISSUE TITLE
v1 - TypeError: context.ɵgetModuleContext is not a function

### ISSUE THREAD

**Issue by zicodeng** [Urigo/graphql-modules#1312]
First of all, thanks for your effort on v1 🚀

I am migrating from v0 to v1 and encountered this error. Can someone from the team help me?

```
TypeError: context.ɵgetModuleContext is not a function
at NonNullInputDirective.wrappedResolver (/app/node_modules/graphql-modules/index.cjs.js:1306:30)
at field.resolve (webpack:///./src/gql/schema-directives.ts?:50:22)
at /app/node_modules/graphql-middleware/dist/applicator.js:7:114
at middleware (/app/node_modules/graphql-shield/dist/generator.js:30:30)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

The server actually started running fine but when I made any requests, it failed with the above error. It seems doesn't work with graphql-shield 🤔

**Comment by zicodeng** [comment]
The issue was caused by the way how I initialized the app...

**Comment by zicodeng** [comment]
Re-open this because this way of creating schema should be allowed, but currently doesn't work with graphql-modules. It will cause `context.ɵgetModuleContext is not a function` error

```
// Create GraphQLModule app and get type defs and resolvers
const { typeDefs, resolvers } = createApplication({
  modules,
});

const schema = makeExecutableSchema({
  typeDefs,
  resolvers,
  schemaDirectives: {
    nonNullInput: NonNullInputDirective,
  },
});

// Create schema and apply middleware
const schemaWithMiddleware = applyMiddleware(schema, permissions);
```

**Comment by ardatan** [comment]
@zicodeng You can extract typeDefs and resolvers from the schema by using `graphql-tools` and pure graphql-js
https://www.graphql-tools.com/docs/api/modules/utils#getresolversfromschema
```ts
import { printSchemaWithDirectives, getResolversFromSchema } from '@graphql-tools/utils';
import { parse } from 'graphql';
const typeDefs = parse(printSchemaWithDirectives(schema));
const resolvers = getResolversFromSchema(schema);
```
But if you only need to apply schema directive visitors, you can run `visitSchemaDirectives` on the generated schema without extracting typeDefs and resolvers.

**Comment by zicodeng** [comment]
@ardatan Thanks for your reply! My goal is to get custom schema directives working. I just tried the approach you mentioned and refactored my server bootstrap code like this below:

```
const gqlApp = createApplication({
  modules,
});
const schema = gqlApp.createSchemaForApollo();

SchemaDirectiveVisitor.visitSchemaDirectives(schema, {
  nonNullInput: NonNullInputDirective,
});
```

Unfortunately, schema directives are only called on server start, but not in subsequent requests :( This seems to be related to v1 release only. Similar issue: https://github.com/Urigo/graphql-modules/issues/1293

**Comment by zicodeng** [comment]
Even with this, I wasn't able to get custom directives working 😞

```
const gqlModApp = createApplication({
  modules,
});
const gqlModSchema = gqlModApp.createSchemaForApollo();
const typeDefs = parse(printSchemaWithDirectives(gqlModSchema));
const resolvers = getResolversFromSchema(gqlModSchema);

const schema = makeExecutableSchema({
  typeDefs,
  resolvers,
  schemaDirectives: {
    nonNullInput: NonNullInputDirective,
  },
});

const schemaWithMiddleware = applyMiddleware(schema, permissions);

const apollo = new ApolloServer({
  schema: schemaWithMiddleware,
  ...
}
```
