### ISSUE TITLE
v0.7.14 How to deal with Session scope inside Application scope

### ISSUE THREAD

**Issue by waldemarnt** [Urigo/graphql-modules#1317]
I've been using graphql-modules in a quite big codebase with many different people making changes to it. I want to understand how I could prevent people from accidentally adding `Session` scoped modules as a dependency of an `Application` module, given `Application` is a singleton it will hold the same instance of the `Session` module.
This behaviour has already led us to memory leaks. Is there a way to prevent it from happening? What do you guys suggest?

**Comment by waldemarnt** [comment]
Is the project abandoned?

**Comment by kamilkisiela** [comment]
You can try the new version of GraphQL Modules (still in beta but soon to be stable) in which we we have `Singleton` and `Operation` scoped providers. There should be no memory leaks since the operation-scoped Injector is attached to graphql-js `execute` function, it's no longer dependent on an incoming request object.

**Comment by waldemarnt** [comment]
@kamilkisiela thanks for the reply, I'll test the new version

**Comment by kamilkisiela** [comment]
We released a new major version (v1.0) of GraphQL Modules. Here's the [migration guide](https://graphql-modules.com/docs/next/recipes/migration).

There's a section ["Using both Singleton and Operation scopes"](https://graphql-modules.com/docs/next/di/scopes#using-both) in ["DI Scopes"](https://graphql-modules.com/docs/next/di/scopes) chapter of docs.

The new version solves the issue, so I'm closing the thread.

Please try to upgrade. If you can't and still want to use the legacy version, please open a new issue.
