### ISSUE TITLE
[Feat] Fastify implementation for V1

### ISSUE THREAD

**Issue by artecoop** [Urigo/graphql-modules#1366]
Hello!

is it possible to have an example of how to implement graphql-modules v1 with Fastify?
It seems possible to use 

```TS
const schema = application.createSchemaForApollo();
fastify.register(GQL, {
    path: '/',
    schema
});
```

But I dont remember in which issue in this repo I read, using this implementation is slower than the suggested
```TS
const execute = application.createExecution();
const schema = application.schema;
```

But Fastify does not expose `customExecuteFn` as express does.

Thanks

**Comment by ardatan** [comment]
Other than `createSchemaForApollo`, I don't think it is possible to use `application.schema` with `createExecution`. So you can create an issue on `fastify-gql` to support to provide custom execution function.

**Comment by artecoop** [comment]
@ardatan, precious as ever.

I'll try on that repo.

**Comment by dotansimha** [comment]
@artecoop I opened this recently: https://github.com/mcollina/fastify-gql/issues/278
