### ISSUE TITLE
[V1] Access Raw Headers in providers

### ISSUE THREAD

**Issue by artecoop** [Urigo/graphql-modules#1370]
Hey!

is it possible to access raw headers from underlining http server? (I'm using Fastify right now)
I tried using the ExecutionContext like
```ts
import { ExecutionContext, Injectable } from 'graphql-modules';

@Injectable()
export class FooProvider {
    @ExecutionContext()
    private context: ExecutionContext;

    public foo(): void {
        const bar = this.context.reply.raw.header;
    }
}
```

But type definition for ExecutionContext provides only the injector property and not reply.

My method seems hacky and not future proof

**Comment by kamilkisiela** [comment]
I think it was fixed in recent commits. Here's an integration test that covers it https://github.com/Urigo/graphql-modules/blob/master/packages/graphql-modules/tests/execution-context.spec.ts#L328

**Comment by kamilkisiela** [comment]
Related issue https://github.com/Urigo/graphql-modules/issues/1294
