### ISSUE TITLE
[V1] Provider required in all modules

### ISSUE THREAD

**Issue by artecoop** [Urigo/graphql-modules#1385]
Let's have this modules in an app

- Author
- Book

In order to share some code, I create a `AuthorProvider` and a `BookProvider`, each one with their logic inside. Resolvers respectively reference their provider counterpart.
`BookProvider` imports `AuthorProvider` to have have authors logic inside the book (e.g. name resolutions from IDs).

Now I create a singleton class `FooSingleton`  and import it inside my Book module, referencing it as provider, as per documentation.

The compilers complain with
```Error: No provider for FooSingleton! (undefined -> FooSingleton)```

To fix this, I have to add `FooSingleton` to Author's module providers too. It is useless here

**Comment by dotansimha** [comment]
Hi! Can you please try the latest alpha? it's `graphql-modules@1.0.0-alpha-9f800b1.0`.

Also, we introduced a new (still undocumented) feature for sharing providers, you can do something like that: 

```
@Injectable({
   scope: Scope.Singleton,
   global: true,
})
class MyProvider {}
```

**Comment by artecoop** [comment]
Hey @dotansimha,

I tried the latest alpha. 
Just to be sure, I want to share with you the steps I made with this new release
- Removed all references of singleton's provider from each module previously importing them
- Referenced them in provider's section of `createApplication()`  

The code compiles and run, but I'm not sure if this is the way to go.

On a side note, I find that referencing singletons as provider is a bit confusing. But this is a very personal experience, so do not take it as a criticism.

**Comment by artecoop** [comment]
Wait, there is a problem.

In singletons with 
```
@Injectable({
   scope: Scope.Singleton,
   global: true,
})
```

ExecutionContext is undefined now

**Comment by dotansimha** [comment]
@kamilkisiela  will give it a look next week :)

**Comment by kamilkisiela** [comment]
@artecoop I tried to reproduce this empty ExecutionContext:

```typescript
  @Injectable({
    scope: Scope.Singleton,
    global: true,
  })
  class Posts {
    @ExecutionContext()
    context!: ExecutionContext;

    all() {
      console.log(this.context);

      return [];
    }
  }
```

Both on application and module levels:

https://github.com/Urigo/graphql-modules/blob/f72548a2372faa73e775010fd8663cff919ae353/packages/graphql-modules/tests/execution-context.spec.ts#L328

It seems to work. Could you provide a reproduction?

**Comment by artecoop** [comment]
I can't reproduce even myself right now. But I've left a watch on the `context` when null to trigger my attention. When it's replicating this behavior, I'll make a reproducible codesandbox.

Thanks Kamil.
