### ISSUE TITLE
[V1] Allow to force-init `Singleton` providers?

### ISSUE THREAD

**Issue by dotansimha** [Urigo/graphql-modules#1432]
@kamilkisiela I think we need a way to specify a auto/force-init of Providers, using `@Injectable` decorator.
This goal is to be able to init provider when the injector is created, in order to have those available later. Also, for use-cases like webhook / routes creation.

**Comment by kamilkisiela** [comment]
It was like that before introducing `global: true`, because you can't instantiate providers across different Injectors randomly. We would need to track all singleton injectors, their providers and also their dependencies and instantiate providers within each Injector in proper order.

**Comment by dotansimha** [comment]
I guess we can just call `injector.get(TheProvider)` and it will make sure to init everything, no?

**Comment by kamilkisiela** [comment]
No because we have multiple injectors that depends on each other. We need to instantiate Injector (actually its providers) in proper order so that an Injector that creates a global Provider is created before other Provider that uses a global Injector.

**Comment by kamilkisiela** [comment]
Or maybe it could work, but module injectors should be instantiated few lines later when we actually collect and create modules.

**Comment by dotansimha** [comment]
I even think we can just use the root injector after initalizing everything, and just ask for that module. It won't cover `async` init flow, but maybe this could be done later

**Comment by kamilkisiela** [comment]
Root injector has no access to module injectors

**Comment by dotansimha** [comment]
@kamilkisiela when I do `app.injector.get` - which one does it use? I meant this one :)
