### ISSUE TITLE
Cannot extends Query/ Mutation more than 1 time in same module

### ISSUE THREAD

**Issue by mdilshan** [Urigo/graphql-modules#1459]
I have a project created with Apollo Server & graphql-Modules. I have declared all my types in several Graphql files and at the end I concat all together and provide one string to the graphql TypeDef.

For make debugging easy, I put all the sub graphql files into one file, and here's the last part of that file.

```
 const q = gql`
  ...

  extend type Mutation {
    createStudent(input: UserAccountIn): AuthUser
    loginStudent(input: UserLogIn): AuthUser
    loginAdmin(input: UserLogIn): AuthUser
  }
  type Subject {
    _id: String
    name: String
    grade: String
    subject_straem: String
    subject_code: String
    status: String
    avatar_url: String
    created_at: Int
    updated_at: Int
    deleted_at: Int
  }
  input SubjectIn {
    name: String
    grade: String
    subject_straem: String
    subject_code: String
    status: String
  }

  extend type Mutation {
    createSubject(input: SubjectIn): Subject
      @hasRole(roles: [SUPER_ADMIN, ADMIN])
  }
`;
```

When I compile the project with the above file I get the below error,

```
throw new ExtraResolverError(`Resolver of "${id}" type cannot be implemented`, `${id} is not defined`, useLocation({ dirname: metadata.dirname, id: metadata.id }));
            ^
[ExtraResolverError: Resolver of ""Mutation.createStudent"" type cannot be implemented
"Mutation.createStudent" is not defined
```

But if I remove the last extend Type Mutation from the definition OR If I put the createSubject into the previous extend type Mutation and remove the last extend type Mutation it start to work

And the weird thing is, eventhough I'm dealing with Mutation.createSubject the error message is regarding Mutation.createStudent

I also tried to add 2nd extend type Query just above the last extend type Mutation & surprisingly this time error refer to my 1st extend type Query.

So what I can assume is I can't extend Query or Mutation for more than 1 time but in a example project I can see there are many "extend" types in there.

I use only one module. The reason why I use this module is to use the DI features of this module. 

```
"apollo-server": "^2.19.0",
"graphql": "^15.4.0",
"graphql-modules": "^1.0.0-alpha-adf0de4.0",
"reflect-metadata": "^0.1.13",
```

Thanks in advance.

**Comment by dotansimha** [comment]
Thanks! Managed to reproduce and fix here: https://github.com/Urigo/graphql-modules/pull/1461

**Comment by mdilshan** [comment]
Awesome
