### ISSUE TITLE
GraphQL Code Generator integration

### ISSUE THREAD

**Issue by kaminskypavel** [Urigo/graphql-modules#1465]
Hey teams, thanks for this project, I'm working on a lerna mono-repo (express + react)
and was wondering what would be the easiest way to successfully integrating the two?

```json
    "@graphql-codegen/cli": "1.19.4",
    "graphql-modules": "^1.0.0",
```

**Comment by kamilkisiela** [comment]
https://graphql-code-generator.com/docs/presets/graphql-modules :)

**Comment by kaminskypavel** [comment]
oh, missed that. thanks!
