### ISSUE TITLE
Testing graphql-modules v1

### ISSUE THREAD

**Issue by rosengrenen** [Urigo/graphql-modules#1473]
Hi, is it possible to write tests on the modules like in the legacy version? Can't seem to find it anywhere in the docs. I tried creating a testModule from my module and overriding (I think) a provider, but when trying to execute using the `execute` function from graphql I got errors about graphql types missing (that are defined in other modules).

**Comment by kamilkisiela** [comment]
Unfortunately, it's in progress :) For now, you can use a module in an application and provide missing types manually or create a script that turns type extensions into definitions.

**Comment by kamilkisiela** [comment]
`v1.1.0` + [docs](https://graphql-modules.com/docs/next/essentials/testing/)
