### ISSUE TITLE
How to create a federation apollo federation in v1?

### ISSUE THREAD

**Issue by anlauren** [Urigo/graphql-modules#1522]
We do have the function `createSchemaForApollo` but the signature doesn't match the federation `buildFederatedSchema`, so i've used directly the typedefs and resolvers, as below:
```typescript
  const application = createApplication({
    modules: [myModule].map(
      getModuleConfigurationMapper(providers)
    ),
  });
  const { typeDefs, resolvers } = application;
  const server = new ApolloServer({
    schema: buildFederatedSchema(
      typeDefs.map((td, index) => ({
        typeDefs: td,
        resolvers: resolvers ? resolvers[index] : [],
      }))
    ),
```

but it seems that we are missing the context there, because i get that error at runtime:
```
TypeError: context.ɵgetModuleContext is not a function
```

any way to set it up? 🤔  i've read the pre-v1 examples but it doesn't seem to apply anymore

**Comment by Albert-Lo** [comment]
I just started building my applications with v1.2.
It seems that using schemaBuilder property in createApplication is the correct way?
But I can't get it working either. It is not calling the resolver and always returning null for `me()` in the example below:
```
const { ApolloServer, gql } = require('apollo-server');
const { buildFederatedSchema } = require('@apollo/federation');
const { createApplication, createModule } = require('graphql-modules');

const typeDefs = gql`
  type Query {
    me: User!
  }

  type User {
    id: ID!
    username: String
  }
`;

const resolvers = {
  Query: {
    me() {
      return { id: "1", username: "@ava" }
    }
  },
  User: {
    __resolveReference(user, { fetchUserById }){
      return fetchUserById(user.id)
    }
  }
}

const userModule = createModule({
  id: 'user-module',
  dirname: __dirname,
  typeDefs,
  resolvers,
});

const app = createApplication({
  modules: [userModule],
  schemaBuilder: buildFederatedSchema,
});

const schema = app.createSchemaForApollo();

const server = new ApolloServer({
  schema,
});

server.listen(4001).then(({ url }) => {
    console.log(`🚀 Server ready at ${url}`);
});
```

And if I uncomment __resolveReference resolver, it will throw this error:
```
ExtraResolverError: Resolver of ""User.__resolveReference"" type cannot be implemented
"User.__resolveReference" is not defined
```

**Comment by Albert-Lo** [comment]
I ended up doing
```
schemaBuilder: (input: {
    typeDefs: DocumentNode[];
    resolvers: Record<string, any>[];
  }) => buildFederatedSchema({
    typeDefs: input.typeDefs,
    resolvers: Object.assign({}, ...input.resolvers),
  }),
  ```
  and it finally works for me, not sure if this is intended tho

**Comment by Albert-Lo** [comment]
I have a PR for that making __resolveReference works

**Comment by anlauren** [comment]
That is awesome news!
Do you know how it will be integrated to a next version? are we talking days/weeks/month? 
Only asking because i am starting a new project where federation is a must and graphql-modules with godegen seems to be the more "typesafe" solution out there

**Comment by Albert-Lo** [comment]
I think they are reviewing it, but I'm not sure what the release plan looks like.

**Comment by Albert-Lo** [comment]
And I actually have to do
```
import { mergeTypeDefs } from 'graphql-tools';
import _ from 'lodash';
...
schemaBuilder: (input: {
    typeDefs: DocumentNode[];
    resolvers: Record<string, any>[];
  }) => buildFederatedSchema({
    typeDefs: [mergeTypeDefs(input.typeDefs)],
    resolvers: _.merge({}, ...input.resolvers),
  }),
  ...
 ```
 To make it fully working when I have more queries and mutations. Not sure if they want to make this friendlier, or maybe I'm just doing something wrong.

**Comment by kkckkc** [comment]
I have a similar issue, but with `__resolveObject`, i.e. I get

```
ExtraResolverError: Resolver of ""User.__resolveObject"" type cannot be implemented
"User.__resolveObject" is not defined
```

**Comment by kkckkc** [comment]
> @kkckkc Isn't `__resolveObject` deprecated in favor of `__resolveReference`

I'm not aware of this, but it might very well be the case. Anyhow, `__resolveObject` is *very* useful for us compared to `__resolveReference` - as I can resolve a partial object, and then use the `fields` parameter to determine if the partial object is sufficient, or if I need to fetch the full object from the source.

**Comment by kamilkisiela** [comment]
[`v1.4.0`](https://github.com/Urigo/graphql-modules/releases/tag/graphql-modules%401.4.0) supports `__resolveReference` and `__resolveObject`
