### ISSUE TITLE
How to use DelegateToSchema?

### ISSUE THREAD

**Issue by jyotman** [Urigo/graphql-modules#1536]
I'm wondering what's the best way to use 1 resolver within another resolver without duplicating code.

We wanna use the delegateToSchema from graphql-tools library but it seems the schema returned by application.createSchemaForApollo() is not compatible with it probably. I think delegateToSchema expect `executable` graphQL Schema instead of graphql Schema.

Example requirement - 
Order Module -
```
extend type Query {
    order(id: ID!): Order!
}

type Order {
    id: ID!
    owner: User!
}

// Resolvers  -
const resolvers = {
  Query: {
    order(parent, args, context, info): Promise<Order> {
        return orderStore.getOrderById(args.id) // this order object contains userId which is used in child resolver below
    }
  },
  Order: {
    // instead of rewriting the resolver code here we delegate this to user module
    owner(parent: OrderModel, args, context, info): Promise<User> { 
      return delegateToSchema({
        schema: entireSchema, // We're using executable schema created by graphql-tools here instead of application.createSchemaForApollo()
        operation: 'query',
        fieldName: 'user',
        args: {
          id: parent.userId,
        },
        context,
        info,
      })
    },
  }
```

User Module -
```
type Query {
    getUserById(id: ID!): User!
}

// Resolvers  -
const resolvers = {
  Query: {
    user(parent, args, context, info): Promise<Order> {
        return userStore.getUserById(args.id) // The id is assigned in args from the order deletegateToSchema
    }
  },
}
```

The problem we're facing is that the `user` resolver is being called twice. Only once from the `owner` resolver but it's called once again after that, I don't know the source but that execution leads to wrong result as `args` is empty.

**Comment by ardatan** [comment]
You can use providers with DI. So you can **keep your logic inside providers then call those providers in the resolvers** instead of having two execution logic.
