### ISSUE TITLE
[V1] Can't get instance out of DI when Scope.Operation

### ISSUE THREAD

**Issue by fenos** [Urigo/graphql-modules#1541]
Hi Folks!

I find it very strange that I'm unable to simply do `inject.get(MyClass)`  outside of a resolver, when my class is defined with a `Scope.Operation`

I currently want to write a script that uses few classes which are defined with the `Scope.Operation` and i'm getting the ugly error message:

```
Error: No provider for AuthService! - in App (Singleton Scope)
```

There is a ton of benefit allowing to return the constructed instance for both the scopes. 
As with the previous version when getting a class that was defined as `Scope.Operation` i would get a new instance all the time.

From the documentation:

> To improve the performance a bit, GraphQL Modules instantiate services on demand. When Data is not called anywhere directly or indirectly by resolvers, the service is not created.

If we want to keep this optimization we can at least have a flag that would allow the instance to be resolved.

Any thoughts?

**Comment by fenos** [comment]
We should be able to at least do something similar to this:

```ts
injector.withContext({}).get(OperatonInstance);
```

otherwise the DI is incomplete at this stage.

**Comment by kamilkisiela** [comment]
RFC #1568

**Comment by kamilkisiela** [comment]
[`v1.4.0`](https://github.com/Urigo/graphql-modules/releases/tag/graphql-modules%401.4.0)
