### ISSUE TITLE
[v1] Inject within module doesn't work

### ISSUE THREAD

**Issue by kkckkc** [Urigo/graphql-modules#1562]
I'm using the following code 

```
import 'reflect-metadata';
import gql from 'graphql-tag';
import { InjectionToken, Injectable, Inject, CONTEXT, MODULE_ID, Scope } from 'graphql-modules';

@Injectable()
export class Test2 {
  constructor() {
    console.log('*** INSTANTIATE Test2');
    console.log('--------------------------');
  }
}

@Injectable()
export class Test {
  constructor(@Inject(Test2) tst) {
    console.log('*** INSTANTIATE Test');
    console.log(tst);
    console.log('--------------------------');
  }
}

export const module = {
  id: __filename,
  dirname: __dirname,
  typeDefs: gql`
    type Query {
      q: MyType
    }

    type MyType {
      id: ID
    }
  `,
  providers: () => [
    Test2,
    Test
  ]
}
```

with the output being 

```
*** INSTANTIATE Test2
--------------------------
*** INSTANTIATE Test
undefined
--------------------------
```

After trying to debug this for some time, I think the issue is that somehow, due to my transpilation settings, the `Inject` annotation is read before the `Injectable` annotation. This means that the line 29-42 in https://github.com/Urigo/graphql-modules/blob/master/packages/graphql-modules/src/di/decorators.ts removes any data already set by the `Inject` annotation. 

If I add 

```
if (!(target as any)[INJECTABLE]) (target as any)[INJECTABLE] = meta
``` 

on line 45 it all works as expected. However, this effectively removes the logic on line 28-42 - so I don't think this is the correct solution

**Comment by kamilkisiela** [comment]
@kkckkc I can't reproduce the error, it works fine in https://github.com/Urigo/graphql-modules/pull/1569. Could you create a test here, that fails?

Try to use [`forwardRef`](https://graphql-modules.com/docs/di/providers#lazy-with-forwardref), maybe Test1 is undefined when Test2 is created

**Comment by kkckkc** [comment]
`forwardRef` doesn't make a difference since the constructor parameter annotation metadata is essentially deleted. 

I'm not surprised that your test case cannot reproduce the issue, as I believe the issue is somehow related to specific transpilation settings (we use a combination of Typescript and Babel) 
 
I will try to recreate the issue in a separate repo, but I'm not sure how easy it will be (since we have a large complicated codebase). Worst case, I can extract the transpiled code as an illustration of the issue

**Comment by kkckkc** [comment]
I've created a small repo that reproduces the issue. You can find it at https://github.com/kkckkc/1562_example

Apologies for the somewhat complicated setup, but it's the smallest possible replica of our setup that I could provide. 

BTW, the issue is indeed in the transpiled code. The relevant section looks like

```
let Test = (_dec2 = (0, _graphqlModules.Injectable)(), _dec2(_class2 = (_temp2 = (_temp = class Test {
  constructor(tst) {
    console.log('*** INSTANTIATE Test');
    console.log(tst);
    console.log('--------------------------');
  }

}, _temp), _temp = (0, _graphqlModules.Inject)(Test2)(_temp, undefined, 0) || _temp, _temp2)) || _class2);
```

It's somewhat hard to see, but the last line invokes the `Inject` annotation. This call is a parameter to the `Injectable` annotation - hence, the annotation are "executed" in a different order than they appear in the original source code

**Comment by kkckkc** [comment]
I've added this test-case https://github.com/kkckkc/graphql-modules/commit/8d4345fd244bfaa7107f36118399a0a467d08733 that illustrates the issue (it's a manual recreation of the transpiled code - so not 100% sure it is accurate)

**Comment by kkckkc** [comment]
and this https://github.com/kkckkc/graphql-modules/commit/914fe6e0e1546caef4bcc582e1ff3e98e30d86aa seems to fix the test case

**Comment by kamilkisiela** [comment]
[`v1.4.1`](https://github.com/Urigo/graphql-modules/releases/tag/graphql-modules%401.4.1)
