### ISSUE TITLE
GraphQL dataloader with Firebase Firestore

### ISSUE THREAD

**Issue by artecoop** [Urigo/graphql-modules#1604]
I've already posted this on stackoverflow with no luck. I'm hoping here to solve the problem, if it is related to graphql-modules.

I'm using for this project Firebase Firestore, and I'm trying to implement dataloaders to reduce request to the server. 

In this particular case, I have a Category collection structured like this:
(I'll use typescript to better define my code)

```typescript
type Category = {
    name: String
    parent?: Category
}
```

when I query the graphql endpoint, in resolvers I verify if the category has a parent, and if one is present, I query the database for details. Here's come the dataloader.

This is my Dataloader implementation for Firestore:
```typescript
 private dataLoader = new DataLoader(async (ids: readonly string[]) => {
    // firestore limits batches to 10
    let batches: Category[] = [];
    const tmp = [...ids];
    while (tmp.length) {
        const batch = tmp.splice(0, 10);
        const result = await this.collection.where(FieldPath.documentId(), 'in', [...batch]).get();
        batches = [...batches, ...result.docs.map(d => ({ id: d.id, ...d.data() } as Category))];
    }

    return batches;
});
```

the resolver itself calls this method
```typescript
public async getById(id: string): Promise<Category> {
    const foo = await this.dataLoader.load(id);
    console.log('required', id, 'received', foo.id);
    return foo;
}
```
but as you can see in this sample output, it messes up big time: 
```
required ztdOcVv9JdNp6U54ySed received 4jXbScd1qTwPStXocaoc
required Qnb86GsOy0gSgGxmMqYR received NeuCCRrJyurQTxvlAVhs
required NeuCCRrJyurQTxvlAVhs received Qnb86GsOy0gSgGxmMqYR
required 4jXbScd1qTwPStXocaoc received ztdOcVv9JdNp6U54ySed
```

My understanding is that somewhere async cause some trouble, but no idea where or how to solve this. That's why I'm here asking for help.

Thanks in advance

**Comment by kamilkisiela** [comment]
It's not related to GraphQL Modules but if I were you I would check the following thing:

```typescript
new DataLoader<string>(async ids => {
    const results = await whateverDataFetchingLogicYouHave(ids);
    
    return results; // <- check if `ids[i]` matches `results[i]`
});
```

It's important to return a matching value for every key in `ids` array, they should have the same index, the same order and so on. Basically you have to match `ids[i]` with `results[i]` even if it's nullable.

**Comment by artecoop** [comment]
@kamilkisiela thanks for your suggestion!
