### ISSUE TITLE
Improve Testing section in the documentation

### ISSUE THREAD

**Issue by chanlito** [Urigo/graphql-modules#163]
The title says it all.

**Comment by agustif** [comment]
As I am trying to understand further graphql-modules and it's ecosystem, I would love to tackle this.

Whare are you missing specifically, a test coverage of the packages itself, or tests in the example repos?

I would love any direction/feedback on how to tackle this, I do see there's virtually no test suite for the package itself, is there something where help or PR might be nice? maybe along some extra docs about it?

Good night!

**Comment by Urigo** [comment]
We have a testing section here: https://graphql-modules.com/docs/introduction/test-your-module

If you want to add things, open a new issue
