### ISSUE TITLE
testkit option for replaceExtensions

### ISSUE THREAD

**Issue by maapteh** [Urigo/graphql-modules#1634]
Hi team, for the options 'replaceExtensions' which works perfect im looking for an option which only replaces the extension on Query/Mutation/Subscriptions since our modules are set up to always extend. Now in testing the option doesnt allow to extend other modules type (which is fine). Im looking for an option to flatten only the above mentioned. Now i have to hack my way around, see the sandbox which uses your test structure to show my wish.

https://codesandbox.io/s/github/maapteh/sandbox-feature-request?file=/test.ts

**Comment by kamilkisiela** [comment]
@maapteh https://github.com/Urigo/graphql-modules/pull/1645 :)

**Comment by kamilkisiela** [comment]
@maapteh could you try `graphql-modules@1.4.3-alpha-28e4400.0`?

**Comment by maapteh** [comment]
Will try tomorrow!

**Comment by maapteh** [comment]
I posted in that PR that it works :)
