### ISSUE TITLE
Error: Invalid AST Node

### ISSUE THREAD

**Issue by nemonemi** [Urigo/graphql-modules#1636]
**Describe the bug**

While testing the library I've encountered a bug at the basic example.

**To Reproduce**
1. clone the repo https://github.com/nemanjamilosavljevic-newtron/graphql_ensemble/tree/graphql-modules at the branch graphql-modules
2. install dependencies of the /backend_services/books and run it
3. observe the error
```ts
[ERROR] 22:08:08 Error: Invalid AST Node: "type Query {\n      hello: String!\n    }".
```

In the /backend_services/books/src/test.ts there is a basic setup from the documentation which isn't working.
```ts
const { createModule, createApplication } = require('graphql-modules');

export const Books = createModule({
  id: 'my-module',
  dirname: __dirname,
  typeDefs: [
    `type Query {
      hello: String!
    }`,
  ],
  resolvers: {
    Query: {
      hello: () => 'world',
    },
  },
});

export const application = createApplication({
  modules: [Books],
});
```

**Expected behavior**
The default example should run without problems.

**Environment:**

- OS: Windows 10
- `@graphql-modules/...`: 1.4.2
- NodeJS: 14.16.0

**Additional context**

**Comment by kamilkisiela** [comment]
@nemonemi Hi there :) GraphQL Modules accepts `DocumentNode` (parsed string) https://github.com/Urigo/graphql-modules/blob/b66b364bd34cf51732ab7016ff6f832241147267/packages/graphql-modules/src/module/types.ts#L9

You can do:

```diff
-const { createModule, createApplication } = require('graphql-modules');
+const { createModule, createApplication, gql } = require('graphql-modules');

export const Books = createModule({
  id: 'my-module',
  dirname: __dirname,
  typeDefs: [
-    `type Query {
+    gql`type Query {
      hello: String!
    }`,
  ],
  resolvers: {
    Query: {
      hello: () => 'world',
    },
  },
});

export const application = createApplication({
  modules: [Books],
});
```

**Comment by kamilkisiela** [comment]
https://github.com/Urigo/graphql-modules/pull/1643

this should help to prevent those issues

**Comment by nemonemi** [comment]
It would be nice if the documentation is then updated as well.
I've created a pull request with that adjustment.
