### ISSUE TITLE
Readme.md file contains broken lins which should lead towards the documentation

### ISSUE THREAD

**Issue by nemonemi** [Urigo/graphql-modules#1647]
This is a documentation change.

Links in the readme file do not lead to where they are meant to lead.
For example, this is one such link https://graphql-modules.com/docs/index
![image](https://user-images.githubusercontent.com/77624664/114423705-ba309a80-9bb7-11eb-9f2b-a1212bf459a6.png)

Places in the Readme file with broken links.
* [Website](https://graphql-modules.com/)
* [Documentation](https://graphql-modules.com/docs/index)
* Documentation is available at [graphql-modules.com](https://graphql-modules.com/docs/index).
* More advanced usage at [graphql-modules.com](https://graphql-modules.com/docs/next/index)

Either add `www.` to each url, or better yet better handle the incoming urls.

**Comment by kamilkisiela** [comment]
Yeah, we monitor our sites and the DNS fix is in progress

**Comment by nemonemi** [comment]
Nice, I see that most of the links work correctly now, except one:
More advanced usage at [graphql-modules.com](https://www.graphql-modules.com/docs/next/index).

![image](https://user-images.githubusercontent.com/77624664/116280596-218a4500-a789-11eb-8f72-b1c18819939a.png)

**Comment by ardatan** [comment]
Seems fine now!
