### ISSUE TITLE
[legacy] security upgrade needed on graphql-modules/core

### ISSUE THREAD

**Issue by Akarshit** [Urigo/graphql-modules#1717]
**Describe the bug**
Since the legacy version is still widely used, we should be providing security updates to it. Right now while using account-js which uses `graphql-modules/core`, I get the following vulnerability:
<img width="1309" alt="Screen_Shot_2021-06-08_at_10 27 08_AM" src="https://user-images.githubusercontent.com/7762605/121224587-f7c34400-c845-11eb-938f-d30497fff25b.png">

**Expected behavior**

Since it's not very straightforward to upgrade to v1 of graphql-modules, we should do a patch release that fixes this vulnerability.

**Comment by ardatan** [comment]
You can use yarn resolutions to force the latest version of lodash.
https://classic.yarnpkg.com/en/docs/selective-version-resolutions/#:~:text=Yarn%20supports%20selective%20version%20resolutions,manual%20edits%20in%20the%20yarn.

**Comment by ardatan** [comment]
See https://overreacted.io/npm-audit-broken-by-design/
