### ISSUE TITLE
A better implementation for schema directives?

### ISSUE THREAD

**Issue by darkbasic** [Urigo/graphql-modules#1726]
Is there any reason why `schemaDirectives` has been deprecated in graphql-modules v1?
I've read here (https://github.com/Urigo/graphql-modules/issues/1293) that the supported way is now through the visitor pattern, but the older approach was far more developer-friendly and I was reasoning about the reasons behind its deprecation.
In accounts-js with v0 you didn't have to export neither the context nor the schemaDirectives, with v1 you have to manually provide both. I understand you want to keep the context global and not per-module like in v0, but what's the problem with `schemaDirectives`?

**Comment by ardatan** [comment]
Old Schema Directives with `SchemaDirectiveVisitor` has been deprecated in GraphQL Tools v8. Now we have a different approach for directives;
https://www.graphql-tools.com/docs/schema-directives

**Comment by shellscape** [comment]
> but what's the problem with schemaDirectives?

This is the question that hasn't been answered anywhere. And the documentation doesn't cover that. The deprecated `schemaDirectives` property doesn't even exist in the documentation, or at least it doesn't show in any search results. (FWIW this is the same kind of gripe that folks have had with the guild's documentation for a while now)

While I'm not a fan of the new method of creating directives and applying them to schemas, I'd love to at least see some thorough documentation on it.

**Comment by ardatan** [comment]
`schemaDirectives` or any kind of schema transformation done with directives is not GraphQL Modules v1's feature so we don't have it in the documentation.

> While I'm not a fan of the new method of creating directives and applying them to schemas, I'd love to at least see some thorough documentation on it.

You're free to choose any version of graphql-tools or GraphQL Modules you like and you can also fork and maintain an older version of those since they are all open source and available in this repo and NPM.

**Comment by shellscape** [comment]
> You're free to choose any version of graphql-tools or GraphQL Modules you like and you can also fork and maintain an older version of those since they are all open source and available in this repo and NPM.

I think you missed the point there. We're not griping about things changing. We're griping about the documentation not keeping up with things changing. If uncomfortable changes are explained, they become less uncomfortable. In this case, there's no migration guide, no documentation on the deprecation of `schemaDirectives`, and nothing searchable in the graphql-tools website. That's a problem, and with the knowledge, nuance, and context required to write those docs, it unfortunately falls on the maintainers to help bring the community along for the ride.

**Comment by Urigo** [comment]
Thank you @shellscape and I agree with your comment.
Would you be able to help us set up this kind of guide?

**Comment by shellscape** [comment]
> That's a problem, and with the knowledge, nuance, and context required to write those docs, it unfortunately falls on the maintainers to help bring the community along for the ride.

I feel this accurately describes the problem with asking users to champion these kinds of requests. Consistently offloading documentation onto the community doesn't encourage contribution, as understanding of the project begins with documentation.
