### ISSUE TITLE
Sharing of providers in other uses & usage of GraphQL dependency injection elsewhere

### ISSUE THREAD

**Issue by laurisvan** [Urigo/graphql-modules#1754]
**Is your feature request related to a problem? Please describe.**

While the main usage of our providers is via our API service, there are a few support services (mainly scheduler) that would benefit from running the same providers in its own process.

Creating a stub application (with typedefs etc) feels a bit of overkill while the DI part would be very beneficial.

**Describe the solution you'd like**

Export RefleciveInjector (or a factory to create a an Injector) from within graphql-modules

**Describe alternatives you've considered**

An alternative would be to create a stub application with createApplication() with no resolvers, typedefs etc. It feels a bit of overkill, as none of them would be needed.

**Comment by dotansimha** [comment]
Hi @laurisvan ,

After creating the `Application` with `createApplication`, you can use it to get the `injector` and from there you can get access to all `Provider`s that defined on the app level, `Singleton` scope, or defined as `global: true`. 

Do you wish to use that without any typedefs at all? Why not leverage an existing GraphQL Application and its Injector, and just use it to get the instances you wish to trigger?

**Comment by laurisvan** [comment]
Yep, that's what I ended up doing. After all, graphql-modules application is quite thin layer, so I guess it's ok.

However, while it suffices for now, I believe we may need to use other DI frameworks for other processes, as it feels a bit silly to add graphql semantics for other modules. Now that the DI is much simpler than it was pre 1.0 modules, perhaps you could re-evaluate if you used Inversify.js again (I guess the DI you have was inspired of it).
