### ISSUE TITLE
graphql-shield not working as expected

### ISSUE THREAD

**Issue by derekr** [Urigo/graphql-modules#1772]
**Describe the bug**

Using `graphql-shield` w/ the `middlewares` config doesn't seem to work as expected. The docs are non-existent on this particular use case (couldn't find any docs, blogs or related issues in both repositories w/ working code examples), but I think this should work.

**To Reproduce**

https://codesandbox.io/s/compassionate-cohen-nyfhs?file=/index.js

**Expected behavior**

Field should not be accessible with provided config.

**Environment:**

- OS:
```
"apollo-server": "^3.0.0",
    "apollo-server-core": "^3.0.0",
    "graphql": "^15.5.0",
    "graphql-middleware": "^6.0.10",
    "graphql-modules": "^1.4.3",
    "graphql-shield": "^7.5.0"
```
- NodeJS: 12/14

**Additional context**

![CleanShot 2021-07-13 at 16 37 50](https://user-images.githubusercontent.com/22249/125538641-6091e04f-e8fa-426f-9fa8-2091c68b311f.png)

I've also attempted assigning the middleware at the application level (createApplication), but that didn't seem to work either.

**Comment by ardatan** [comment]
Which docs are you referring to?

**Comment by derekr** [comment]
@ardatan Hey! There are no docs on this specific use case (I should have been more clear), but going through other `grapql-shield` related issues it seems like others have had success with this use case.

**Comment by ardatan** [comment]
I think there is a confusion between GraphQL Modules Middlewares and `graphql-middleware` :) They are completely different things.
You should additionally attach `graphql-shield` to the schema created by GraphQL Modules;
https://graphql-shield.vercel.app/docs/getting-started#integrating-shield

**Comment by derekr** [comment]
Ok that makes sense. Was assuming there was some sort of interop (like it all uses the same middleware definition contract). Thanks for pointing me in the right direction!

**Comment by ardatan** [comment]
You're welcome!
