### ISSUE TITLE
Apollo server 3 upgrade

### ISSUE THREAD

**Issue by sahanatroam** [Urigo/graphql-modules#1781]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Apollo server 3 has been released with some under the hood upgrades
https://www.apollographql.com/docs/apollo-server/migration/

**Comment by sahanatroam** [comment]
hello @kamilkisiela @dotansimha 
Would you recommend that I start a new project with Apollo Server 2 + GraphQL Modules or should I simply use Apollo Server 3 now and then migrate the codebase to GQ-Modules once v3 is supported?

**Comment by dotansimha** [comment]
@sahanatroam have you tried graphql-modules with v3 of apollo-server? as far as I can see, the relevant APIs (for executor) remain the same, so it should work without any changes.

**Comment by ardatan** [comment]
GraphQL Modules currently supports Apollo Server v3 as you can see in our unit tests. Feel free to create an issue with a reproduction if you have any issues.
