### ISSUE TITLE
Documentation about features

### ISSUE THREAD

**Issue by ardatan** [Urigo/graphql-modules#182]
- [x] - OnRequest hook
- [x] - Encapsulation
- [x] - Circular Dependency
- [x] - Authentication
- [x] - Option factories (Passing configuration or schema to option factories)
- [ ] - Logger Interface
- [ ] - Middlewares
- [x] - Provider scopes and ModuleSessionInfo
- [x] - DI in factory functions ( InjectFunction wrapper function )
- [x] - DataSources support
- [x] - DirectiveResolvers and SchemaDirectives
- [ ] - Prisma integration #209

**Comment by dotansimha** [comment]
Also, document:
- Authentication
- `resolversComposition` usage (as object and as function)

**Comment by Tera3yte** [comment]
Also:

- Extending Modules (GraphQLModule.merge() ?)

**Comment by Tyler-Churchill** [comment]
Would also like to see documentation on:

- schema directives

**Comment by berstend** [comment]
Examples or best practices how to use in conjunction with code generation would be great as well.

Specifically making the resolvers strongly typed is a bit tricky currently, as we need to use a single generated file for all modules (as modules are able to extend schemas).


```ts
import { UserModuleContext } from "@modules/user/types";
import { UserResolvers, User } from "@generated/graphql/types";

export default {
  User: {
    id: currentUser => currentUser.id,
    username: currentUser => currentUser.username,
    current: (root, args, ctx) => {
      return ctx.authenticatedUser;
    }
  } as Partial<UserResolvers.Resolvers<UserModuleContext>>
};
```

I feel in order to make the modules as type safe as possible a custom `graphql-code-generator` template might be required.

I'm currently working on a full-featured [starter](https://github.com/berstend/graphql-microservice-starter) using graphql modules and so far it's been a great experience (esp. clear module dependencies and schema extending seem very scalable to me).

**Comment by ardatan** [comment]
@berstend 
Here you can see how to use resolvers signature together with graphql-modules, you can use `IResolvers` interface that is generated by graphql-code-generator.
https://graphql-modules.com/docs/guides/integrate-with-graphql-code-generator

**Comment by berstend** [comment]
Hey @ardatan, thanks for the quick feedback!

Without aiming to derail this PR with specifics, when I use `as IResolvers` my resolvers aren't really strongly typed (as the parameters are of `any` type):

`as IResolvers`
![image](https://user-images.githubusercontent.com/1368633/50743405-b9aa3c00-1217-11e9-97af-b378b0de5e52.png)

`as Partial<UserResolvers.Resolvers<UserModuleContext>>`
![image](https://user-images.githubusercontent.com/1368633/50743410-cfb7fc80-1217-11e9-8f0f-93df2dd839dc.png)

The generated `IResolvers` interface doesn't support passing a context, hence the feeling we might need to adjust/extend the codegen template here. :-)

```ts
export interface IResolvers {
  Query?: QueryResolvers.Resolvers;
  User?: UserResolvers.Resolvers;
}
```

**Comment by ardatan** [comment]
Thank you for your feedback :) Let's move this to graphql-code-generator, because code generation stuff is not part of graphql-modules.

**Comment by berstend** [comment]
Definitely, just wanted to mention here that there's huge potential for making extensive use of codegen (and the derived benefits) in the future. :-)

I'll continue exploring this and potentially submit PRs to `graphql-code-generator`.

**Comment by dandv** [comment]
Have [circular dependencies been dropped](https://github.com/Urigo/graphql-modules/issues/352#issue-417009053)?

**Comment by ardatan** [comment]
Yes they have.
https://medium.com/the-guild/manage-circular-imports-hell-with-graphql-modules-4b1611dee781
