### ISSUE TITLE
TypeError: Reflect.hasMetadata is not a function

### ISSUE THREAD

**Issue by delta98** [Urigo/graphql-modules#183]
Using `0.2.0` and examples within documentation, I'm receiving `TypeError: Reflect.hasMetadata is not a function` from `@graphql-modules/core/dist/di/index.js:208:22`

I'm not using any dependency injection, just basic example.

**Comment by delta98** [comment]
Solution is to import `reflect-metadata` - however, this isn't immediately obvious or addressed in any documentation

**Comment by dotansimha** [comment]
Hi @delta98 ! Thank you for reporting it! 
The internals of `graphql-modules` uses `reflect-metadata`, even if you are not using DI. 
We might be able to solve this by lazy-loading it. 
As a temporary solution, you can add `import 'reflect-metadata'` on your main entry point.
Keeping it open until we'll find a solution / document it.

@ardatan what do you think?

**Comment by ardatan** [comment]
We can do this after seperating DI logic from core package

**Comment by MANTENN** [comment]
Why is it closed? I am on `0.7.0` and its still required, I use a monorepo with typescript

**Comment by joemckie** [comment]
@ardatan I'm also having the same issue with `@graphql-modules/di 0.7.2`

**Comment by ardatan** [comment]
If you're using `di` package, it will be required. That's not an issue.

**Comment by joemckie** [comment]
@ardtan then it should be a dependency of the `di` package, no?

**Comment by ardatan** [comment]
@joemckie It is already in `peerDependencies`.
https://github.com/Urigo/graphql-modules/blob/a03f69f9669313c56bc96acd2aa149fcf7f7b2fa/packages/di/package.json#L14

**Comment by joemckie** [comment]
@ardatan ah must have missed that, thanks for that 👌
