### ISSUE TITLE
Documentation Update: Context Type Safety

### ISSUE THREAD

**Issue by bombillazo** [Urigo/graphql-modules#1860]
Changes to make ti clearer how to use and customize the Context type.

**Comment by bombillazo** [comment]
https://github.com/Urigo/graphql-modules/pull/1861#issuecomment-922623054

**Comment by dotansimha** [comment]
Thanks @bombillazo ! Merged your PR, closing :)

**Comment by bombillazo** [comment]
No problem! I saw the PR was merged, but the docs haven't changed.
