### ISSUE TITLE
Cannot import .graphql files

### ISSUE THREAD

**Issue by jchapple** [Urigo/graphql-modules#188]
Hello!

I have been trying to use TypeScript to import .graphql files, by using the method mentioned [here](https://graphql-modules.com/docs/guides/development-environment#import-from-graphql-files), however, I consistently receive the error:

```TSError: ⨯ Unable to compile TypeScript:
src/modules/auth/index.ts(2,27): error TS2307: Cannot find module './schema.graphql'.``
```

I have tried placing the `typings.d.ts` file within the same directory as the .graphql file, at the `src` level, at the project root. None have altered a single thing. It's as if TS isn't even seeing the .d.ts file. 

Here is the tsconfig:
```{
  "compilerOptions": {
    "lib": ["es2017", "esnext.asynciterable", "dom"],
    "target": "es2017",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "outDir": "dist",
    "typeRoots": ["node_modules/@types"],
    "paths": {
      "@lib/*": ["./lib/*"],
      "@models/*": ["./models/*"],
      "@modules/*": ["./modules/*"]
    },
    "baseUrl": "./src/",
    "allowSyntheticDefaultImports": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules"]
}
```

I have found [this related issue](https://github.com/apollographql/graphql-tag/issues/59), but despite trying all listed solutions, I have not been able to resolve the error.

Any help would be greatly appreciated.

**Comment by dotansimha** [comment]
@ardatan just updated to docs: https://github.com/Urigo/graphql-modules/blob/master/docs/guides/development-environment.md#import-from-graphql-files 
Thanks @jchapple

**Comment by yalamber** [comment]
Hello, I followed the documentation to import files from .graphql files, this works well in development but when building it seems to not build .graphql files and when I run npm start  there is this error: 
Error: Cannot find module './schema.graphql'
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "target": "es6",
    "lib": ["es6", "esnext", "es2015"],
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "sourceMap": true,
    "declaration": true,
    "outDir": "./dist",
    "rootDir": "./src"
  },
  "files": ["src/main.ts"],
  "include": ["src/**/*"],
  "exclude": ["node_modules", "**/*.spec.ts"]
}
```
My scripts
```
"scripts": {
    "dev": "nodemon --exec ts-node src/main.ts",
    "debug": "nodemon --exec node -r ts-node/register --inspect src/main.ts",
    "build": "tsc",
    "start": "node dist/main.js"
  },
```

**Comment by ardatan** [comment]
@yalamber Because your graphql files are still in the source file directory, you need to copy them to the output folder.

**Comment by yaldram** [comment]
For anyone who came across this issue of not finding `.graphql` files in your build please check this - https://github.com/a7ul/esbuild-node-tsc#optional-configuration
