### ISSUE TITLE
Guidance on build step for production use

### ISSUE THREAD

**Issue by sahanatroam** [Urigo/graphql-modules#1909]
Would be great to have a example of how a simple graphql-module should be built and hosted on a production environment

**Comment by sahanatroam** [comment]
Thanks @Urigo 
Here is a good example that I used as a base: https://github.com/aryankush25/microservice-node-server/tree/master/api-gateway

Would be good to have a baseline production build script if possible. Happy to help too.

**Comment by jycouet** [comment]
A few weeks ago I did a video speaking about modules: https://youtu.be/OR6Hi9makKk
Maybe it can help? Repos are linked in the description.

I'm preparing a new one about the same topic. ✨ Stay tuned ✨
