### ISSUE TITLE
[Question] Using libraries such as join-monster, which rely on mutating schema instance

### ISSUE THREAD

**Issue by jchapple** [Urigo/graphql-modules#198]
Hi again.

I've recently discovered a few GraphQL libraries that work by decorating / mutating the schema (`GraphQLSchema`) instance, and depend on those changes being persisted and not overwritten, such that those decorations can be accessed in resolvers with the `resolverInfo` argument (fourth argument). For example, [join-monster](https://github.com/acarl005/join-monster) requires adding custom properties to `GraphQLObjectType` constructors in order to be configured. When using Apollo, this can be achieved using an adapter, such as [join-monster-graphql-tools-adapter](https://github.com/acarl005/join-monster-graphql-tools-adapter), which works by [decorating / mutating](https://github.com/acarl005/join-monster-graphql-tools-adapter/blob/74b366d41dd6306dffaebc7d8860bdd4c1773c59/src/index.js) the schema based on a custom object you pass to it.

As far as I can tell, I cannot rely on mutating the schema instance in such a way when using GraphQL Modules, as [the schema are built using a factory method](https://github.com/Urigo/graphql-modules/blob/cad896f65678cb6a98d850a6d1f3dbd030008ad1/packages/core/src/graphql-module.ts#L366), which is called at strategic points in the control flow.

This has lead me to abandon the idea of being able to use such libraries with GraphQL Modules, viewing them as being idiomatically incompatible with one another. Is this an accurate conclusion, or have I missed something? Perhaps the solution could be as simple as formalising an interface for mutating / transforming a schema at a strategic point before the resolvers get called?

Cheers.

**Comment by jchapple** [comment]
Great, that would do the trick!

**Comment by ardatan** [comment]
Now you can mutate schema by using 
```
new GraphQLModule({
  // some definition
  middleware({schema}){
              //your logic
     return {
            schema
      };
   }
}
})
```

**Comment by jchapple** [comment]
Thanks! I tried that, but it didn't seem to work.

As a test, I tried:
```typescript
new GraphQLModule({
  // ...
  middleware({ schema }) {
    schema['__DIRTY__'] = true;
    return { schema };
  }
})
```

I see that the `middleware` function is getting called once, which seems to be when the `GraphQLModule` is initially bootstrapped.

However, when inspecting `resolverInfo.schema` from within a resolver, I see that the schema remains unchanged (e.g. I can't see the `__DIRTY__` property).

**Comment by ardatan** [comment]
Hi @jchapple!
I added tests for your case, and it passes.
https://github.com/Urigo/graphql-modules/commit/24eac3dac8463b07993680709816396988cfe7cb

**Comment by ardatan** [comment]
Could you try the following versions?
```
Changes:
 - @graphql-modules/core: 0.2.14 => 0.3.0-alpha.aca8a400
 - @graphql-modules/epoxy: 0.2.14 => 0.3.0-alpha.aca8a400
 - @graphql-modules/sonar: 0.2.14 => 0.3.0-alpha.aca8a400
 - @graphql-modules/utils: 0.2.14 => 0.3.0-alpha.aca8a400
```

**Comment by j-chapple** [comment]
Great, that seems to have fixed it. Many thanks! 🎉

**Comment by BeeHiveJava** [comment]
> Could you try the following versions?
> 
> ```
> Changes:
>  - @graphql-modules/core: 0.3.0-alpha.aca8a400
>  - @graphql-modules/epoxy:  0.3.0-alpha.aca8a400
>  - @graphql-modules/sonar: 0.3.0-alpha.aca8a400
>  - @graphql-modules/utils:  0.3.0-alpha.aca8a400
> ```

I just tested this today and it does not seem to work. I tested versions 0.4.2 and 0.5.0-alpha.e4344183. The modified schema only seems to get through when the middleware is added to the root module (so changing the root module or moving the middleware to the root module).

I'm using the exact sample supplied above by @ghost so I'm not certain where to go from here?

**Comment by ardatan** [comment]
#335 We are planning to change our merge logic, so you won't lose your modifications on child modules if you use middlewares.
Could you try it with the following versions?
```
Changes:
 - @graphql-modules/core: 0.4.2 => 0.5.0-alpha.b12e4322
 - @graphql-modules/di: 0.4.2 => 0.5.0-alpha.b12e4322
```

**Comment by BeeHiveJava** [comment]
> #335 We are planning to change our merge logic, so you won't lose your modifications on child modules if you use middlewares.
> Could you try it with the following versions?
> 
> ```
> Changes:
>  - @graphql-modules/core: 0.4.2 => 0.5.0-alpha.b12e4322
>  - @graphql-modules/di: 0.4.2 => 0.5.0-alpha.b12e4322
> ```

I just tested this and it does not seem to work. The schema only gets modified when applying the middleware on the root module.

**Comment by ardatan** [comment]
How do you test it?

**Comment by BeeHiveJava** [comment]
Root module:

```TypeScript
export const AppModule = new GraphQLModule({

    imports: [
        UserModule,
        EntryModule
    ]

});
```

Child module:

```TypeScript
export const UserModule = new GraphQLModule({

    typeDefs: definitions,
    resolvers: resolvers,
    middleware: ({schema}: any) => {
        schema["__DIRTY__"] = true;
        return {schema};
    }

});
```

This does not seem to modify the final schema for me. But again, when I place the middleware in the root module it does work:

```TypeScript
export const AppModule = new GraphQLModule({

    middleware: ({schema}: any) => {
        schema["__DIRTY__"] = true;
        return {schema};
    },
    imports: [
        UserModule,
        EntryModule
    ]

});
```

**Comment by ardatan** [comment]
@BeeHiveJava
The schema of each module is created independently from each other recursively.
First, `UserModule` creates a schema with its typeDefs and resolvers. Then, `middleware` gets called with that schema not the root module's.
Second, `AppModule` gets schemas from each imported module then merges it with its own typeDefs and resolvers.
So, I don't think we should reflect your custom property change to `AppModule`'s schema.

**Comment by BeeHiveJava** [comment]
I guess that the biggest use case would be libraries such as [join-monster](https://github.com/acarl005/join-monster). I think we can get these libraries to work by modifying the generated schema with custom properties afterwards, but it would be real nice if we could add custom properties to the schema from a module.

In addition I think that this is also solvable by implementing some custom directives and a middleware that parses them on the root module? That might even be a more elegant approach than monkey-patching the schema.

**Comment by ardatan** [comment]
So, the point is to get that field inside the resolver right?
Your child module can take the custom properties of its module's schema like this;
```
export const UserModule = new GraphQLModule({

    typeDefs: definitions,
    resolvers: {
        SomeType: {
          someField: (root, args, context, info) => {
             // schema has __DIRTY__ here
          }
         }
    },
    middleware: ({schema}: any) => {
        schema["__DIRTY__"] = true;
        return {schema};
    }

});
```

I just added a test for that case;
https://github.com/Urigo/graphql-modules/pull/335/files#diff-d906e55e6c8b73e6a4d023a5deb41485R1008

**Comment by BeeHiveJava** [comment]
You're right, I missed that point! I'll do some testing and I'll let you know if I get my use case for GraphQL-shield and join-monster to work.

**Comment by BeeHiveJava** [comment]
I tested and debugged some and your provided sample seems to work, the new properties are present on the schema @ardatan.

I couldn't, however, get [join-monster](https://github.com/acarl005/join-monster) to work, but it seems like the issue I'm having now is irrelevant. Thanks for all the support thus far, fantastic library . 👍

**Comment by ardatan** [comment]
@BeeHiveJava Let's keep this issue open until your issue is solved.

**Comment by ardatan** [comment]
We are using different approach for merging schemas, so I think your issue is solved in the latest version. Feel free to open this issue again if your problem persists.
