### ISSUE TITLE
Unable to resolve providers - Prisma integration

### ISSUE THREAD

**Issue by chanlito** [Urigo/graphql-modules#209]
The following is part from a `main.ts`.
```ts
// main.ts
const { schema, context, resolvers } = AppModule;

const prismaBinding = new PrismaBinding({
    endpoint: PRISMA_ENDPOINT,
    secret: PRISMA_MANAGEMENT_API_SECRET,
    debug: NODE_ENV === 'development',
    fragmentReplacements: extractFragmentReplacements(resolvers),
  });

const server = new ApolloServer({
  schema,
  introspection: true,
  playground: true,
  context: async (networkRequest: Request) => {
      const ctx = await context(networkRequest);
      ctx.injector.provide<PrismaClient>({
        provide: PrismaClient,
        useValue: prismaClient,
        scope: ProviderScope.Application,
      });
      ctx.injector.provide<PrismaBinding>({
        provide: PrismaBinding,
        useValue: prismaBinding,
        scope: ProviderScope.Application,
      });
      return { ...ctx };
    },
});
```

And I'm trying to get it somewhere in my UserModule. But it says dependency not found.
```ts
import { Prisma as PrismaClient } from '@/lib/prisma/prisma-client';
import { QueryResolvers, UserResolvers } from '@/types';

export const Query: QueryResolvers.Resolvers = {
  user: (parent, args, ctx, info) => {
    console.log('?', ctx.injector.get(PrismaClient));
    return {
      id: '1',
      username: 'chanlito',
      email: 'chanlito@fakemail.com',
      password: '',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
  },
};

```

I don't know if this is even allowed or not.

**Comment by chanlito** [comment]
@ardatan the only reason I'm trying to do my way is that this function `extractFragmentReplacements ` requires the `resolvers`.

**Comment by ardatan** [comment]
Ok create another module called Prisma, and put there a RequestScope factory function;
```
providers: [
 {
  provide: PrismaClient,
  useFactory: () => yourClient,
  scope: ProviderScope.Request
}
]
```
Then import this module wherever you need PrismaClient.
This will cause getting PrismaClient on runtime instead of module construction.

**Comment by ardatan** [comment]
Let me know if it worked.

**Comment by chanlito** [comment]
I've beed trying out graphql-modules all day now, and I ran to various issues which can be found here https://github.com/chanlito/graphql-app which shows usage of graphql-modules vs vanilla apollo server integrated with Prisma.

@ardatan I think your solution mentioned above might work with `prisma-client` but not with `prisma-binding`.

**Comment by ardatan** [comment]
@chanlito You can do the same thing for prisma-binding and you can get resolvers from AppModule. So it is supposed to work.

**Comment by ardatan** [comment]
Could you check this?
https://github.com/chanlito/graphql-app/pull/1

**Comment by chanlito** [comment]
Hey @ardatan thanks for the PR, but unfortunately it was not a success.

I've got the following error.

<img width="626" alt="screen shot 2018-12-06 at 10 58 31 am" src="https://user-images.githubusercontent.com/15667259/49560724-26df5e80-f946-11e8-8611-afb9283a6c2b.png">

I think we can't use `AppModule.resolvers` because it has not been instantiated.

**Comment by ardatan** [comment]
But it was working with canary version; `0.3.0-alpha.7132a265`.

**Comment by ardatan** [comment]
Any updates? @chanlito

**Comment by chanlito** [comment]
I upgraded to `0.3.0-alpha.7132a265` still getting that error.

**Comment by chanlito** [comment]
@ardatan I dunno how graphql-modules DI work internally, but is possible that we could set values (prisma-binding) to the container at runtime?

**Comment by chanlito** [comment]
So I managed to setup PrismaModule for prisma-client.

```ts
// now I can access it within my resolver like the following:
const db = injector.get<PrismaClient>(PrismaClient);
```

And if I need to use `prisma-binding`, I will be accessing it from the context directly.

I've also updated the example repo at https://github.com/chanlito/graphql-app. 
I'll leave this issue open for now.

**Comment by Urigo** [comment]
as now there is a new major version of Prisma, I'll close this one for now and we are happy to take PRs on demonstrating how to integrate GraphQL Modules and Prisma 2.0
