### ISSUE TITLE
📜 [Doc] Missing import statement in type-definitions section

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [Urigo/graphql-modules#2106]
**Describe the bug**

In the documentation of [Import Type Definitions](https://www.graphql-modules.com/docs/essentials/type-definitions) the presence of `join` has been left out. `import { join } from 'path'` should maybe be added

**Comment by B2o5T** [comment]
Your are right, would you submit a PR?

**Comment by sschneider-ihre-pvs** [comment]
There you go

**Comment by B2o5T** [comment]
@sschneider-ihre-pvs merged, thank you for contributing 🚀😉
