### ISSUE TITLE
Provider with scope operation is instantiated twice when executing multiple mutations

### ISSUE THREAD

**Issue by donroyco** [Urigo/graphql-modules#2168]
**Describe the bug**

When a provider with `Scope.Operation` is being used when executing multiple mutations (like two), it's instantiated twice. Is this expected behaviour?

**To Reproduce**
Steps to reproduce the behaviour:

See [this repository](https://github.com/donroyco/graphql-modules-bug) to reproduce the issue. The [README](https://github.com/donroyco/graphql-modules-bug/blob/main/README.md) file gives you the steps to see the behaviour.

Execute mutation:
```graphql
mutation Mutation {
  mutationOne
  mutationTwo
}
```

Output in terminal:
```bash
🚀  Server ready at http://localhost:4000/
SampleProvider: creating instance
SampleProvider: creating instance
```

**Expected behavior**

I would expect to that **one** provider (named `SampleProvider`) should be instantiated, like it was in earlier versions of GraphQL Modules (v0.x and using `Scope.Session`).

**Environment:**

- OS: macOS
- `graphql-modules`: v2.0.0
- NodeJS: v14

**Additional context**
N/A

**Comment by kamilkisiela** [comment]
#2216 

If you're not using Subscriptions, we recommend to use `createApolloExecutor` method.

```typescript
const apollo = new ApolloServer({
      typeDefs: app.typeDefs,
      resolvers: app.resolvers,
      executor: app.createApolloExecutor(),
    });
```

**Comment by kamilkisiela** [comment]
Example in `examples/apollo-subscriptions`
