### ISSUE TITLE
No support for Graphql

### ISSUE THREAD

**Issue by rajanmishra** [Urigo/graphql-modules#2179]
const application = createApplication({
      modules: [myModule],
    });

data = await graphql({
        schema: application.schema,
        source: request.payload?.query,
        rootValue: application.createExecution(),
      });
      
      while using graphql-module with graphql I am getting the following error

      Cannot read property 'ɵgetModuleContext' of undefined

**Comment by dotansimha** [comment]
@rajanmishra If you are going to use `graphql`'s `execute` function, you'll need to manually construct your `context` value and pass it to the execute function, and also maintain a manual lifecycle for the Context and `Operations` scope. This is done using `createOperationController`.  

Here's an example for how it's done in the `envelop` plugin of `graphql-modules`:
https://github.com/dotansimha/envelop/blob/main/packages/plugins/graphql-modules/src/index.ts#L12


Ideally, you should use the composed `execute` function of GraphQL modules, if you want it to be manage for you automatically (this should be the default behavior for most apps): 

```ts
const application = createApplication({
modules: [myModule],
});
const execute = application.createExecution();

execute(...);
``` 

Also: https://github.com/Urigo/graphql-modules/blob/master/examples/basic/src/index.ts#L18-L21
