### ISSUE TITLE
graphql-modules v2.0.0 doesn't have graphql 16.x as a peer dependency

### ISSUE THREAD

**Issue by the-ult** [Urigo/graphql-modules#2201]
**Describe the bug**

The latest release (2.0.0) of graphql-modules is not (yet) compatible with grapqhl 16:

```console
npm ERR! Found: graphql@16.5.0
npm ERR! node_modules/graphql
npm ERR!   graphql@"16.5.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^14.0.0 || ^15.0.0" from graphql-modules@2.0.0
npm ERR! node_modules/graphql-modules
npm ERR!   graphql-modules@"~2.0.0" from the root project
```

This is a problem when running `npm i --production` in docker 

I noticed that the root package.json and https://github.com/Urigo/graphql-modules/blob/master/packages/graphql-modules/package.json has a had an updated peerdependency for a while now. But there hasn't been a new release
```json
"peerDependencies": {
    "graphql": "^14.0.0 || ^15.0.0 || ^16.0.0"
  },
```

**Expected behavior**

A new (minor?) release with the updated `peerDependencies`

**Comment by kamilkisiela** [comment]
graphql-modules@2.1.0
