### ISSUE TITLE
Implicit dependency on lodash

### ISSUE THREAD

**Issue by dodas** [Urigo/graphql-modules#227]
Hi,
so while trying to make minimal demo to reproduce #226, I found out that `@graphql-modules/core` does require `lodash`, but it isn't listed in any dependencies. See: [search for lodash in this repo](https://github.com/Urigo/graphql-modules/search?q=lodash&unscoped_q=lodash).

**Comment by alfaproject** [comment]
This issue can be closed because a lot of the code was moved out from this repository to https://github.com/dotansimha/graphql-toolkit
