### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by gurusamy** [Urigo/graphql-modules#2273]
Hi We are getting this error on production. It is happening on intermittently. Please let me know what could be the issue
RangeError: Maximum call stack size exceeded\n    at destroyContextAndItsChildren (/data/instance/node_modules/graphql-modules/index.js:199:38)\n    at destroyContextAndItsChildren (/data/instance/node_modules/graphql-modules/index.js:206:13)\n    at destroyContextAndItsChildren (/data/instance/node_modules/graphql-modules/index.js:206:13)\n    at destroyContextAndItsChildren (/data/instance/node_modules/graphql-modules/index.js:206:13)\n    at destroyContextAndItsChildren (/data/instance/node_modules/graphql-modules/index.js:206:13)\n    at destroyContextAndItsChildren (/data/instance/node_modules/graphql-modules/index.js:206:13)\n    at destroyContextAndItsChildren (/data/instance/node_modules/graphql-modules/index.js:206:13)\n    at destroyContextAndItsChildren (/data/instance/node_modules/graphql-modules/index.js:206:13)\n    at destroyContextAndItsChildren (/data/instance/node_modules/graphql-modules/index.js:206:13)\n    at destroyContextAndItsChildren (/data/instance/node_modules/graphql-modules/index.js:206:13)

**Comment by dotansimha** [comment]
Hi @gurusamy , can you please share more information or a reproduction?

**Comment by gurusamy** [comment]
@dotansimha We got another error for the same scenario 
```Maximum call stack size exceeded\n    at Map.delete (<anonymous>)\n    at destroyContextAndItsChildren (/data/instance/node_modules/graphql-modules/index.js:201:37)\n    at destroyContextAndItsChildren (/data/instance/node_modules/graphql-modules/index.js:206:13)\n    at destroyContextAndItsChildren (/data/instance/node_modules/graphql-modules/index.js:206:13)\n    at destroyContextAndItsChildren (/data/instance/node_modules/graphql-modules/index.js:206:13)\n    at destroyContextAndItsChildren (/data/instance/node_modules/graphql-modules/index.js:206:13)\n    at destroyContextAndItsChildren (/data/instance/node_modules/graphql-modules/index.js:206:13)\n    at destroyContextAndItsChildren (/data/instance/node_modules/graphql-modules/index.js:206:13)\n    at destroyContextAndItsChildren (/data/instance/node_modules/graphql-modules/index.js:206:13)\n    at destroyContextAndItsChildren (/data/instance/node_modules/graphql-modules/index.js:206:13```

**Comment by Simon12121** [comment]
Hi @gurusamy and @dotansimha, I have also received this error. However, for me it only occurs when I make database queries with many return objects. Have you already found a solution for this problem?

**Comment by ardatan** [comment]
We need a failing test or a reproduction on CodeSandbox or StackBlitz

**Comment by Simon12121** [comment]
Hi @ardatan, I have created a repo on github for reproduction: https://github.com/Simon12121/graphql-modules-bug-replication. Because the error happens only when I make a query to MongoDb with many return objects, you would have to create an Atlas Free cluster. Maybe it happens also with other databases. I have stored my connection-string under environment/.env in the variable MONGO_DB_URI (not present in repo). First you would need to run the Mutation 'initFeatureTest' and the errors happens then when querying 'getAllNames'. I hope you can reproduce the error.

**Comment by enisdenjo** [comment]
Hey @Simon12121 and @gurusamy, thanks for your patience! Can you try out graphql-modules@2.2.1-alpha-20231102120726-44db491f please? https://github.com/Urigo/graphql-modules/pull/2461 has potential to fix your issue too. Thanks!

**Comment by enisdenjo** [comment]
Fixed in `graphql-modules@2.2.1` with #2461. Please try it out!
