### ISSUE TITLE
Error context.ɵgetModuleContext is not a function

### ISSUE THREAD

**Issue by Sandeep-Malhotra** [Urigo/graphql-modules#2293]
### Discussed in https://github.com/Urigo/graphql-modules/discussions/2292

<div type='discussions-op-text'>

<sup>Originally posted by **Sandeep-Malhotra** February  6, 2023</sup>

Error 
<img width="508" alt="image" src="https://user-images.githubusercontent.com/11954798/216888659-2c7abfa2-464f-455f-9436-e9b09dbc9afe.png">

code snippet
<img width="601" alt="image" src="https://user-images.githubusercontent.com/11954798/216888723-782de8df-f960-4661-992d-e2911d9e3fcd.png">

Full source code 
https://github.com/Sandeep-Malhotra/test-graphql

Kindly let me how to resolve it 

Thanks in advance </div>

**Comment by MatamandoKalilani** [comment]
Check out this link - https://github.com/Urigo/graphql-modules/issues/2270#issuecomment-1365000062

I think i was facing a similar problem, and it seemed to solve the issue.
