### ISSUE TITLE
Links not distinguishable

### ISSUE THREAD

**Issue by jonas-arkulpa** [Urigo/graphql-modules#231]
Hey guys,
just wanted to let you know that links in the documentation aren't clearly distinguishable from normal text.
Even if you hover them there is no underline or anything which would indicate that it is a link.

[Example on the first Site I read:](https://graphql-modules.com/docs/introduction/modules)
![Example with undistinguishable link](https://user-images.githubusercontent.com/17269256/50012039-e921ac00-ffbd-11e8-93a9-af1204fb99b5.png)
»Separation of Concerns« is a link

**Comment by ardatan** [comment]
Fixed :)

**Comment by nshaikhinurov** [comment]
Still there sometimes

[OnConnect hook](https://graphql-modules.com/docs/introduction/dependency-injection#onconnect-hook)
![image](https://user-images.githubusercontent.com/4477911/55316314-8f1ef680-5487-11e9-8fd0-0e8d36a90c09.png)
