### ISSUE TITLE
Prepare for Typescript 5.0 compatibility

### ISSUE THREAD

**Issue by patrickjm** [Urigo/graphql-modules#2323]
**Is your feature request related to a problem? Please describe.**

Typescript 5.0 changes rules around package.json exports and decorators, among other things.

**Describe the solution you'd like**

Introduce support for Typescript 5.0.

**Describe alternatives you've considered**

N/A

**Additional context**

https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-rc/

**Comment by dotansimha** [comment]
Available in `graphql-modules@2.1.1`.
