### ISSUE TITLE
Typescript 5 support

### ISSUE THREAD

**Issue by darkbasic** [Urigo/graphql-modules#2328]
**Describe the bug**

Typescript 5 has [tighter parameter decorator checking with --experimentalDecorators](https://github.com/microsoft/TypeScript/issues/52435).
That means [constructor parameter decorators should allow undefined as the type of key](https://github.com/nestjs/nest/issues/10959).

**To Reproduce**

Use the `Inject` decorator with Typescript 5+:

```
error TS1239: Unable to resolve signature of parameter decorator when called as an expression.
  Argument of type 'undefined' is not assignable to parameter of type 'string | symbol'.

50     @Inject(Pool) pool: DatabasePool,
        ~~~~~~~~~~~~
```

**Expected behavior**

Works with TS5+.

**Environment:**

- OS: Gentoo Linux ppc64le
- `graphql-modules`: 2.1.1
- NodeJS: v18.15.0

**Additional context**

**Comment by dotansimha** [comment]
Thanks @darkbasic ! 
This was fixed and released in `graphql-modules@2.1.2`
