### ISSUE TITLE
How to solve n+1 problem with graphql-modules?

### ISSUE THREAD

**Issue by biels** [Urigo/graphql-modules#240]
I am just getting started with graphql-modules and would like to know if (and if yes, how) the n+1 problem is solved. Also, it would be very helpful to add a section dedicated to it in the docs.

**Comment by dotansimha** [comment]
Hi @biels 
`graphql-modules` does not attempt to solve the n+1 problem. It's just a layer on top of GraphQL that allow you to write your server in a modular way. 
You can use packages like DataLoader to avoid loading the same data each time.

**Comment by biels** [comment]
Okay, thanks. Can I find an example somewhere of how to implement the dataloader pattern in graphql-modules?

**Comment by dotansimha** [comment]
@biels created a new issue for it: https://github.com/Urigo/graphql-modules/issues/246
