### ISSUE TITLE
[Feature request] Provide onResponse and onError hooks

### ISSUE THREAD

**Issue by iagomelanias** [Urigo/graphql-modules#293]
Currently, there is a hook called onHook which is very useful. I believe it would be great to to extend this functionality by adding new hooks, like `onResponse` and `onError` or implement [request middlewares](https://github.com/prisma/graphql-middleware).

### Use case:
I would like to send errors to a error reporting tool, like Sentry. Currently, i need to use Apollo Server `formatError`, which does not come with the context of the request. To get the context, i need to add it as plugin and call the context directly. I'm not sure how this would work in insolation.

By using graphql-middleware, we can not only track the errors, but change the args, response, etc. Very similar to how resolver compositions work.

```ts
export const SentryMiddleware: MiddlewareFn = async ({ root, args, context, info }, next) => {
  try {
    const response = await next();

    if (response instanceof Error) {
      notifyError(response, context);
    }

    return response;
  } catch (error) {
    notifyError(error, context);

    throw error;
  }
}
```

**Comment by ardatan** [comment]
That would be nice! Any PRs and more ideas are welcome!

**Comment by ardatan** [comment]
Added both in 0.7.6!
