### ISSUE TITLE
[Bug] Context is built every time the module is imported

### ISSUE THREAD

**Issue by iagomelanias** [Urigo/graphql-modules#294]
In [this tutorial](https://medium.com/the-guild/authentication-and-authorization-in-graphql-and-how-graphql-modules-can-help-fadc1ee5b0c2), there is a part where we use GraphQL Modules to build the `currentUser` context. The recommendation is to create a `AuthModule` and import it in every module we need to authenticate the user. But... there is a problem.

Every time we import a module into another module, the context is built. So, if we are making DB queries, we're going to make 3, 4, 5, db calls in every request.

A workaround is to create a service using `ProviderScope.Session` and store the user data in the class property and use it if exists. Is this the expected behavior?

**Comment by ardatan** [comment]
Yes, you're right. Context was built async for each module recursively before. But now we changed it and it is done using a sync iteration.
And for your case, it must be fixed in the latest version. Could you check and let me know if it works correctly.
