### ISSUE TITLE
Is there a way to use graphql-shield with modules?

### ISSUE THREAD

**Issue by pixelmeister** [Urigo/graphql-modules#297]
I tried to see if I could use `graphql-shield` via the middleware options field in `graphql-modules`, but that did not seem to work. The `resolversComposition` options seem like a good place to make it work as well, but `graphql-shield` is really set up to be used as middleware. Any tips on how to make it work? I can alway use the permissions at the top when I instantiate the server, but would rather the permissions be co-located with the resolvers in the module.

**Comment by ardatan** [comment]
#198
Do you have the same issue? If you have, could you try the canary versions in the last comment I shared there?

**Comment by Sytten** [comment]
Is there a way it could be integrated natively inside the modules. Maybe using the extensions that were added not long ago? @ardatan
