### ISSUE TITLE
About lucasconstantino/graphql-modules

### ISSUE THREAD

**Issue by lucasconstantino** [Urigo/graphql-modules#301]
Hey, you!

Thank god someone built a _better_ solution for GraphQL modularization. I have had my approach on it a couple of years ago, published as (guess what?) [graphql-modules](https://github.com/lucasconstantino/graphql-modules).

~I'm here to charge you for copy-right violations~

No, seriouly now: I didn't take my project forward, but there are still people reaching there and using a code-base which is more then 2 years old... thus why I'm here to see if you guys know what can we do to properly deprecate that project and point everything here. Also, I've seen you already got a nice `@graphql-modules` package namespace, but if it makes any difference I would be glad to make `graphql-modules` it available for you.

Cheers, thanks for the nice and needed open-source ;)

**Comment by Urigo** [comment]
Wow @lucasconstantino !!

First - Thank you so much!!! that is VERY generous and nice of you!!!

Second - About moving and deprecating, what do you think about releasing a new version on your side with a readme with a deprecation message can help, and then we can release `@graphql-modules/core` also as `graphql-modules` (after giving @dotansimha @ardatan and myself permissions to the npm release)?

Third - it looks like you are doing a lot of very nice and interesting things in open source and GraphQL yourself!!
Would be cool to meet and talk about work and maybe even collaborate on things!

**Comment by lucasconstantino** [comment]
Ok, so, what have I done so far:

on **GitHub**:
- [x] Updated project's description and tags;
- [x] Updated project's README to inform deprecation, and point to [Urigo/graphql-modules](https://github.com/Urigo/graphql-modules);
- [x] Archived repository, to make it read-only and avoid new issues/pull-requests.

on **NPM**:
- [x] Published a new version (`0.3.0`) with the updated README;
- [x] Deprecated versions `<= 0.3.0` with a message to point to _Urigo_'s repo;
- [x] Added @Urigo, @dotansimha, and @ardatan as maintainers of the `graphql-modules` package.}

---

About collaboration, well, I honestly would love to do more work on open-source stuff. I work in a [company](https://github.com/TallerWebSolutions) which has 10 repositories for each current dev of ours, and we have being in some minor conversations with the Apollo folks for a while now. @sebas5384 and I have some pull-requests merged in. We are certainly open for collaboration! We can move this conversation to the Apollo Slack if you think there is anything we can help ;)

**Comment by dotansimha** [comment]
Thank you @lucasconstantino ❤️ ! 
We published the latest version as `graphql-modules`.

**Comment by Urigo** [comment]
@lucasconstantino please also reach out to me on whatever channel you want, I'm sure we have a lot of things we can and should collaborate on
