### ISSUE TITLE
How to use modules with graphql-compose.

### ISSUE THREAD

**Issue by b091** [Urigo/graphql-modules#311]
Hi,
is there any way - or walk around for now to provide exetucable schema eg. from [graphql-compose](https://github.com/graphql-compose/graphql-compose)?

**Comment by ardatan** [comment]
You can use `extraSchemas` field;
```
new GraphQLModule({
        // other definitions
        extraSchemas: [
           yourSchema
        ]
});
```

**Comment by tomdev10** [comment]
Can I reopen this and ask how this was achieved?

**Comment by ardatan** [comment]
I don't know

**Comment by ardatan** [comment]
I don't know much about `graphql-compose`. So does it expose a schema or mutate the existing schema?

**Comment by kamilkisiela** [comment]
Closing in favor of #1466
