### ISSUE TITLE
Make graphlql-modules compatible with SchemaLink

### ISSUE THREAD

**Issue by RIP21** [Urigo/graphql-modules#313]
I'm using an alpha based on this PR https://github.com/Urigo/graphql-modules/pull/312
And I have exactly the same issue on the larger codebase as I have here in sandbox below.
https://codesandbox.io/s/92kxln66vy

I think SchemaLink is used in unit tests heavily when you develop a real ApolloServer. 
But I using it to have GraphQL Server on Client.

Making it work properly will enable us at Revolut to us `graphql-modules` since we don't have a real server just yet.

**Comment by ardatan** [comment]
Available in 0.4.1
