### ISSUE TITLE
Support GraphQLSchema

### ISSUE THREAD

**Issue by birkir** [Urigo/graphql-modules#321]
Currently I'm creating my schemes with GraphQLSchema and extracting typeDefs and resolvers with:

```ts
const schema = new GraphQLSchema(...);
const typeDefs = printSchema(schema)
const resolvers = {
  Query: {
    thing: ThingType.resolve,
  },
  AnUnion:{
    __resolveType: AnUnion.resolveType
  },
};

const module = new GraphQLModule({
  typeDefs,
  resolvers,
  ...
});
```

How hard would it be to support just dropping the schema object right in without having to define the resolvers?

I am having a hard time making field in a type that returns an list of Unions to show any data, where it works fine with normal schema.

Any ideas welcome

**Comment by ardatan** [comment]
You can use `extraSchemas` field if you want to pass GraphQLSchema object into GraphQLModule.

**Comment by birkir** [comment]
Ah very nice, I was just thrown away from the naming but I get it now.

Only issue with that is I have to manually add union __resolveType to the resolvers map.

type-graphql has a resolverMap function that I am able to extract  and filter them from.

Thanks for the quick response
