### ISSUE TITLE
Bundle size after updating to @graphql/core 0.4.1 grew massively

### ISSUE THREAD

**Issue by alfaproject** [Urigo/graphql-modules#322]
So after updating to latest version, my bundles pretty much duplicated in size from 2.78mb to 5.09mb.

It looks like `graphql-toolkit` brings a bunch of transient dependencies like a chunk of Babel and TypeScript itself: https://puu.sh/CHCvc/608cd28a71.png

Is it possible to do anything about this?

**Comment by ardatan** [comment]
Are you using GraphQL-Modules on the server?
If yes, why do you need to use Babel and create a bundle?

**Comment by alfaproject** [comment]
Yes, because I'm working with lambda functions and size/performance matters a lot, but I can't see any reason for this library not be used on front-end either which would suffer from the same bundling issues. ):

I'm not using Babel. Babel is a transient dependency of `graphql-toolkit`:
```
› yarn why @babel/parser
yarn why v1.12.3
[1/4] 🤔  Why do we have the module "@babel/parser"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@babel/parser@7.3.2"
info Reasons this module exists
   - "@graphql-modules#core#graphql-toolkit#graphql-tag-pluck" depends on it
   - Hoisted from "@graphql-modules#core#graphql-toolkit#graphql-tag-pluck#@babel#parser"
   - Hoisted from "@graphql-modules#core#graphql-toolkit#graphql-tag-pluck#@babel#traverse#@babel#parser"
   - Hoisted from "@graphql-modules#core#graphql-toolkit#graphql-tag-pluck#@babel#traverse#@babel#helper-function-name#@babel#template#@babel#parser"
info Disk size without dependencies: "384KB"
info Disk size with unique dependencies: "384KB"
info Disk size with transitive dependencies: "384KB"
info Number of shared dependencies: 0
✨  Done in 0.70s.
```

Same thing for TypeScript and a few other smaller/medium dependencies.

**Comment by ardatan** [comment]
We can provide es2015 module in addition to commonjs, then you can do tree shaking. I'll try to manage that.

**Comment by ardatan** [comment]
Treeshaking is available in the latest version. Please open the issue again if your problem persists.
