### ISSUE TITLE
"Cannot read property 'fetch' of undefined" when using Request scope with RESTDataSource

### ISSUE THREAD

**Issue by Und3Rdo9** [Urigo/graphql-modules#339]
Using RESTDataSource as Provider with `ProviderScope.Application` and `ProviderScope.Session` works just fine, but as soon as you switch to `ProviderScope.Request`, fetch in`RESTDataSource.ts` is `undefined`. It seems like the `intialize` method is not being called in this case which initialises the httpCache with the fetch method on it. See: https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource-rest/src/RESTDataSource.ts#L51-L54

**Comment by 5amfung** [comment]
I also used RESTDataSource as Provider, but with `ProviderScope.Session` only.  `initialize` doesn't seem to be called as all because `this.context` is an empty object.  Had `initialize` been called, I should see some keys set in `this.context`.

**Comment by ardatan** [comment]
Must be fixed in this canary version;
`@graphql-modules/core@0.7.0-alpha.aeba5abf`

**Comment by ardatan** [comment]
It is available in 0.7.0.
