### ISSUE TITLE
Inject db in context without ts?

### ISSUE THREAD

**Issue by FerX** [Urigo/graphql-modules#346]
I apologize for the request,
but I can not find a way to **inject the reference to the DB in the context**.
**I do not use ts.**

thank you very much.

**Comment by ardatan** [comment]
Since TS is not required for GraphQL-Modules, you can use Injection Tokens;
```js
export const DB = Symbol('DB');
export const DBModule = new GraphQLModule({
   providers: [{
       provide: DB,
       useValue: YOUR_DB_INSTANCE_HERE
   }],
   resolvers: {
      Query: {
            foo: (root, args, context, injector) => injector.get(DB).doSomeStuff()
      }
   }
})
```

**Comment by FerX** [comment]
OK thanks,
in this way it works.
I thought there was a way to avoid doing includes in every module.
