### ISSUE TITLE
Help with circular dependency with Auth and User modules

### ISSUE THREAD

**Issue by betaflag** [Urigo/graphql-modules#352]
I'm currently building on your basic example where there's a `auth` module and an `user` module and where the former depends on the latter.

If I want to add stuff into the `user` module that needs authentication (ex: managing users), I understand that I need to add the `auth` module as a dependency, however this creates a circular dependency.

The only alternative I see is to move basic user stuff into Auth and create a UserManagement module but that isn't really a satisfying design.

Since circular dependency feature has been drop, can you help me find a solution for this problem?

**Comment by ardatan** [comment]
I think there should be a basic User module, then an authentication module imports this basic User Module, then another module imports both. Does it work for you?

**Comment by betaflag** [comment]
I'm not sold. By design, my app should have a User module for CRUD operations and an Auth module for Authentication. This is the first foundational block I'm coding and I'm already resorting into a workaround because graphql-modules doesn't support it. I understand that enabling circular dependency is like shooting ourselves in the foot and I would love coming up with a better solution, I'm just not familiar enough with dependency injection. However, this isn't something new, I mean, authentication and user management is basic stuff and there's probably plenty of libraries that have solved the issue already. I'm going to do some research on my own but if I find that enabling circular dependencies is the most suitable solution, I see only two solutions: implementing it this graphql-modules (I think you supported it before) or using another module system like nestjs.

**Comment by ardatan** [comment]
I still don't understand your point to have a single `User` module for all `User` operations. you can seperate modules by functionalities. Manipulating user data on the data source is a single functionality while checking it by your Authentication Module is another.

User.graphql
```graphql
type User {
  id: ID
  name: String
  # other fields
}
```

UserProvider.ts
```ts
@Injectable()
export class UserProvider {
  constructor(private db: Db) {}
  collection = db.collection('users');
  getUserById(userId: string){
   return this.collection.findOne(userId);
  }
 getUsers() {
   return this.collection.find().toArray(); 
 }
}
```

UserModule.ts
```ts
import User from './User.graphql';
export const UserModule = new GraphQLModule({
       typeDefs: [User],
       resolvers,
       imports: [ DbModule ],
       providers: [
         UserProvider
       ]
})
```

AuthProvider.ts
```ts
@Injectable({ scope: ProviderScope.Session })
export class AuthProvider implements OnRequest {
  cosntructor(private userProvider: UserProvider){}
  currentUser: User;
  onRequest(req: Request) {
      // some logic to get user id by token
      this.currentUser = await this.userProvider.getUserById(user);
  }
  hasRole(role: String) {
    // some logic with currentUser
   return someBoolean;
  }
}
```

Auth.graphql
```graphql
enum AccountType {
 User
 Admin
}
extend type User {
  # some fields for password etc
 accountType: AccountType 
}
```

AuthModule.ts
```ts
export const AuthModule = new GraphQLModule({
  imports: [ UserModule ],
  providers: [ AuthProvider ],
  typeDefs,
  resolvers
})
```

UserManagement.graphql
```graphql
type Mutation {
  someRestrictedMutation(...): ...
}
```

UserManagementModule.ts
```ts
export const UserManagementModule = new GraphQLModule({
  imports: [ AuthModule, UserModule ],
  providers: [ UserManagementProvider ],
  typeDefs,
  resolvers: {
     Mutation: {
        someRestrictedMutation: (root, args, { injector }, info) => {
            const authProvider = injector.get(AuthProvider);
            if (authProvider .hasRole('someRestrictedMutation')) {
                  throw new Error('Unauthorized');
            }
           // ...
        }
     }
  }
})
```

**Comment by dandv** [comment]
@ardatan: This User/Auth situation was just *one* example.

The general case of many-to-many relationships is very common. Does graphql-modules support that or not?

Another example if that helps: `User`s are engaged in online `Videoconference`s. A `User` has signed up for a number of upcoming `Videoconference`s, and each `Videoconference` has a number of participants of type `User`. How should we model that?

**Comment by ardatan** [comment]
@dandv This is not about GraphQL Modules but how you design your structure. You can model it feature-based then.
https://medium.com/the-guild/manage-circular-imports-hell-with-graphql-modules-4b1611dee781

***UserModule***
```graphql
type User {
  id: ID
  username: Strıng
  email: String
}
```

***Conference*** (imports UserModule)
```graphql
type Conference {
  topic: String
  participants: [User!]
}

extend type User {
  participants: [User!]
}
```

**Comment by dandv** [comment]
```gql
extend type User {
  participants: [User!]
}
```

Good advice, thanks!
