### ISSUE TITLE
DI is not working inside providers - @babel/typescript

### ISSUE THREAD

**Issue by KharamanV** [Urigo/graphql-modules#353]
When i'm trying to inject some provider into some other provider, i don't receiving anything in constructor.

`ChatsProvider`
![image](https://user-images.githubusercontent.com/4006620/53810085-d84e5a00-3f5e-11e9-9728-c534cc8f950d.png)

`ChatsModule` (I have `AuthGraphQLProvider` in the `AuthGraphQLModule`)
![image](https://user-images.githubusercontent.com/4006620/53810180-121f6080-3f5f-11e9-9ede-2204a905d776.png)

`AuthGraphQLModule`
![image](https://user-images.githubusercontent.com/4006620/53810252-33804c80-3f5f-11e9-90fb-03c94f174997.png)

`AuthGraphQLProvider`
![image](https://user-images.githubusercontent.com/4006620/53810276-41ce6880-3f5f-11e9-88c1-e1a02d6d68e3.png)

**Comment by ardatan** [comment]
Do you have `reflect-metadata` in your project?

**Comment by KharamanV** [comment]
> Do you have `reflect-metadata` in your project?

Hi! Yes, i have.
`import 'reflect-metadata';` in the root of the project (`0.1.13` version)

**Comment by ardatan** [comment]
@KharamanV Could you reproduce a repo?

**Comment by KharamanV** [comment]
> @KharamanV Could you reproduce a repo?

Link to the repo: https://github.com/KharamanV/gql-modules-test

Steps to reproduce:
1. `yarn install & yarn start`
2. Go to the http://localhost:8080/graphql
3. insert `subscription {
  messageAdded {
    text
  }
}`

I'm trying to inject `AuthGraphQLProvider` into `src/modules/Chats/graphql/ChatsProvider.ts` file.

Inside `ChatsProvider` you can see console.log of the `AuthGraphQLProvider`

@ardatan Thank you very much for helping!

**Comment by ardatan** [comment]
@KharamanV Somehow babel-typescript doesn't reflect typings as metadata properly. I don't know much about babel-typescript. And I think there is no point to use babel-typescript while typescript's own compiler already compiles everything properly for NodeJS. If you want to use TypeScript on runtime, you can prefer `ts-node`, instead of having a bunch of configuration with babel. With `ts-node`, you will have two dependencies; `ts-node` and `typescript` while babel-typescript requires a lot of `@babel/YET_ANOTHER_BABEL_PLUGIN`.

**Comment by ardatan** [comment]
Yes, of course but I don’t know how to solve it.

**Comment by ardatan** [comment]
@KharamanV Unfortunately, @babel/typescript doesn't use Type Reflection like TypeScript's official compiler does. So, you have two options; use ts-node/typescript or `@Inject()` decorator to inject providers inside other providers.

**Comment by eugeneoshepkov** [comment]
@ardatan There's third option now using [babel-plugin-transform-typescript-metadata](https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata). Could you add it to the readme section, please? As it can be not an easy task to drop babel and switch to ts-node, it's good to have this workaround for people using `@babel/preset-typescript`
