### ISSUE TITLE
Node 8 doesn't support decorator.

### ISSUE THREAD

**Issue by 5amfung** [Urigo/graphql-modules#378]
My company is still on Node v8.  How do I go about using `@Injectable`?  I'm getting...

```
@Injectable({
^

SyntaxError: Invalid or unexpected token
```

**Comment by ardatan** [comment]
I think you are using plain JavaScript, so I recommend you to use Babel for decorators.

**Comment by 5amfung** [comment]
I think I managed to make it worked without using babel nor switching to TypeScript.  A lot of developments are still using plain js.  I hope Babel and TypeScript don't become manadatory in the future.

**Comment by 5amfung** [comment]
For the others perusal, I did this.

```
module.exports = Injectable({...})(MyProvider);
```

**Comment by angaziz** [comment]
Hi @5amfung, do you have any obstacle when using graphql-modules on your non-typescript project?
