### ISSUE TITLE
[Feature Request, Question] onOperationComplete() lifecycle hook from Apollo Server

### ISSUE THREAD

**Issue by nshaikhinurov** [Urigo/graphql-modules#390]
I'm using subscriptions and I'm trying to handle an event when Apollo Server (with App GraphQl Module connected) receives message of type GQL_STOP from client over ws connection as described in the [graphql-ws Protocol](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md).

In Apollo Server [docs](https://www.apollographql.com/docs/graphql-subscriptions/lifecycle-events) there is an onOperationComplete() hook for that which can be declared in SubscriptionServer constructor

The question is can i determine the fact that Apollo server received such message in a GraphQL Module or in a Provider's code in particular. Or can I get the SubscriptionServer from App GraphQl Module somehow and inject 'native' Apollo onOperationComplete() hook there and use it as described in the docs mentioned above.

My use case is closing a helperer internal ws connection with another backend which serves data on subscription when there is no need in keeping that connection. 

The onDisconnect() hook is not invoked because the graphql client is still connected to Apollo Server via ws and can initialize another operation (new subscription particularly)

**Comment by ardatan** [comment]
I created a PR related to your feature request. You can try the canary alpha version;
`@graphql-modules/core@0.7.0-alpha.d44931da`

**Comment by ardatan** [comment]
It is available in 0.7.0.
