### ISSUE TITLE
GraphQL-Modules Error: Schema is not valid! error when running compiled code with node instead of ts-node

### ISSUE THREAD

**Issue by tlabarge** [Urigo/graphql-modules#415]
I've been trying to follow the recipe at  https://github.com/Urigo/graphql-modules/blob/master/docs/recipes/load-your-schema.md#using-sonar-in-graphql-toolkit to put my schema definition files into `*.graphql` files within a `schema` sub-directory of a module. This works perfectly when I run the code with `ts-node`. However, after compiling the code with `tsc`, I get the following error when I try to start the Apollo server with `node` instead of `ts-node`:

```
GraphQL-Modules Error: Schema is not valid!
```

This occurs if I put all of the module schema definitions into a single `*.graphql` file or use multiple `*.graphql` files, so it looks like a problem of not recognizing the schema and not some kind of merging issue.

When I use a `gql` string for the `typeDefs` property in the object that is passed to `new GraphQLModule()` the code will run fine with both `ts-node` and after compiling with `tsc` and running under `node`.

I also find that using `loadResolversFiles` to load multiple resolver files works just fine under both `ts-node` and `node` after compiling with `tsc`, so the problem seems to be specific to schema files.

**Comment by ardatan** [comment]
You should copy your files to the JavaScript output folder as well.

**Comment by tlabarge** [comment]
@ardatan Thanks for the reply, but I am afraid that it still does not work for me.

I'm puzzled by your comment about Sonar not being part of GraphQL-Modules. Looking at the documentation at https://graphql-modules.com/docs/recipes/load-your-schema, it references the following import: `import { loadResolversFiles, loadSchemaFiles } from '@graphql-modules/sonar';`

However, I agree that I do not see sonar within the graphql-modules codebase in the git repo. I'm wondering if the documentation that I am working to is out of date.

**Comment by dotansimha** [comment]
@tlabarge can you please provide an example module file, and add a screenshot of the files tree? 
Regarding sonar, the docs are outdated, the import should come from `graphql-toolkit` now.
