### ISSUE TITLE
production config

### ISSUE THREAD

**Issue by ScreamZ** [Urigo/graphql-modules#437]
Hello,

I see that you recommend using .gql files,

In production I wish to use nodeJS with compiled files from ts instead of ts-node.
But .gql files are not copied, what do you recommend to run in production ? in order to use .gql files and be ready ?

Regars

**Comment by OLDIN** [comment]
Hi. I have the same problem.
How to solve this, can an example configuration for production ?!
Thanks you.

**Comment by ardatan** [comment]
You can use typescript files for gql definitions or copy the same files to your JS output folder.

**Comment by ScreamZ** [comment]
I'll take time to write and share a good webpack config for such… I won't migrate for now because this is too complex… Thanks
