### ISSUE TITLE
Can't find getFieldsWithDirectives in @graphql-modules/utils

### ISSUE THREAD

**Issue by JeromeBu** [Urigo/graphql-modules#439]
I am trying to implement authentication with graphql-modules following this post : https://medium.com/the-guild/authentication-and-authorization-in-graphql-and-how-graphql-modules-can-help-fadc1ee5b0c2

I am not able to import get the fields with directives with following function:
```
import { getFieldsWithDirectives } from '@graphql-modules/utils';
```

It seems the utils module has been moved but I can't find where...

**Comment by ardatan** [comment]
@JeromeBu Could you try to use `graphql-toolkit`? It's supposed to have that method.
@dotansimha I think the blog post should be updated.

**Comment by JeromeBu** [comment]
@ardatan I believe that there was an export missing in the utils index in `graphql-toolkit`, I just made a PR to fix it : https://github.com/ardatan/graphql-toolkit/pull/90/files
