### ISSUE TITLE
resolversComposition next is not a function

### ISSUE THREAD

**Issue by GiddeonWyeth** [Urigo/graphql-modules#441]
I'm having a problem with middleware that is passed to resolversComposition.
Call of `next` function in middleware end with error `next is not a function`
```import {GraphQLModule} from '@graphql-modules/core';
import Auth from './auth'
import Test from './test'
import User from './user'

const authenticated = () => next => async (root, args, context, info) => {
    if (!context.id) throw new Error('You are not authenticated!');
    return next(root, args, context, info);
};

const AppModule = (new GraphQLModule({
    imports: [User, Auth, Test],
    resolversComposition: {'Query.protected': [authenticated()]}
}));

**Comment by dotansimha** [comment]
Hi @GiddeonWyeth ,
Sorry for the delay. I managed to reproduce it, and it should work now with `0.7.2`.

**Comment by authentik8** [comment]
I've also been experiencing this issue in 0.7.5, specifically when attempting to use a directive defined in one module in an other - can file a separate issue if required?

**Comment by Urigo** [comment]
@authentik8 do you think it might be the same issue as https://github.com/Urigo/graphql-modules/issues/472 and https://github.com/ardatan/graphql-toolkit/issues/100 ?

**Comment by authentik8** [comment]
I'm not sure - I'm not getting OOM errors, rather just error messages returned to the client instead. I've also tried variants of directive definitions with both single parameters as well as array arguments, both return the same error.

**Comment by authentik8** [comment]
Just figured out what was going wrong:

I had defined a `roles` directive and was using it as a guard on a type like the below:

```graphql
type EmployeeRecord {
  firstName: String!
  surname: String!
  email: String! @roles(["admin"])
}
```
I had been relying on the default GraphQL resolution path of attribute lookup, and therefore hadn't defined an `email` resolver - adding logic along the lines of the below fixed the error:
```javascript
...
resolvers: {
  EmployeeRecord: {
    email: obj => obj.email
  },
}
```

Presumably if there are no resolvers other than directives in the path for a given attribute, there should be a fall back to simple attribute lookup? If you can point me to the right place, happy to submit a PR!

**Comment by ardatan** [comment]
@authentik8 Could you create a repo that reproduces this issue?

**Comment by authentik8** [comment]
Sure, give me a couple of hours
