### ISSUE TITLE
Providers' onInit() Hook Is Not Called on App Start

### ISSUE THREAD

**Issue by derek-fong** [Urigo/graphql-modules#459]
According to the [OnInit Hook docs](https://graphql-modules.com/docs/introduction/dependency-injection#oninit-hook): 

> `OnInit` hook is called once when your application is started.

However, I noticed the `OnInit` hook won't be called on app start. In fact, it's not being called until the provider (which implements `OnInit`) is injected and executed in resolver(s).

I was trying to execute some app init tasks with the help of `OnInit` hook, but unfortunately this won't work as expected if the codes are not executed until it's being injected on first resolver call.

Is this an expected behaviour? If so, then I would suggest updating the documentation to clarify this, as current documentation is not describing it's actual behaviour. I am happy to create a PR to update the documentations if required.

I have also created a[ CodeSandbox](https://codesandbox.io/s/yko9yr7n1j?fontsize=14) to help describe the problem:

[![Edit graphql-modules-oninit-test](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yko9yr7n1j?fontsize=14&module=%2Fsrc%2Fapp%2Fapp.provider.ts)

- Observe Terminal output - Console log `[AppProvider] onInit() called` won't show until a "message query" is called on `GraphQL Playground`.

_(Note: You might need to [fork the Sandbox](https://codesandbox.io/s/yko9yr7n1j?fontsize=14) -> `Restart Server` on `Server Control Panel` if you dont't see the "OnInit" console output, because `onInit()` is only called once on first resolver execution. )_

**Comment by ardatan** [comment]
@derek-fong 
`onInit` is getting called on construction of injector (lazy). I will take a look at it but for now you can do this workaround for now;
```
const { schema, injector } = AppModule;
```

**Comment by ardatan** [comment]
@derek-fong Could I know your use case for onInit?

**Comment by ardatan** [comment]
I am closing this issue for now. If you have any further questions and persisting problems, please feel free to open a new issue.
