### ISSUE TITLE
Eager loading providers?

### ISSUE THREAD

**Issue by markspolakovs** [Urigo/graphql-modules#473]
I'm setting up a system for Relay-like generation of global IDs. The approach I've taken is to have a `GlobalIDProvider` where all my module providers register themselves in the constructor, which is then responsible for handing out global IDs.

Example:
```ts
export const FoldersModule = new GraphQLModule({
    imports: [GlobalIDModule],
    typeDefs: gql`
      # snip
    `,
    providers: [
        FolderProvider
    ]
})
```
```ts
@Injectable()
export class FolderProvider {
    constructor(private globalId: GlobalIDProvider) {
        this.generateGlobalId = globalId.register("Folder", {
            async getObjectById(id) {
                return await FolderService.findById(id);
            }
        });
    }
}
```

```ts
@Injectable()
export class GlobalIDProvider {
  private types: Map<string, GlobalIDType<any>> = new Map();

  public register<T extends GIDable>(type: string, meta: GlobalIDType<T>) {
    this.types.set(type, meta);
    return function makeGID(id: string) {
        return Buffer.from(type + "/" + id).toString("base64");
    };
  }
}
```

and then I can use these global IDs in queries:
```graphql
query GlobalID {
  node(id:"Rm9sZGVyLzE=") {
    __typename
  }
}
```

The problem I'm running into is that graphql-modules only loads a module's providers the first time it is needed, so my FolderProvider doesn't run until I specifically query my FoldersModule. So, if I run the above GlobalID query immediately after server start, the FolderProvider hasn't executed yet, thus the GlobalIDProvider can't find it and throws an error.

Is there a way to "eager load" all providers upon server startup? Alternatively, is there a better solution here?

**Comment by ardatan** [comment]
If you'd like to call something on application startup, you can use `onInit` lifecycle hook.
https://graphql-modules.com/docs/introduction/dependency-injection#oninit-hook
