### ISSUE TITLE
Custom context property is lost when using resolversComposition

### ISSUE THREAD

**Issue by dancon** [Urigo/graphql-modules#505]
You can reproduce the problem with the repo <https://github.com/dancon/apollo-server_graphql-modules_subscriptions>

in the `src/index.ts`

```
const { schema, context, subscriptions } = new GraphQLModule({
  imports: gmodules,
  context () {
    return {
      user: {
        id: 'u123',
        name: 'Tom'
      }
    }
  },
  resolversComposition: {
    'Query.getUserInfo': [ authenticated ]
  }
})
```

debug with vscode

`src/middleware/authentication.ts`
![image](https://user-images.githubusercontent.com/6836599/59409794-b0865200-8de9-11e9-8eba-847679b0457f.png)

`src/schemas/user/resolvers.ts`
![image](https://user-images.githubusercontent.com/6836599/59409868-e3c8e100-8de9-11e9-982d-f043aa3248a1.png)

Is I missing some thing?

**Comment by ardatan** [comment]
This is not an issue, your composition belongs to the module that has context while resolver itself belongs to another module that don't have that context. I recommend you to move composition and context to `user` module.

**Comment by dancon** [comment]
@ardatan I got it ~ thank you！But I wonder whether is there a way to make it accessible to all the modules that import to `root module`. Like a global context settings,  I think it is very superfluous to import an authentication module to every submodules. Maybe there are some modules do not need authentication, but you can do nothing with that, I hope GraphQL Modules can support the feature ~
