### ISSUE TITLE
Dataloader docs should mention per-request caching

### ISSUE THREAD

**Issue by edorivai** [Urigo/graphql-modules#511]
As [mentioned in the official dataloader](https://github.com/graphql/dataloader#caching-per-request) docs, the most common use case for dataloader is to only utilize a cache-per-request. The [current docs](https://graphql-modules.com/docs/recipes/data-loader) implement a setup where items are cached indefinitely.

While not necessarily wrong, this could be a footgun, especially for less experienced developers that aren't familiar with the subtleties of cache invalidation problems.

I would suggest to either add a new "primary" example, which is set up to use per-request caching. Or alternatively, to clearly touch on per-request vs indefinite caching of dataloader in the docs.

**Comment by ardatan** [comment]
You're right, we should suggest you to use dataloaders as session-scope provider to have the exact behavior like in DataLoader's official docs like below;
```ts
{
  provide: `SOME_DATA_LOADER`,
  scope: ProviderScope.Session,
  useFactory: () => new DataLoader(...)
}
```
