### ISSUE TITLE
Would 'DB Connection Pooling' be the best use in this situation?

### ISSUE THREAD

**Issue by NickBronze** [Urigo/graphql-modules#518]
I recently found this module and really want to integrate it into my existing applications. I have reached a point where I have all my modules ready with dummy data, but now I'm not sure how to proceed in loading from my database. My applications currently specify MongoDB models and then use the helper functions (.findOne, etc.) from mongoose. I've also decided to move over to typescript, so I'm not sure if I'm processing all the information I'm taking in.

I found this page in your docs,
https://graphql-modules.com/docs/recipes/db-connection-pooling

However, I'm not sure if it would apply to my situation here. Can you please guide me in the right direction?

Thanks!

ps: your website's contact me isn't working :(

**Comment by ardatan** [comment]
I just added an example with MongoDB there in docs; https://graphql-modules.com/docs/recipes/db-connection-pooling
And you can also check my fork that uses MongoDB;
https://github.com/ardatan/WhatsApp-Clone-Server-Mongo
