### ISSUE TITLE
Unable to inject multiple providers for testing the module

### ISSUE THREAD

**Issue by shipraguptaa** [Urigo/graphql-modules#575]
I want to overwrite multiple providers to test the module but then I get error:
```
"errors": Array [
    [GraphQLError: injector.get(...).getUserOrgs is not a function],
    [GraphQLError: injector.get(...).handler is not a function],
    [GraphQLError: injector.get(...).getUserOrgs is not a function],
    [GraphQLError: injector.get(...).handler is not a function],
  ]

Test code:
const { schema, injector } = shellinitModule;
  it('FieldResolver of Query: shellInitData', async () => {
    injector.provide({
      provide: OrgProvider,
      overwrite: true,
      useValue: {
        getUserOrgs: () => (
          "sample json"
        )
      }
    });
    injector.provide({
      provide: LoginProvider,
      overwrite: true,
      useValue: {
        handler: (token, expiryTime, param, prefixTenantId, redirectLocation, resource, createSession) => ("sample json")
      }
    });
injector.provide({
      provide: SettingsProvider,
      overwrite: true,
      useValue: {
        getSettings: (clientkey, id, orgId, keys, url) => ("sample json")
      }
    });

const result = await execute({
      schema,
      document: gql `
      query shellInitData {
        shellInitData(expiryTime:"86399982", redirectLocation: "undefed") {
          userOrgs {
            orgName
          }
          handler {
            currentImsOrgId
          }
         userOrgSettings(clientkey: "app", Id:"test-module1", keys:"uo") {
            orgId,
          settings {
            key
            value
          }
        }
      }
    }
      `,
    });
    expect(result).toMatchSnapshot();
  });
```

**Comment by shipraguptaa** [comment]
@ardatan  can you help with this issue. Let me know if you need any information.

**Comment by kamilkisiela** [comment]
@shipraguptaa Are `OrgProvider`, `LoginProvider` and `SettingsProvider` providers part of one GraphQL Module or they are defined in multiple places?

Is it something like this?
```ts
const shellinitModule  = new GraphQLModule({
  providers: [
    OrgProvider,
    LoginProvider,
    SettingsProvider
  ]
});
```

**Comment by shipraguptaa** [comment]
@kamilkisiela They are defined in different modules and imported in shellInitModule like
const graphQLModule = new GraphQLModule({
  typeDefs,
  resolvers,
  providers: [OrgProvider, LoginProvider, SettingsProvider],
  imports: [commonModule, imsModule, loginModule, settingsModule],
});


then finally all these modules including  shellInitModule are loaded in parent index.js as one graphql module :
const modules = [];
fs
  .readdirSync(__dirname)
  .filter(file => fs.statSync(path.join(__dirname, file)).isDirectory())
  .forEach(directory => modules.push(require(path.join(__dirname, directory))));

module.exports = new GraphQLModule({
  imports: modules,
});

**Comment by kamilkisiela** [comment]
@shipraguptaa why do you define `OrgProvider` and the rest twice? Once in `providers: []` of main graphql module and once in `settingsModule`?

**Comment by shipraguptaa** [comment]
I have defined provider(lets say "OrgProvider") twice- once in the module where it belongs(lets say module "settingsModule") and second time in the module("shellInitModule") which uses "OrgProvider".
Now "shellInitModule" has multiple providers, some belongs to it and some are imported from other modules(dependency injection) to resolve fields.

My problem here is if I have to write test cases for "shellInitModule", I have to mock all the injector providers and I am unable to mock multiple providers as I am getting above error.

Below example just mocks one provider.
https://graphql-modules.com/docs/introduction/test-your-module 
Can you show an example for how to mock multiple providers?.

**Comment by ardatan** [comment]
@shipraguptaa Could you share more specific repo or something like that to get on the same page?

**Comment by ardatan** [comment]
I'm closing it for now so feel free to open new issue if the problem persists.
