### ISSUE TITLE
(Question) Any recommendations on subscriptions with federation?

### ISSUE THREAD

**Issue by veerjainATgmail** [Urigo/graphql-modules#583]
Hi,

Thanks for the apollo federation usage example.
What is your recommendation on the usage of subscriptions?, While gateway is used for Query and Mutation?

Thanks,
MJ

**Comment by ardatan** [comment]
GraphQL Modules does schema merging in this case while client server data exchange is done by Apollo. I think you should look for Apollo Federation documentation for more information.
