### ISSUE TITLE
Issues with type-graphql

### ISSUE THREAD

**Issue by cobraz** [Urigo/graphql-modules#590]
Hello 👋

Thank you for this awesome project. I'm testing `type-graphql` with `graphql-modules` and I'm having issues. Not exactly sure whether it's `type-graphql` or `graphql-modules` causing this, but it seems to me that the `context` (that includes `injector`) is not being passed to `type-graphql`.

I've implemented in accordance with the [recipe](https://graphql-modules.com/docs/recipes/type-graphql). To troubleshoot, I've added a simple `console.log` to the container function. It does not have the `injector` variable. I've tested with both `apollo-server` and `express-graphql`.
```javascript
extraSchemas: [
    buildSchemaSync({
      resolvers,
      container: ({context}) => {
        console.log('injector', context.injector);
        return context.injector;
      },
    }),
  ]
```

returns: `injector undefined`

It seems I'm not the only one either. antonwebflow is having the same issue, have a look at the implementation [here](https://github.com/antonwebflow/typeGraphQl).

**Comment by ardatan** [comment]
Could you try the following?
```ts
container: ({ context }) => ChatsModule.injector.getSessionInjector(context)
```

**Comment by cobraz** [comment]
I can't access that repository you referenced. This works 🎉

I have to @ts-ignore a lot to make that work.

**Comment by cobraz** [comment]
Thanks for the super quick response!
I've got it working 🎉

The example repository you referencing does not exist (at least for me).
