### ISSUE TITLE
Apollo recipe not working

### ISSUE THREAD

**Issue by cobraz** [Urigo/graphql-modules#591]
Hello 👋

I'm testing `apollo-server` and having issues with the recipe that is provided in the documentation. Schema is provided as expected, but resolvers seem to not be executed.

The implementation I'm using is in accordance with this [recipe](https://graphql-modules.com/docs/recipes/apollo-server).

**Comment by cobraz** [comment]
Let me know if you need more information or a reproduction repository.

**Comment by ardatan** [comment]
It'd better to see a reproduction and error.
You can check the following example;
https://github.com/Urigo/graphql-modules/tree/master/examples/apollo-modules

**Comment by Urigo** [comment]
@cobraz can you please create a reproduction?

**Comment by cobraz** [comment]
Yes, I will. Probably not until tomorrow, I'm afraid.

**Comment by kckst8** [comment]
Same here. typeDefs appear to load properly, but resolvers are not executing (using with fastify):

`const { gql } = require("apollo-server-fastify");
const { GraphQLModule } = require("@graphql-modules/core");

const typeDefs = gql`
  "OIDC user"
  type User {
    "the user's email address"
    email: String
    "the user's last name"
    family_name: String
    "the user's first name"
    given_name: String
    iss: String
    client_id: String
    org_name: String
  }

  "main Query type"
  type Query {
    "the current OIDC user info"
    user: User
  }
`;

const resolvers = {
  Query: {
    user: (parent, args, context, info) => {
      if (!context.user) {
        return;
      }
      return context.user;
    },
  },
};

const UserModule = new GraphQLModule({
  typeDefs: typeDefs,
  resolvers: resolvers,
});

module.exports = {
  UserModule,
};
`

In the main app.js:

const { ApolloServer } = require("apollo-server-fastify");
const { UserModule } = require("./graphql/schema");

`      // Register the Apollo GraphQL handler
      const apolloServer = new ApolloServer({
        modules: [UserModule],
        context: async ({ req }) => {
          // Attempt to add the user and entitlement status to the context object.
          // This will allow resolvers to implement their own authorization using just the global entitlement or specific user info
          let entitled = false;
          const token = req.headers.authorization || "";
          if (!token || !token.toLowerCase().startsWith("bearer"))
            return { entitled };
          const user = await introspect(token);
          if (user && user.active) {
            entitled = isUserEntitled(user);
          }
          return { user, entitled };
        },
      });

      fastify.register(apolloServer.createHandler());`

**Comment by kckst8** [comment]
In my case, when using with apollo-server and fastify, the resolvers are executing, but the context is not being passed:

`const typeDefs = gql`
  "OIDC user"
  type User {
    "the user's email address"
    email: String
    "the user's last name"
    family_name: String
    "the user's first name"
    given_name: String
    iss: String
    client_id: String
    org_name: String
  }

  "should be implemented for mutation response types"
  interface MutationResponse {
    code: String!
    success: Boolean!
    message: String!
  }

  "main Query type"
  type Query {
    "the current OIDC user info"
    user: User
  }
`;

// global resolver list. This will be modularized
const resolvers = {
  Query: {
    user: (parent, args, context, info) => {
      if (!context.user) {
        return;
      }
      return context.user;
    },
  },
};

const UserModule = new GraphQLModule({
  typeDefs: typeDefs,
  resolvers: resolvers,
});

module.exports = {
  UserModule,
};`

`      const apolloServer = new ApolloServer({
        modules: [UserModule],
        context: async ({ req }) => {
          // Attempt to add the user and entitlement status to the context object.
          // This will allow resolvers to implement their own authorization using just the global entitlement or specific user info
          let entitled = false;
          const token = req.headers.authorization || "";
          if (!token || !token.toLowerCase().startsWith("bearer"))
            return { entitled };
          const user = await introspect(token);
          if (user && user.active) {
            entitled = isUserEntitled(user);
          }
          return { user, entitled };
        },
      });

      fastify.register(apolloServer.createHandler());`

**Comment by ardatan** [comment]
@kckst8 Your case is different. Context is handled by GraphQL Modules internally. If you want to have context inside GraphQL Modules. You can use `context` build of GraphQL Modules like below;
```ts
export const CommonModule = new GraphQLModule({
  context: async ({ req }) => {
          let entitled = false;
          const token = req.headers.authorization || "";
          if (!token || !token.toLowerCase().startsWith("bearer"))
            return { entitled };
          const user = await introspect(token);
          if (user && user.active) {
            entitled = isUserEntitled(user);
          }
          return { user, entitled };
        },
}
})
const typeDefs = gql
  type User {
    email: String
    family_name: String
    given_name: String
    iss: String
    client_id: String
    org_name: String
  }

  type Query {
    user: User
  }
;

const resolvers = {
  Query: {
    user: (parent, args, context, info) => {
      if (!context.user) {
        return;
      }
      return context.user;
    },
  },
};

const UserModule = new GraphQLModule({
  typeDefs: typeDefs,
  resolvers: resolvers,
  imports: [CommonModule],
});

module.exports = {
  UserModule,
};

const apolloServer = new ApolloServer({
        modules: [CommonModule, UserModule],
        context: session => session,
      });
      fastify.register(apolloServer.createHandler());

```

**Comment by cobraz** [comment]
Hello. Still having mostly summer vacation, so things are taking longer than usual!

**Comment by cobraz** [comment]
Hello 👋!

Finally, I've been able to create a reproduction. Find it here:
https://github.com/cobraz/graphql-modules-apollo-typegraphql

**Comment by ardatan** [comment]
@cobraz Thank you for that repo! So there are three problems in that repo;
First for some reason Apollo Modules doesn't work well in the latest version of Apollo Server so we recommend you to pass `schema` instead of `modules` like below;
```
    this.server = new ApolloServer({
      schema: AppModule.schema,
```
And second like in our TypeGraphQL recipe you should pass `container` like below;
```
    container: ({ context }) => TodoModule.injector.getSessionInjector(context),
```
Finally the third one is that Apollo Server needs to be passed all session object in `context` option like in our Apollo Server recipe;
```
  context: session => session,
```
Let me know if the issue persists.
