### ISSUE TITLE
Injection Hook without TypeScript

### ISSUE THREAD

**Issue by szuercher** [Urigo/graphql-modules#624]
Can anyone give me an example how to inject a Hook without TypeScript. For example "OnConnect".

**Comment by ardatan** [comment]
`OnConnect` is an interface just to help you for the signature of `onConnect` method inside a provider. So in your provider, you can add a method called `onConnect` and use it. There is no need to add `implements OnConnect`. It doesn't have any effect for runtime.
```js
export class SomeProvider {
   onConnect(connectionParams, ...otherStuff){
     // This will be called on each WS connection start.
   }
}
```
