### ISSUE TITLE
Custom scalars don't run when using apollo-server `modules`

### ISSUE THREAD

**Issue by marvinroger** [Urigo/graphql-modules#628]
Hi,

You might want to see this: https://github.com/apollographql/apollo-server/issues/2218

My custom scalars did not run at all when using apollo-server, because I was following this: https://graphql-modules.com/docs/recipes/apollo-server, thus encountering the issue I linked above.

The solution was simple, instead of using apollo-server modules:

```js
const server = new ApolloServer({
  modules: [
    MyGraphQLModule
  ],
  context: session => session,
});
```

Simply use the executable schema:

```js
const server = new ApolloServer({
  schema: MyGraphQLModule.schema,
  context: session => session,
});
```

I don't know what the drawbacks are, but until this issue is fixed in apollo-server, it's probably a good idea to mention this in the docs. :wink:

**Comment by ardatan** [comment]
Yes, you are right. We should update documentation until  it gets fixed.

**Comment by ardatan** [comment]
Docs are updated!

**Comment by eliperelman** [comment]
An alternative solution from https://github.com/apollographql/apollo-server/issues/2218#issuecomment-593271456 also allows you to continue to use `modules` via the `@apollo/federation` package:

```ts
import { buildFederatedSchema } from '@apollo/federation';

const server = new ApolloServer({
  schema: buildFederatedSchema([MyGraphQLModule]),
});
```

**Comment by ardatan** [comment]
@eliperelman Apollo Federation package handles schema in a different way. That doesn't look like a good practice. We are already exposing `GraphQLSchema` in `GraphQLModule`. Just use it simply :)
