### ISSUE TITLE
Trying to inject config without `@Inject(ModuleConfig)` shows unclear error

### ISSUE THREAD

**Issue by dotansimha** [Urigo/graphql-modules#655]
If `@Inject(ModuleConfig)` is missing, the error is not informative enough. 

```
 - Provider #Object couldn't be injected into Provider #Something
```

I think, maybe we should detect if the required object is not a real object and then let people know that `@Inject` is missing? Because it happens when trying to inject an interface/type using tokens.

**Comment by ardatan** [comment]
Fixed in 0.7.11!
