### ISSUE TITLE
How to integrate Apollo upload server middleware

### ISSUE THREAD

**Issue by zicodeng** [Urigo/graphql-modules#665]
Hi, thanks for creating this awesome library. It changed the way how I modularize my code and enabled me to obtain separation of concerns!

A question on integrating this middleware: https://github.com/maticzav/graphql-middleware-apollo-upload-server? Where would I place it? during `new GraphQLModule` or `new ApolloServer`?

Thanks in advance!

**Comment by ardatan** [comment]
You should put it in Apollo Server because it is a server middleware, but we recommend you to use this recipe;
https://graphql-modules.com/docs/recipes/file-uploads

**Comment by zicodeng** [comment]
Awesome, thanks, I will take a look!
