### ISSUE TITLE
Extend type with field-level data resolution.

### ISSUE THREAD

**Issue by guibernardino** [Urigo/graphql-modules#700]
My app fetches data at field level.

Example:

## Module Event

Schema:

```
type Event {
  eventId: Int!
  userId: Int!
  title: String!
}

type Query {
  event(id: Int!): Event
}
```

Resolver:

```
export default {
  Query: {
    event: (root, { id }) => ({ eventId: id }) 
  },
  Event: {
    title: async ({ eventId }) => {
      const { title } = await getEvent(eventId);

      return title;
    },
    userId: async ({ eventId }) => {
      const { userId } = await getEvent(eventId);

      return userId;
    },
  }
}
```
##

I am trying to get the user's resolver to receive the userId that needs to be resolved in the event module.

## Module User

Schema:
```
type User {
  userId: Int!
  name: String!
}

extend type Event {
  user: User
}
```

Resolver:
```
export default {
  Event: {
    user: ({ userId }) => ({ userId: userId }),  // userId undefined
  },
  User: {
    name: async ({ userId }) => {
      const { name } = await getUser(userId);

      return name;
    },
  }
}
```

Response
```
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field User.userId.",
      "path": [
        "event",
        "user",
        "userId"
      ],
    }
  ]
}
```

**Comment by ardatan** [comment]
Parent object doesn't contain resolved fields, this is how GraphQL works normally(without GraphQL Modules, it would run in exactly same way). I think you should change your approach like below;
```ts
export default {
  Query: {
    event: (root, { id }) => getEvent(id)
  },
}
```
and
```ts
export default {
  Event: {
    user: ({ userId }) =>getUser(userId),  // userId undefined
  },
  }
}
```

**Comment by elincognito** [comment]
Hi, 
I run onto the same issue and the proposed solution won't work for me at least ideally:

For simplicity lets assume i have the following schema
I am also using codegen for generating types
``` 
type Event {
  eventId: Int!
  title: String!
  relatedField: String!
}

type Query {
  events(userId: Int!): [Event]
}

```

```
export default {
  Query: {
    events: (root, { userId }) => getUserEvents(userId)
  },
}
```

now here comes the issue
let's assume that to get the relatedField i need the userId

```
export default {
  Event: {
    relatedField: ({ eventId }) =>getRelatedField(eventId, userId)  // here we have no access to userId
  },
  }
}

```

In the above example I can see too solutions:
change the *Event* schema to include the userId schema (which IMO isn't a good solution to force a schema change to solve this problem)
Or add the userId to the context which supposedly isn't also a good solution.

Note: That i could also include  the *userId* in the top field resolver for *events* but with codegen 
generating the strict types i would get an error

**Comment by ardatan** [comment]
You're asking something that GraphQL doesn't have so the thing you asked is not an issue of neither GraphQL Modules nor GraphQL itself. GraphQL Modules doesn't have that kind of feature.

Let me give an example;
When you query something like that;
```gql
{
   events(userId: 2) {
      eventId
      title
      relatedField
   }
}
```
First, GraphQL Server calls `Query.events: (root, { userId }) => getUserEvents(userId)` function with `{}, { userId: 2,}` and for relatedField `Event.relatedField: ({ eventId }) =>getRelatedField(eventId, userId)` is called with the exactly same object you returned from `getUserEvents`. This is how GraphQL works. 

Also in codegen, you can use `mappers` to have different entity typings. So you can have an entity type like;
I assume you return `eventId` and `title` from `getUserEvents`.
```ts
export interface EventEntity {
  eventId: number;
  title: string;
  userId: number;
}
```

So after that you can add `userId`;
```
export const Query:QueryResolvers = {
    events: (root, { userId }) => ({ userId, ...getUserEvents(userId) })
}
```
and you can get it inside `Event`.
```
export const Event:EventResolvers = {
    relatedField: ({ eventId, userId }) =>getRelatedField(eventId, userId)  // here we have no access to userId    
}

```

**Comment by elincognito** [comment]
@ardatan  Thank you for taking the time to explain in more detail the mistakes on my assumptions.
I fixed my issue with codegen `mappers`
