### ISSUE TITLE
How to integrate mongoose with the modules.

### ISSUE THREAD

**Issue by KROSF** [Urigo/graphql-modules#704]
Hi, I started to use this amazing project but i ran into a problem.
I can't find the best way to integrate mongoose with the modules.
Can you help me.
Thanks.

**Comment by Urigo** [comment]
Hi @KROSF and thank you for the question!

It would actually be cool to have an example with Mongoose.
Could you maybe create one, even with the current errors you experience and share it here?

Then when we solve it everyone will enjoy a new working example of that integration

Thank you!

**Comment by KROSF** [comment]
Hi @Urigo thanks for your response.

The first idea i have was to create an model inside of each module

```ts
// src/modules/users/model.ts
import mongoose, { Schema, Document } from 'mongoose'
import { UserDbObject } from '@models'

export type UserSchema = UserDbObject & Document

const userSchema = new Schema({
  email: { type: String, required: true, unique: true },
  firstName: { type: String, required: true },
  lastName: { type: String, required: true }
})

export default mongoose.model<UserSchema>('User', userSchema)
```

And add the model as part of the context

```ts
// src/modules/users/index.ts
import { GraphQLModule, ModuleContext } from '@graphql-modules/core'
import { loadResolversFiles, loadSchemaFiles } from 'graphql-toolkit'
import { CommonModule } from '@modules/common'
import { UsersProvider } from '@modules/users/providers/users.provider'
import User, { UserSchema } from './model'

export type UserModuleContext = ModuleContext<{
  models: {
    User: UserSchema
  }
}>

export const UsersModule = new GraphQLModule({
  imports: [CommonModule],
  providers: [UsersProvider],
  typeDefs: loadSchemaFiles(__dirname + '/schema/'),
  resolvers: loadResolversFiles(__dirname + '/resolvers/'),
  context: {
    models: {
      User
    }
  }
})
```

but I think this is not the optimal solution when referring to other models.

**Comment by ardatan** [comment]
You don't need to use `context` to inject models. You can directly import it inside providers in my opinion.

**Comment by KROSF** [comment]
Thanks @ardatan.

**Comment by fridaystreet** [comment]
Also been working on a nice way to solve this problem while trying to ensure there is a decent level of abstraction from the db layer to the app. After a lot of trial and error, finally landed on the datasource approach shown in the graphql-modules doco coupled with some dependency injection to present the models to the app.

Basic premise is to have a very specific mongo module that loads the models and contains the mongo specific code in providers for each model. It creates a set of useFactory providers which initialise each model and it's datasource and present it via a string based DI token something like 'DataSource:Mongo:User'. Then have a  generic 'data' module that imports you mongo data module (and any others you might want to use) and presents those via useFactory providers with injectfunction('Datasource:Mongo:User') and present it to your app as 'Datasource:User'. Then just import your data source model to your app module. This allows you to use different technologies for different models in your app if required. Also means there is no db specific code in your app (like mongo.findOne or mongo query strings) . Well providing you want have that level of abstraction. obviously you could then just use the mongo models directly in you User provider if you only want mongo. We wanted more abstraction so we could start to migrate som parts of our data to diffewrent services.

generic data module looks something like this:

```
export const DataSources = new GraphQLModule({
  name: 'DataSources',
  imports: [ MongoDatasource],
  providers: [
    {
      provide: 'DataSource::User',
      scope: ProviderScope.Session,
      useFactory: InjectFunction('DataSource::Mongo::User')(User => User)
    },
    {
      provide: 'DataSource::Passport',
      scope: ProviderScope.Session,
      useFactory: InjectFunction('DataSource::Mongo::Passport')(Passport => Passport)
    },
    {
      provide: 'DataSource::Domain',
      scope: ProviderScope.Session,
      useFactory: InjectFunction('DataSource::Mongo::Domain')(Domain => Domain)
    },
    {
      provide: 'DataSource::Task',
      scope: ProviderScope.Session,
      useFactory: InjectFunction('DataSource::Mongo::Task')(Task => Task)
    }
  ]
});
```

then you user provider has constructor something like

constructor(
    private moduleSessionInfo: ModuleSessionInfo,
    @Inject('DataSource::User') private User: any
)
Then in you provider functions

this.User.myAbstractedDatasourceFunction(user, params)
 
or direct to mongo
this.User.find({ mymongo query})
