### ISSUE TITLE
MongoDB with generic-pool

### ISSUE THREAD

**Issue by Simon12121** [Urigo/graphql-modules#717]
Hello,

All tools provided by you (i.e. authentication) worked really good. However I am struggling to implement the database connection pooling in combination with MongoDB. I'm using the code from https://graphql-modules.com/docs/recipes/db-connection-pooling. 
Instead of returning a connection, there occors an infinite loop in the acquire function from 'generic-pool'. I have searched also in the internet but there were no results.
I have found out that through adding`{
                max: 10
            }` to the createPool function in database.module.ts, the infinite loop does not occur anymore, but now _poolClient is always undefined.

Does anyone have any idea why this behavior occurs?
Thanks in advance

**Comment by ardatan** [comment]
@Simon12121 Could you share a repo?

**Comment by Simon12121** [comment]
Sorry for claiming that the code does not work. While building the repo i found out that i forgot to add a return in a then block. So now everything works fine.
I am just not sure about one thing: I found a lot of examples (like this: http://mongodb.github.io/node-mongodb-native/driver-articles/mongoclient.html#mongoclient-connection-pooling), where also only one connect call was executed, but in addition to this there was no manual pooling used. Which way is more performant?
Could adding this option to createPool increase the performance even more?
`createPool(
    {
        create: () => MongoClient.connect('the mongourl', { useUnifiedTopology: true, useNewUrlParser: true }),
        destroy: client => client.close(),
    },
    {
        max: 10
    }
)`

Thanks in advance
Simon

**Comment by ardatan** [comment]
I don't think it matters since MongoDB handles queries async internally :)
