### ISSUE TITLE
Typing issue with at least two nexus projects

### ISSUE THREAD

**Issue by valentinpalkovic** [Urigo/graphql-modules#738]
If a user wants to use at least two nexus modules within the same project, the types are generated properly, but not usable at once (see: https://github.com/ardatan/NexusGraphQLModules/issues/2 and https://github.com/prisma-labs/nexus/issues/269). The generated types of one module will overwrite the generated types of the other module.

The example project https://github.com/ardatan/NexusGraphQLModules is therefore not workable! More than one nexus module is therefore not supported with graphql modules atm.

**Comment by ardatan** [comment]
Are those typings of different modules generated in different folders?

**Comment by valentinpalkovic** [comment]
Yes. the typings are generated in separate folders.

**Comment by kamilkisiela** [comment]
Closing in favor of #1466
