### ISSUE TITLE
resolversComposition error with extrasSchema

### ISSUE THREAD

**Issue by silas-joekel** [Urigo/graphql-modules#741]
I have a module for authentication which exports AuthModule and isAuthenticated, which is just a function to use in resolversComposition.

Everything works as intended in modules which import AuthModule and the function, but in the AuthModule itself the functions i put in resolversComposition don't get called.

I guess this is because I use extrasSchema with TypeGraphQL and the schema is not loaded when graphql-modules tries to add the resolversComposition.

I can't get the AuthModule to use the functions from resolversComposition, am I missing something?

**Comment by ardatan** [comment]
Could you share a reproduction repo?

**Comment by lewebsimple** [comment]
Is it possible you are configuring `resolversComposition` from a different module than the one with `extraSchemas` ?

I'm having a similar issue when trying log all queries from `LogModule`, which has no schema whatsoever. Does `resolversComposition` always have to reside next to the Queries / Mutations it affects ?

**Comment by kamilkisiela** [comment]
We released a new major version (v1.0) of GraphQL Modules. Here's the [migration guide](https://graphql-modules.com/docs/next/recipes/migration).

The new version doesn't support `extraSchemas` (yet) but I put it under #1466 umbrella and closing the thread.

Please try to upgrade. If you can't and still want to use the legacy version, please open a new issue.
