### ISSUE TITLE
ModuleSessionInfo not available on schema directives

### ISSUE THREAD

**Issue by waldemarnt** [Urigo/graphql-modules#744]
Hey! I've been trying to use `ModuleSessionInfo` inside a provider that is being injected via `injector` inside a `schemaDirective` but I get the error `Provider #ModuleSessionInfo not provided in #Module` which means that ModuleSessionInfo wasn't built yet.
Is it expected?

Codesandbox example: https://codesandbox.io/s/thirsty-lake-zmc4p

Looks like the context is built after the directive resolves, any idea how to deal with this?

**Comment by ardatan** [comment]
Could you share a reproduction on codesandbox by any chance?

**Comment by waldemarnt** [comment]
@ardatan here we go :D https://zmc4p.csb.app/ let me know if you need anything else

**Comment by kamilkisiela** [comment]
We released a new major version (v1.0) of GraphQL Modules. Here's the [migration guide](https://graphql-modules.com/docs/next/recipes/migration).

The new version solves the issue, so I'm closing the thread.

Please try to upgrade. If you can't and still want to use the legacy version, please open a new issue.
