### ISSUE TITLE
Isolation of modules

### ISSUE THREAD

**Issue by rahul22048** [Urigo/graphql-modules#747]
We have an application in which we have many different modules. Now suppose there is some buggy code inside some module provider, now considering the fact that node is single threaded and everything runs in event loop , all subsequent requests will be blocked. So ideally all modules should have some sort of isolation, where a bug in one module is not affecting other modules.  This can be achieved either by running every module code is separate thread or separate process. Is this achievable in GraphQL modules?

**Comment by artakvg** [comment]
@rahul22048  you have many Providers and modules maybe you'll have an idea for a workaround for this? https://github.com/Urigo/graphql-modules/issues/745

I am sure Graphql modules is not providing such tooling now. But this is something that your CI/CD should be responsible for.

**Comment by rahul22048** [comment]
Can this be taken as a feature request? When I am doing injector.get(Provider) I should have some sort of option over here to tell whether I want to run the code in the provider in a separate thread or process. Simply because most likely it will be making a downstream API call, I don't want some buggy code in other repo to affect my repo

**Comment by fenos** [comment]
@rahul22048 It doesn't make sense to have that functionality built in **graphql-modules**.
What you are after is **GraphQL federation**.

Create an independent graphql server running on a different port / process for the modules that you want total isolation. Then use federation to unify the schemas.

Now you have total isolation of your modules.

**Comment by rahul22048** [comment]
Ok. Thanks for the response. You can close the ticket at your end.

**Comment by ardatan** [comment]
GraphQL Federation uses different GraphQL backend servers through the network connection, so you can achieve what you want in this way; because each module in GraphQL Modules has its own encapsulated valid schema.
