### ISSUE TITLE
Example not working from Doc: Load Your Schema and Resolvers

### ISSUE THREAD

**Issue by kbdavis07** [Urigo/graphql-modules#773]
![image](https://user-images.githubusercontent.com/5434970/68558832-c041ab00-0408-11ea-81b1-9e7dfe24c89d.png)

I am following along with this example and TypeDefs keeps giving error 

![image](https://user-images.githubusercontent.com/5434970/68558900-0565dd00-0409-11ea-97cd-f932c28dd46b.png)

Is there a working example some where that shows how to load multiple files for Types and Revolvers for a module?

Thanks,

Brian Davis

**Comment by ardatan** [comment]
@kbdavis07 Do you use TypeScript? If yes, you should copy your graphql files into `dist/` folder. If no, could you share a reproduction repo?

**Comment by kbdavis07** [comment]
@ardatan I managed to get the code from Examples https://github.com/Urigo/graphql-modules/tree/master/examples/apollo-modules 

Working the way I wanted to have modules.

Thanks for your help 👍

**Comment by bombillazo** [comment]
> 
> 
> @ardatan I managed to get the code from Examples https://github.com/Urigo/graphql-modules/tree/master/examples/apollo-modules
> 
> Working the way I wanted to have modules.
> 
> Thanks for your help 👍

That example is no longer in the repo, how did you fix the dynamic loading problem?

**Comment by Urigo** [comment]
@bombillazo the docs have been updated: https://www.graphql-modules.com/docs/essentials/type-definitions#dynamically-load-sdl-files
Please open a new issue with an example if that didn't work for you

**Comment by bombillazo** [comment]
Thanks for the update. 

Does this approach work for `.ts` files that are exporting a `gql` const? E.g.

```ts
import { gql } from 'graphql-modules';

export const myTypeDef = gql`
type MyType {
  id: ID
  prop: string
}
`;
```
