### ISSUE TITLE
Nest.js vs graphql-modules for new project. Or both?

### ISSUE THREAD

**Issue by zenVentzi** [Urigo/graphql-modules#817]
I have experience with Express, Apollo server and related technologies separately, but have never used graphql-modules or nest.js. Do these two combine? If they don't, how can one decide which one to use?

**Comment by LucienLee** [comment]
You should choose one of them, but not both. 

It depends on what kind of style you like to write grapql.
NestJS use the [TypeGraphQL](https://github.com/MichalLytek/) style to write resolver, which uses metadata annotations to specify the type. It would write a class like:

```ts
@Resolver('Author')
export class AuthorResolver {
  constructor(
    private readonly authorsService: AuthorsService,
    private readonly postsService: PostsService,
  ) {}

  @Query()
  async author(@Args('id') id: number) {
    return this.authorsService.findOneById(id);
  }

  @ResolveProperty()
  async posts(@Parent() author) {
    const { id } = author;
    return this.postsService.findAll({ authorId: id });
  }
}
``` 

Correspondingly, the pure resolver just an object with lots of resolve functions. just like

```ts
import authorsService from '...'

const resolvers = {
  Query: {
    author(parent, args, context, info) {
      return authorsService.find(authors, { id: args.id });
    },
  },
  Mutation: {}
}
```
If you prefer that and want DI in the grapql, graphql-module will be your choose. 

Another factor is will you want to use Apollo Federation. 
NestJS has a waiting big PR for that https://github.com/nestjs/graphql/pull/455. If you want to use federation now, graphql-modules will be better.

Finally, you might want to consider community activity. NestJS has larger community than graphql-module. It looks like @ardatan is the only maintainer now. I hope that the [guild](https://github.com/the-guild-org) members could take more attention on this project. I really hope that this project could maintain it's healthy.

**Comment by MichalLytek** [comment]
@LucienLee you can use TypeGraphQL with GraphQL Modules 😉 

https://graphql-modules.com/docs/recipes/type-graphql
