### ISSUE TITLE
How to use logger in the module?

### ISSUE THREAD

**Issue by LucienLee** [Urigo/graphql-modules#850]
Instead of providing official logger plugin, graphql-modules give logger interface now.
I see that we could pass logger functions when initiating module. But I have no idea how to call logger in my resolvers or providers. 

https://github.com/Urigo/graphql-modules/blob/eecfc5208f00387b2d6595da98b1510bc137be2b/packages/core/src/graphql-module.ts#L28-L33

Could you give some hints about what's the best practice in your design?

**Comment by ardatan** [comment]
Hi @LucienLee 

You have two options;

First you can use DI;
Currently `Logger` is not part of DI but you can make it part of DI like below. Let's say you have `Logger` class.
`logger.provider.ts`
```ts
import { Logger } from '@graphql-modules/core';
import { Injectable } from '@graphql-modules/di';
@Injectable()
export class LoggerProvider implements Logger {/*...*/}
```
`logger.module.ts`
```ts
import { GraphQLModule, Logger } from '@graphql-modules/core';
import { InjectFunction } from '@graphql-modules/di';
import { LoggerProvider } from './logger.provider';
export const LoggerModule = new GraphQLModule({
   providers: [LoggerProvider],
   logger: InjectFn((loggerProvider: LoggerProvider) => loggerProvider)
})
```
`example.resolver.ts`
```ts
import { LoggerProvider } from '@modules/logger/logger.provider';
export const Query = {
   foo: (_, __, { injector }) => {
      const logger = injector.get(LoggerProvider);
      logger.info('foo called!');
      return true;
   }
}
```

Second you can access module's `selfLogger` attribute to get `logger` of that module;
```ts
import { LoggerProvider } from '@modules/logger/logger.provider';
export const Query = {
   foo: (_, __, { injector }) => {
      const logger = FooModule.selfLogger;
      logger.info('foo called!');
      return true;
   }
}
```

**Comment by LucienLee** [comment]
The signature of `InjectFunction` is changed. The correct version is that:  

```ts
import { GraphQLModule } from '@graphql-modules/core';
import { InjectFunction } from '@graphql-modules/di';
import { LoggerProvider } from './logger.provider';

export const LoggerModule = new GraphQLModule({
  providers: [LoggerProvider],
  logger: InjectFunction(LoggerProvider)(
    (loggerProvider: LoggerProvider) => loggerProvider
  ),
});

```

**Comment by ardatan** [comment]
Sorry my bad. I forgot to add `LoggerProvider` at the beginning :)

**Comment by LucienLee** [comment]
Yeah, but I have a proposal on `Logger` and `LogMethod ` interface. Should I open a new issue, or just discuss it here?

**Comment by ardatan** [comment]
@LucienLee It doesn't matter

**Comment by LucienLee** [comment]
First, add more common optional methods.

```ts
export interface Logger {
  log?: LogMethod;
  debug?: LogMethod;
  info?: LogMethod;
  warn?: LogMethod;
  error?: LogMethod;
  clientError?: LogMethod;
}
```

Second, use overload instead of union type on `message` type, which could be useful when you certainly know what's the message type. For example, when you pass a pure string to the logger, you don't have to case it.  But keep `(message: string | Error): void;`, `logger.clienError` uses the `ILogger` type from `graphql-tool`. 

Finally, add spread meta property in order to user want to pass more context to the logger.

```ts
export interface LogMethod {
  (message: string, ...meta: any[]): void;
  (message: Error, ...meta: any[]): void;
  (message: string | Error): void;
}
```

How do you think, @ardatan? If it looks good, I have prepared a PR for you.

**Comment by LucienLee** [comment]
@ardatan any schedule of releasing?

**Comment by LucienLee** [comment]
@ardatan Sorry to bother you continually. Could you make a version bump and release it first?

**Comment by ardatan** [comment]
@LucienLee You can use this canary version for now;
`0.7.15-alpha-15a59a4.120+15a59a4`
