### ISSUE TITLE
Mock context does not appear on context within Resolvers

### ISSUE THREAD

**Issue by CVANCGCG** [Urigo/graphql-modules#863]
I can't access my mocked context object via the mock({ contextBuilder() => {} }). My error appears to be very similar to the same symptoms reported with [Issue #443](https://github.com/Urigo/graphql-modules/issues/443). Per that issue, I tried version 0.7.6 but didn't have expected outcome. Note that the query behaves correctly with real application users that are logged in but my automated tests written in Jest do not provide my mocked context object that I create in contextBuilder which causes my tests to fail when I access the context.currentUser property.

**Expected behavior**: In resolver functions, ```context.identity``` should be set to the mocked object via ResearchModule.mock({...})

**Observed behavior**: ```context.identity``` is undefined within my resolver functions and the mocked object is nowhere to be found while running unit tests and results in a failure when I require access to the user identity, i.e. context.identity.

My GraphQL module definition.
```
// Add the context mock since we don't have an interactive user in automated tests
BookModule.mock({
Promise<ModuleContext<Context>>;
  contextBuilder: async (_ses, _exclude): Promise<ModuleContext<PerCallContext>> => {
    return { 
       session: _ses, 
       injector: BookInjector, 
       identity: {
        email: 'user@jest-test.com',
      },
    }
  },
})
```

My GraphQL module Jest test
```
describe('BookModule correctly processes GraphQL requests with Mock API providers', () => {
  beforeAll(async () => {
    await initializeConfig()
    // Setup Provider mock for entire BookApi so we can run an isolated test w/o needing to call the real APIs
    BookInjector.provide({
      provide: BookApi,
      overwrite: true,
      useValue: {
        async getAll(): Promise<Book[] | undefined> {
          const hardback = <HardCoverBook>{
            id: 'HardCoverBook.1',
            title: 'Away from Home, in Los Angeles',
          }
          return [hardback]
        }
      },
    })
  })

// My test that fails to build the mock context object that is required in my resolver.
  it('Query::allBooks returns correct results from provider', async () => {
    const result = await execute({
      schema: BookSchema,
      document: gql`
        query {
          allBooks {
            id
            title
          }
        }
      `,
    })

    expect(result.errors).toBeFalsy()
    expect(result.data!.allBooks.length).toBe(1)
  })
})
```

Any suggestion on how to properly mock the context object so that the identity object is available via context.identity within my resolvers would be appreciated. Thank you.

**Comment by kamilkisiela** [comment]
We released a new major version (v1.0) of GraphQL Modules. Here's the [migration guide](https://graphql-modules.com/docs/next/recipes/migration).

The new version solves the issue, so I'm closing the thread.

Please try to upgrade. If you can't and still want to use the legacy version, please open a new issue.
