### ISSUE TITLE
Dependency injection not working for providers in the same module.

### ISSUE THREAD

**Issue by dalkegama** [Urigo/graphql-modules#913]
I'm having issues with DI. I have a module that has 2 providers. Both providers are declared in the `providers` array in `index.ts`. 

**FooPovider** has a simple method that does a `console.log`, I've injected **FooPovider** into **BarPovider** `constructor(private fooPovider: FooPovider)` as shown in the [Docs](https://graphql-modules.com/docs/introduction/dependency-injection#import-providers-from-other-modules). But when I'm calling **FooPovider's** method inside **BarPovider**, I'm keeping getting `"message": "Cannot read property 'foo' of undefined"`. But if I do the following:
```
const fooPovider: FooPovider; 
constructor(){
    this.fooPovider = new FooPovider()
}
```
then I can access methods in FooPovider. Clearly my class isn't getting instantiated when I do normal DI. 
I found out if I do `constructor(@Inject(FooPovider) private fooPovider: FooPovider) {}` then the class get an instance of the FooPovider. Is this expected way to do this? It doesn't feel right to call **@Inject(...)** here for a simple provider.
I would expect this: `constructor(private fooPovider: FooPovider)` to work out of the box.

**Comment by ardatan** [comment]
Something might be wrong in your configuration and types are not reflected as metadata. Could you share a reproduction repo so we can help better?

**Comment by dalkegama** [comment]
@ardatan ,here is the reproduction of my [qapi-test](https://github.com/dalkegama/qapi-test) repo. We were thinking, maybe being caused by the use of the `@graphql-toolkit`. Thank you.

**Comment by dalkegama** [comment]
Any update on this ?

**Comment by aylesm** [comment]
I have the same issue.

**Comment by mattleff** [comment]
I had this same issue and thanks to @ardatan's tip discovered the fix was enabling `emitDecoratorMetadata` in my `tsconfig.json`:

```ts
{
	"compilerOptions": {
		...
		"experimentalDecorators": true,
		"emitDecoratorMetadata": true,
		...
	}
	...
}
```

**Comment by ardatan** [comment]
@dalkegama 's reproduction is missing `emitDecoratorMetadata` which will be fixed by @mattleff 's change.
Closing the issue for now. Feel free to open a new one if it still persists.
