### ISSUE TITLE
How do I use JavaScript instead of TypeScript

### ISSUE THREAD

**Issue by jermsam** [Urigo/graphql-modules#965]
My intention is to go modular but the limitation I have is with the fact that defining a custom context seems to be rigidly tied to typescript. Is there a way I can approach this within .js type module files instead of .ts as explained in the docs?
Using:
graphql 14.6.0
@graphql-modules/core 0.7.14
apollo-server-express 2.10.1

**Comment by iannickb** [comment]
They have a decent example inside the project:
https://github.com/Urigo/graphql-modules/tree/master/examples/basic-with-dependency-injection-js

**Comment by kamilkisiela** [comment]
Closing in favor of #1467
