### ISSUE TITLE
pubsub communication between modules doesn't seem to work as per doco

### ISSUE THREAD

**Issue by fridaystreet** [Urigo/graphql-modules#975]
I'm trying to get some pubsub communication to happen between modules as per the doco here

https://graphql-modules.com/docs/recipes/communication-between-modules

The problem is that the provider that I want to receive the message and do something with the event is never called during the request, so it's constructor isn't called and so it never registers it's subscription. 

The setup. 
common module that provides the PubSub class. 

Task module, that creates tasks. It has an injectable Task provider class.  The task module imports the common module. resolver for createTask injects the task provider and calls the createTask function in provider.

Mutation: {
    createTask: (root, args, { injector }, info) => injector.get(Task).create({...args, fields: getRequestedFields(info)})
}

I then have a notification module.  It has an injectable notification provider class. in this class in the constructor is a pubsub.subscribe('taskcreated'....). It's module imports common. It is injected in resolvers related to getNotificationsForUser (for example). 

If I publish a 'taskcreated' event in the task provider, the subscriber in my notification module never gets the event. if I add a subscription to the event in my task provider constructor, then I can see the event.

So the pubsub itself is working fine, and TBH what happens above almost sounds like it would be correct. Why would my notifications provider's constructor be called if it's not a request that would require it to be injected.

So my question is in your doco it reads as though the above should actually work, so I was wondering if there is some magic underneath that is instantiating all the providers when the app loads that I'm missing? Or if the example in the demo in fact doesn't work? 

If it doesn't how would a provider that isn't directly used in the request (possibly even be completely remote) be able to register it's subscriptions to the pubsub system and process the events?

Cheers
Paul

**Comment by fridaystreet** [comment]
update: I thought maybe it was because Task module needed to import Notifications module rather than them effective being siblings, but I tried that too and still the notifications provider is never instantiated.

**Comment by bailycase99** [comment]
I had this same issue, I'm using Apollo-Server. I have PubSub created in my entry point and passing it through context.
```js
const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: ({req, res}) => ({req, res, pubsub: pubsub}),
});
```

I used context again in the module to pass my pubsub through.

```js
export const gameModule = new GraphQLModule({
  typeDefs: gameTypeDefs,
  resolvers: gameResolver,
  imports: [userModule],
  context: session => {
    return {
      pubsub: session.pubsub,
    };
  },
});
```

**Comment by mohamedGamalAbuGalala** [comment]
I used [OnRequest hook](https://graphql-modules.com/docs/introduction/dependency-injection#onrequest-hook) to register my subscriber on the other provider and it works.

So we have 2 modules
* A (has AProvider)
* B (has BProvider)


- [ ] AProvider publish an event with some payload as the doc example

- [ ] BProvider implements OnRequest to initiate an instance on each request and have the subscribe logic on the OnInit code.
```typescript
async onRequest (): Promise<void> {
    await this.pubsub.subscribe(
      'someEvent',
      (payload) => {
        logger.info(`default subscribe success ${payload}`)
      }
    )
  }
```

**Comment by fridaystreet** [comment]
@mohamedGamalAbuGalala  That is exactly what I'm looking for. I knew there would be somewhere that wasn't so hacky as context, just forgot about the onRequest hook. That's a perfect place to put it and keeps code nice and descriptive. nice solution, thanks!

**Comment by mohamedGamalAbuGalala** [comment]
Consider trying [OnInit hook](https://graphql-modules.com/docs/introduction/dependency-injection#oninit-hook),
I didn't try it but I think it might work and maybe its best than OnRequest hook.
In my case, I'm working on a serverless graphql app so each function call(request) is considered a new app initialization so it doesn't make any difference between the 2 hooks.

**Comment by fridaystreet** [comment]
@mohamedGamalAbuGalala ok thanks for the update. Yes we are building the same, a totally serverless graphql. Really liking the way graphql-modules gels so nicely with serverless
