### ISSUE TITLE
Is cli tooling planned to be developed?

### ISSUE THREAD

**Issue by NemeSnz** [Urigo/graphql-modules#980]
I think cli tooling would be helpful to get ahead of recurring boilerplate. Are there any plans to develop cli tooling for graphql modules in the near future?

**Comment by LucienLee** [comment]
The author @Urigo has taken the maintenance of [graphql-cli](https://github.com/Urigo/graphql-cli). I think that you can propose that.

**Comment by kamilkisiela** [comment]
Kind of, we started making Modules a first class citizen in graphql codegen https://graphql-code-generator.com/docs/presets/graphql-modules
