### ISSUE TITLE
Using injection to overwrite imported modules. 

### ISSUE THREAD

**Issue by gagoar** [Urigo/graphql-modules#991]
Thanks for building this amazing system. it makes GraphQL easy to maintain and evolve over time. ❤️ 

## Context:
We have several modules with their particular injectors and we wish to provide in the outermost module an override to all the imported modules. This is helpful for a couple of reasons. 

- ***_Env awareness is isolated_***: the individual modules don't need to be aware of this provider override and will keep the module testable in isolation. 
- ***_DRY_***: we don't need to change every module to inject or modify the dependency injection.  
- ***_Control on overrides_***: If we inject the overrides in the outermost Module, we ensure that it will be applied to all of them. instead of doing it on every module which feels fragile and we will need to make sure developers changing every individual module don't affect the order in which the overrides are positioned (every provider gets applied sequentially from left to right).
- ***_Efficiency_***: in this case, the factory (for the provided injection) will be recreated only when the Application starts. returning the same instance for every module assuming the scope is `ProviderScope.Application` (today it instantiates the same provider every time a module invokes it).

## Example
We are going to consider for this example 3 GraphQL modules `moduleA`, `moduleB`, `moduleC`. Every module has already a provider named`ProviderOne`.  We want to overwrite `ProviderOne` when env variables change in a single place instead of having to do it on every module. 

considering `ProviderOne` and `ProviderOneOverride`:
``` typescript

// ProviderOne.ts => Provider definition, that also could be a Graphql module by itself, but the behaviour will be the same. 
export const ProviderOne = [{
  provide: 'ProviderOne',
  useFactory() {
    return {};
  },
  scope: ProviderScope.Application,
  overwrite: true,
}];
```
``` typescript
// ProviderOneOverride.ts  => This will be the override we wish we could inject at the outermost level. 
export const ProviderOneOverride = (): Provider[] => {
  if (env.isProd) {
    return [{
      provide: 'ProviderOne',
      useFactory() {
        return new Map();
      },
      scope: ProviderScope.Application,
      overwrite: true,
    }];

  } else {
    return [];
  }
};
```
### Current use:

``` typescript
export const moduleA = new GraphqlModule({
  imports: [...],
 provides: [ProviderOne, ProviderOneOverride]
});
// similar with module B, C
```
``` typescript
// index.ts  => This will be the outermost module that is later on passed to [apolloServer#modules](https://github.com/apollographql/apollo-server/blob/38ad4386a9585d249d24eb74aa6adac9ff0758f8/packages/apollo-server-core/src/types.ts#L95)
export default new GraphQLModule({
  imports: [moduleA, moduleB, moduleC]
});
```

### Intended use:
``` typescript
export const moduleA = new GraphqlModule({
  imports: [...],
  provides: [ProviderOne]
});

// similar with module B, C
```
``` typescript
// index.ts  => This will be the outermost module that is later on passed to [apolloServer#modules](https://github.com/apollographql/apollo-server/blob/38ad4386a9585d249d24eb74aa6adac9ff0758f8/packages/apollo-server-core/src/types.ts#L95)
export default new GraphQLModule({
  imports: [moduleA, moduleB, moduleC],
  provides: [someInjectionOveride()]
});
```
### Alternative to the intended use:

We could also add a `overrides` param to the [GraphqlModule API](https://github.com/Urigo/graphql-modules/blob/89cf7c3fa593aa4167edd04c71f08b23a849b90d/packages/core/src/graphql-module.ts#L73-L128) that will be used for this particular intent:

``` typescript
export const moduleA = new GraphqlModule({
  imports: [...],
  provides: [ProviderOne]
});

// similar with module B, C
```
``` typescript
// index.ts  => This will be the outermost module that is later on passed to [apolloServer#modules](https://github.com/apollographql/apollo-server/blob/38ad4386a9585d249d24eb74aa6adac9ff0758f8/packages/apollo-server-core/src/types.ts#L95)
export default new GraphQLModule({
  imports: [moduleA, moduleB, moduleC],
  overrides: [someInjectionOveride()]
});
```
 
Thanks!

**Comment by kamilkisiela** [comment]
We released a new major version (v1.0) of GraphQL Modules. Here's the [migration guide](https://graphql-modules.com/docs/next/recipes/migration).

The new version brings much more abstraction-friendly DI, so I'm closing the thread.

Every token/provider defined in a module depends on tokens provided by the application. Creation of Modules and Application is now done with functions so you should be able to modify modules as you wish.

Please try to upgrade. If you can't and still want to use the legacy version, please open a new issue.
