### ISSUE TITLE
Cannot declared custom resolver for extension field from type imported using extraSchema

### ISSUE THREAD

**Issue by leops** [Urigo/graphql-modules#993]
I'll try to provide a reproduction case by hand, not sure it that will actually work as my actual code is a lot more complicated but what I'm trying to do is essentially this:

```js
// Build a schema using graphql-js or another library
const schema = buildSchema(`
    type ParentType {
        field: String
    }
`);

// Expose the schema as a module
const externalModule = new GraphQLModule({
    extraSchemas: [schema],
});

// Extend the existing ObjectType with a new field with a custom resolver function
const extensionModule = new GraphQLModule({
    typeDefs: `
        extend type ParentType {
            customField: String!
        }
    `,
    resolvers: {
        ParentType: {
            customField: () => console.log('never called'),
        },
    },
    imports: [externalModule],
});
```

When introspecting the schema, I can see that `customField` is correctly registered on `ParentType`. But when I try to query it, the custom resolver function is never called and I get a `Cannot return null for non-nullable field ParentType.customField` error

**Comment by leops** [comment]
While I was trying to narrow down the issue and / or work around it, it suddenly disappeared (even after I reset my code to how it originally was). I guess despite it being reliably reproductible that was due to some stale build cache on my side or some other side effect.

**Comment by lewebsimple** [comment]
I'm having a similar issue when trying to use `@nexus/schema` inside graphql-modules.
